### PR TITLE
🐛 secrets manager: fix error handling when creating secrets (0.4 canonical)

### LINKED ISSUE #1561: Error handling of AWS Secrets Manager
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Scenario:
On a management cluster with networking issues, primarily DNS resolution of A records on AWS endpoints, the machine fails to provision with the following:

```
"msg"="Failed to create AWS Secret entry" "error"="RequestError: send request failed\ncaused by: Post https://secretsmanager.region.amazonaws.com/: dial tcp [ipv6]:443: connect: cannot assign requested address" "awsCluster"="cbf22a8cb356" "awsMachine"="control-plane-cbf22a8cb356-0" "cluster"="cbf22a8cb356" "machine"="control-plane-cbf22a8cb356-0" "namespace"="cbf22a8cb356" "secretPrefix"="aws.cluster.x-k8s.io/986d64b7-4c2c-41f6-9f1f-1bf0c30cf05a"
I0214 00:00:00.0       1 recorder.go:52] controller-runtime/manager/events "msg"="Warning"  "message"="RequestError: send request failed\ncaused by: Post https://secretsmanager.region.amazonaws.com/: dial tcp [ipv6 address]:443: connect: cannot assign requested address" "object"={"kind":"AWSMachine","namespace":"cbf22a8cb356","name":"control-plane-cbf22a8cb356-0","uid":"986d64b7-4c2c-41f6-9f1f-1bf0c30cf05a","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha2","resourceVersion":"1652470111"} "reason"="FailedCreateAWSSecretsManagerSecrets"
```

Attempts to delete are then compounded by:
```
E0213 00:01:00      1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="secretPrefix present, but secretCount is not set"  "controller"="awsmachine" "request"={"Namespace":"cbf22a8cb356","Name":"control-plane-cbf22a8cb356-0"}
```

**What did you expect to happen:**
* Appropriate attempt at retries
* Deletions to succeed

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.4.9
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1561

Updates state machine of secrets to handle intermittent failures by retrying creation of secrets, and making sure secrets are deleted prior to creation.

### CODE REVIEW

File: pkg/cloud/scope/machine.go [hunk 1]
```diff
@@ -211,6 +211,9 @@ func (m *MachineScope) DeleteSecretPrefix() error {
 // GetSecretCount returns the number of AWS Secret Manager entries making up
 // the complete userdata
 func (m *MachineScope) GetSecretCount() int32 {
+	if m.AWSMachine.Spec.CloudInit == nil {
```
Comment (vincepri) [inline pkg/cloud/scope/machine.go]: Are we calling this method when `CloudInit` is nil anywhere?

File: pkg/cloud/services/secretsmanager/secret.go [hunk 2]
```diff
@@ -76,12 +76,12 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
 }
 
 // Delete the secret belonging to a machine from AWS Secrets Manager
-func (s *Service) Delete(m *scope.MachineScope) error {
+func (s *Service) Delete(prefix string, chunkCount int32) error {
```
Comment (vincepri) [inline pkg/cloud/services/secretsmanager/secret.go]: Is this just a style preference? I'm not sure what is the benefit w.r.t. the linked issue

File: pkg/cloud/services/interfaces.go [hunk 3]
```diff
@@ -39,6 +39,6 @@ type EC2MachineInterface interface {
 // SecretsManagerInterface encapsulated the methods exposed to the
 // machine actuator
 type SecretsManagerInterface interface {
-	Delete(m *scope.MachineScope) error
+	Delete(prefix string, chunkCount int32) error
```
Comment (vincepri) [inline pkg/cloud/services/interfaces.go]: Same comment, is this a style preference? From an interface perspective, I kinda preferred the old way, but not an issue

File: controllers/awsmachine_controller.go [hunk 4]
```diff
@@ -466,22 +466,22 @@ func (r *AWSMachineReconciler) getOrCreate(scope *scope.MachineScope, ec2svc ser
...
-					return nil, err
-				}
-				if err := scope.SetSecretCount(chunks); err != nil {
-					return nil, err
-				}
 				if err != nil {
 					r.Recorder.Eventf(scope.AWSMachine, corev1.EventTypeWarning, "FailedCreateAWSSecretsManagerSecrets", err.Error())
 					scope.Error(err, "Failed to create AWS Secret entry", "secretPrefix", prefix)
-					delErr := secretSvc.Delete(scope)
+					delErr := secretSvc.Delete(prefix, chunks)
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: if err := ...; err != nil

**Comment by vincepri** [comment]
In the future, we should separate style changes from the actual bug ones. It's hard to point to the solution.

File: pkg/cloud/scope/machine.go (hunk 1 above)
Comment (randomvariable) [reply pkg/cloud/scope/machine.go]: no, i think i forgot what we decided last time. deletin.

File: pkg/cloud/services/secretsmanager/secret.go (hunk 2 above)
Comment (randomvariable) [reply pkg/cloud/services/secretsmanager/secret.go]: This isn't a style change. It's tied to not actually saving the secret prefix if it failed to create, so it can get retried, but I still want to make one attempt at rolling back the secrets.

That said, I might try to cut this differently.

/hold

**Comment by randomvariable** [comment]
Found a simpler solution, which exposed some test issues too.

File: controllers/awsmachine_controller.go [hunk 5]
```diff
@@ -448,57 +448,52 @@ func (r *AWSMachineReconciler) getOrCreate(scope *scope.MachineScope, ec2svc ser
...
 	}
 
-	if instance == nil {
-		scope.Info("Creating EC2 instance")
-		// Create a new AWSMachine instance if we couldn't find a running instance.
+	if instance != nil {
+		return instance, nil
+	}
+	scope.Info("Creating EC2 instance")
+
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: Add back the comment? // Create a new AWSMachine instance if we couldn't find a running instance.

File: controllers/awsmachine_controller.go [hunk 6]
```diff
@@ -448,57 +448,52 @@ func (r *AWSMachineReconciler) getOrCreate(scope *scope.MachineScope, ec2svc ser
...
-			if err != nil {
-				r.Recorder.Eventf(scope.AWSMachine, corev1.EventTypeWarning, "FailedGenerateAWSSecretsManagerCloudInit", err.Error())
+			if err := scope.SetSecretCount(chunks); err != nil {
 				return nil, err
 			}
-			userData = encryptedCloudInit
 		}
-
-		instance, err = ec2svc.CreateInstance(scope, userData)
+		// Register the Secret ARN immediately to avoid orphaning whatever AWS resources having been created
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]:
```suggestion
		// Register the Secret ARN immediately to avoid orphaning whatever AWS resources have been created
```

File: controllers/awsmachine_controller.go [hunk 7]
```diff
@@ -448,57 +448,52 @@ func (r *AWSMachineReconciler) getOrCreate(scope *scope.MachineScope, ec2svc ser
...
-						scope.Error(delErr, "Failed to clean up AWS Secret entries", "secretPrefix", prefix)
-						return nil, delErr
-					}
-					return nil, err
-				}
-			}
-			// Register the Secret ARN immediately to avoid orphaning AWS resources on delete
-			if err := scope.PatchObject(); err != nil {
+		prefix, chunks, serviceErr := secretSvc.Create(scope, compressedUserData)
+		// Only persist the AWS Secrets Manager entries if at least one
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]:
```suggestion
		// Only persist the AWS Secrets Manager entries if there is at least one
```

File: controllers/awsmachine_controller.go [hunk 8]
```diff
@@ -448,57 +448,52 @@ func (r *AWSMachineReconciler) getOrCreate(scope *scope.MachineScope, ec2svc ser
...
+		encryptedCloudInit, err := secretsmanager.GenerateCloudInitMIMEDocument(scope.GetSecretPrefix(), scope.GetSecretCount(), scope.AWSCluster.Spec.Region)
 		if err != nil {
-			return nil, errors.Wrapf(err, "failed to create AWSMachine instance")
+			r.Recorder.Eventf(scope.AWSMachine, corev1.EventTypeWarning, "FailedGenerateAWSSecretsManagerCloudInit", err.Error())
+			return nil, err
 		}
+		userData = encryptedCloudInit
+	}
+
+	instance, err = ec2svc.CreateInstance(scope, userData)
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: The diff is hard to read, is this inside the `if scope.UseSecretsManager() {` or outside?

Comment (chuckha) [reply controllers/awsmachine_controller.go]: if you check the code out it's waaaay easier to read now. This is outside the block you mention.

**Comment by randomvariable** [comment]
Found a bunch of things running the e2e, so have made some additions:
* Deleting secrets and retry creation if they already exist
* Bumped CAP* dependencies in e2e
* Set K8s version to v1.17.2 to pick up the Ubuntu AMIs with the AWS CLI in them

This PR is canonical now, and will be forward ported to #1562

File: pkg/cloud/services/secretsmanager/secret.go [hunk 9]
```diff
@@ -53,21 +53,39 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
 	})
 
 	// Build the prefix.
-	prefix := path.Join(entryPrefix, string(uuid.NewUUID()))
-
+	prefix := m.GetSecretPrefix()
+	if prefix == "" {
```
Comment (ncdc) [inline pkg/cloud/services/secretsmanager/secret.go]: When would we have an already-set prefix?

File: pkg/cloud/services/secretsmanager/secret.go [hunk 10]
```diff
@@ -53,21 +53,39 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
...
-		_, callErr := s.scope.SecretsManager.CreateSecret(&secretsmanager.CreateSecretInput{
-			Name:         aws.String(name),
-			SecretBinary: chunk,
-			Tags:         converters.MapToSecretsManagerTags(tags),
-		})
-		if callErr != nil {
-			err = kerrors.NewAggregate([]error{callErr})
-			return
+		var done bool
+		for ok := true; ok; ok = !done {
```
Comment (ncdc) [inline pkg/cloud/services/secretsmanager/secret.go]: I think you can do `for !done {}` instead

File: pkg/cloud/services/secretsmanager/secret.go [hunk 11]
```diff
@@ -53,21 +53,39 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
...
+			_, callErr := s.scope.SecretsManager.CreateSecret(&secretsmanager.CreateSecretInput{
+				Name:         aws.String(name),
+				SecretBinary: chunk,
+				Tags:         converters.MapToSecretsManagerTags(tags),
+			})
+			// If the secret already exists, delete and recreate
+			if callErr != nil {
+				err = kerrors.NewAggregate([]error{callErr})
+				return
+			}
```
Comment (ncdc) [inline pkg/cloud/services/secretsmanager/secret.go]: Doesn't this keep you from proceeding to the resource exists check?

File: pkg/cloud/services/secretsmanager/secret.go [hunk 12]
```diff
@@ -53,21 +53,39 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
...
+		var done bool
+		for ok := true; ok; ok = !done {
+			_, callErr := s.scope.SecretsManager.CreateSecret(&secretsmanager.CreateSecretInput{
+				Name:         aws.String(name),
+				SecretBinary: chunk,
+				Tags:         converters.MapToSecretsManagerTags(tags),
+			})
+			// If the secret already exists, delete and recreate
+			if callErr != nil {
+				err = kerrors.NewAggregate([]error{callErr})
```
Comment (ncdc) [inline pkg/cloud/services/secretsmanager/secret.go]: Are you trying to aggregate errors in this closure? If so, make `err` on line 61 `var errs []error` and then `append` to it as needed. Outside of the closure, return `kerrors.NewAggregate(errs)`

File: pkg/cloud/services/secretsmanager/secret.go [hunk 13]
```diff
@@ -53,21 +53,39 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
...
+				return
+			}
+			if awserrors.IsResourceExists(callErr) {
+				_, err := s.scope.SecretsManager.DeleteSecret(&secretsmanager.DeleteSecretInput{
+					SecretId:                   aws.String(name),
+					ForceDeleteWithoutRecovery: aws.Bool(true),
+				})
+				if err != nil {
+					err = kerrors.NewAggregate([]error{callErr})
```
Comment (ncdc) [inline pkg/cloud/services/secretsmanager/secret.go]: Same question re error aggregation

File: pkg/cloud/services/secretsmanager/secret.go [hunk 14]
```diff
@@ -53,21 +53,39 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
...
-			err = kerrors.NewAggregate([]error{callErr})
-			return
+		var done bool
+		for ok := true; ok; ok = !done {
+			_, callErr := s.scope.SecretsManager.CreateSecret(&secretsmanager.CreateSecretInput{
+				Name:         aws.String(name),
+				SecretBinary: chunk,
+				Tags:         converters.MapToSecretsManagerTags(tags),
+			})
+			// If the secret already exists, delete and recreate
```
Comment (ncdc) [inline pkg/cloud/services/secretsmanager/secret.go]: Will AWS let you quickly delete & recreate a secret with the same name?

File: pkg/cloud/services/secretsmanager/secret.go (hunk 9 above)
Comment (randomvariable) [reply pkg/cloud/services/secretsmanager/secret.go]: machine gets patched with the secret prefix when at least one secret chunk has been created, and will be set if it partially succeeded in a previous reconciliation.

File: pkg/cloud/services/secretsmanager/secret.go (hunk 11 above)
Comment (randomvariable) [reply pkg/cloud/services/secretsmanager/secret.go]: Yup. Moved.

File: pkg/cloud/services/secretsmanager/secret.go (hunk 12 above)
Comment (randomvariable) [reply pkg/cloud/services/secretsmanager/secret.go]: amended

File: pkg/cloud/services/secretsmanager/secret.go (hunk 14 above)
Comment (randomvariable) [reply pkg/cloud/services/secretsmanager/secret.go]: Yes. Just ran a continuous creation/deletion loop with the SDK up to 1500.

File: controllers/awsmachine_controller.go [hunk 15]
```diff
@@ -448,57 +448,54 @@ func (r *AWSMachineReconciler) getOrCreate(scope *scope.MachineScope, ec2svc ser
...
-			if err != nil {
-				r.Recorder.Eventf(scope.AWSMachine, corev1.EventTypeWarning, "FailedGenerateAWSSecretsManagerCloudInit", err.Error())
+			if err := scope.SetSecretCount(chunks); err != nil {
 				return nil, err
 			}
-			userData = encryptedCloudInit
 		}
-
-		instance, err = ec2svc.CreateInstance(scope, userData)
+		// Register the Secret ARN immediately to avoid orphaning whatever AWS resources have been created
```
Comment (detiber) [inline controllers/awsmachine_controller.go]: possibly follow up work, but I wonder if it would be worth it to compute the secretprefix and count prior to creating the secrets for the purposes of persisting this info prior to making the call.

We could potentially hit a situation where we haven't created the secrets yet, but recorded the fields, but that would remove any scenario of orphaning.

File: pkg/cloud/services/secretsmanager/secret.go [hunk 16]
```diff
@@ -53,26 +53,44 @@ func (s *Service) Create(m *scope.MachineScope, data []byte) (string, int32, err
...
-			Name:         aws.String(name),
-			SecretBinary: chunk,
-			Tags:         converters.MapToSecretsManagerTags(tags),
-		})
-		if callErr != nil {
-			err = kerrors.NewAggregate([]error{callErr})
-			return
+		var done bool
+		for !done {
+			_, createErr := s.scope.SecretsManager.CreateSecret(&secretsmanager.CreateSecretInput{
```
Comment (detiber) [inline pkg/cloud/services/secretsmanager/secret.go]: On a semi-related note, do we need to worry about eventual consistency on the instance side with retrieving the certs we are creating?

Comment (randomvariable) [reply pkg/cloud/services/secretsmanager/secret.go]: hmm, think i've found something. thanks for that intervention.

/hold

File: controllers/awsmachine_controller.go (hunk 15 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: Possibly. This would be in the case that the controller failed to persist the data in between creating the secret and patching the resource?

**Comment by randomvariable** [comment]
The logic of this was tested in a continuous loop in this little program to test continually rewriting the secret:

``` go
package main

import (
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/secretsmanager"
	"github.com/google/uuid"
	"sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/awserrors"
	"sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/wait"
)

var sess *session.Session
var s *secretsmanager.SecretsManager

const scheduledDeletionMsg = "You can't create this secret because a secret with this name is already scheduled for deletion."

func init() {
	sess, _ = session.NewSession(&aws.Config{
		Region: aws.String("eu-west-1")},
	)
	s = secretsmanager.New(sess)
}

func main() {

	s.DeleteSecret(&secretsmanager.DeleteSecretInput{
		SecretId:                   aws.String("test"),
		ForceDeleteWithoutRecovery: aws.Bool(true),
	})
	time.Sleep(10 * time.Second)
	fmt.Println("initial delete done")
	done := false
	count := 0
	for !done {
		fmt.Printf("loop %d \n", count)
		uiddy, _ := uuid.NewUUID()

		retryFunc := func() (bool, error) { return retryableCreateSecret("test", uiddy.String()) }
		// Default timeout is 5 mins, but if Secrets Manager has got to the state where the timeout is reached,
		// makes sense to slow down machine creation until AWS weather improves.
		if err := wait.WaitForWithRetryable(wait.NewBackoff(), retryFunc, secretsmanager.ErrCodeInvalidRequestException, secretsmanager.ErrCodeResourceNotFoundException); err != nil {
			panic(err)
		}

		v, err := s.GetSecretValue(
			&secretsmanager.GetSecretValueInput{
				SecretId: aws.String("test"),
			},
		)
		if err != nil {
			panic(err)
		}
		if v.SecretString == nil {
			fmt.Println("No value")
		}
		if aws.StringValue(v.SecretString) != uiddy.String() {
			fmt.Printf("wanted %s, got %+v\n", uiddy.String(), v)
		}
		count++
	}
}

// retryableCreateSecret is a function to be passed into a waiter. In a separate function for ease of reading
func retryableCreateSecret(name string, chunk string) (bool, error) {
	_, err := s.CreateSecret(&secretsmanager.CreateSecretInput{
		Name:         aws.String(name),
		SecretString: aws.String(chunk),
	})
	// If the secret already exists, delete it, return request to retry, as deletes are eventually consistent
	if awserrors.IsResourceExists(err) {
		return false, forceDeleteSecretEntry(name)
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// forceDeleteSecretEntry deletes a single secret, ignoring if it is absent
func forceDeleteSecretEntry(name string) error {
	_, err := s.DeleteSecret(&secretsmanager.DeleteSecretInput{
		SecretId:                   aws.String(name),
		ForceDeleteWithoutRecovery: aws.Bool(true),
	})
	if awserrors.IsNotFound(err) {
		return nil
	}
	return err
}
```

Have an e2e test running locally, that has got this far so far:

``` shell
=== RUN   TestE2e
Running Suite: e2e Suite
========================
Random Seed: 1582912791
Will run 17 of 18 specs

Setting up kind cluster
Running in region: eu-west-1
Creating AWS prerequisites
I0228 17:59:52.166849 2844153 bootstrap.go:406] AWS Cloudformation stack "cluster-api-provider-aws-sigs-k8s-io" already exists, updating
creating Kind cluster named "capa-test-7pphdd"
[stdout] Creating cluster "capa-test-7pphdd" ...
[stdout]  • Ensuring node image (kindest/node:v1.15.3) 🖼  ...
[stdout]  ✓ Ensuring node image (kindest/node:v1.15.3) 🖼
[stdout]  • Preparing nodes 📦  ...
[stdout]  ✓ Preparing nodes 📦
[stdout]  • Creating kubeadm config 📜  ...
[stdout]  ✓ Creating kubeadm config 📜
[stdout]  • Starting control-plane 🕹️  ...
[stdout]  ✓ Starting control-plane 🕹️
[stdout]  • Installing CNI 🔌  ...
[stdout]  ✓ Installing CNI 🔌
[stdout]  • Installing StorageClass 💾  ...
[stdout]  ✓ Installing StorageClass 💾
[stdout] Cluster creation complete. You can now use the cluster with:
[stdout]
[stdout] export KUBECONFIG="$(kind get kubeconfig-path --name="capa-test-7pphdd")"
[stdout] kubectl cluster-info
[stdout] [stderr] [stderr] kubeconfig path: "/tmp/kind-home348872153/.kube/kind-config-capa-test-7pphdd". Can use the following to access the cluster:
export KUBECONFIG=/tmp/kind-home348872153/.kube/kind-config-capa-test-7pphdd
loading image "gcr.io/stone-poetry-490/cluster-api-aws-controller-amd64:dev" into Kind node
[stdout] [stderr] Applying cluster-api components
[stdout] namespace/capi-system created
[stdout] customresourcedefinition.apiextensions.k8s.io/clusters.cluster.x-k8s.io created
[stdout] customresourcedefinition.apiextensions.k8s.io/machinedeployments.cluster.x-k8s.io created
[stdout] customresourcedefinition.apiextensions.k8s.io/machines.cluster.x-k8s.io created
[stdout] customresourcedefinition.apiextensions.k8s.io/machinesets.cluster.x-k8s.io created
[stdout] role.rbac.authorization.k8s.io/capi-leader-election-role created
[stdout] clusterrole.rbac.authorization.k8s.io/capi-manager-role created
[stdout] rolebinding.rbac.authorization.k8s.io/capi-leader-election-rolebinding created
[stdout] clusterrolebinding.rbac.authorization.k8s.io/capi-manager-rolebinding created
[stdout] deployment.apps/capi-controller-manager created
[stdout] [stderr] Applying manifests for https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/releases/download/v0.1.5/bootstrap-components.yaml
[stdout] namespace/cabpk-system created
[stdout] customresourcedefinition.apiextensions.k8s.io/kubeadmconfigs.bootstrap.cluster.x-k8s.io created
[stdout] customresourcedefinition.apiextensions.k8s.io/kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io created
[stdout] role.rbac.authorization.k8s.io/cabpk-leader-election-role created
[stdout] clusterrole.rbac.authorization.k8s.io/cabpk-manager-role created
[stdout] clusterrole.rbac.authorization.k8s.io/cabpk-proxy-role created
[stdout] rolebinding.rbac.authorization.k8s.io/cabpk-leader-election-rolebinding created
[stdout] clusterrolebinding.rbac.authorization.k8s.io/cabpk-manager-rolebinding created
[stdout] clusterrolebinding.rbac.authorization.k8s.io/cabpk-proxy-rolebinding created
[stdout] service/cabpk-controller-manager-metrics-service created
[stdout] deployment.apps/cabpk-controller-manager created
[stdout] [stderr] Generating CAPA manifests
Applying manifests for /tmp/capa-e2e-suite563266530/infrastructure-components.yaml
[stdout] namespace/capa-system created
[stdout] customresourcedefinition.apiextensions.k8s.io/awsclusters.infrastructure.cluster.x-k8s.io created
[stdout] customresourcedefinition.apiextensions.k8s.io/awsmachines.infrastructure.cluster.x-k8s.io created
[stdout] customresourcedefinition.apiextensions.k8s.io/awsmachinetemplates.infrastructure.cluster.x-k8s.io created
[stdout] role.rbac.authorization.k8s.io/capa-leader-election-role created
[stdout] clusterrole.rbac.authorization.k8s.io/capa-manager-role created
[stdout] clusterrole.rbac.authorization.k8s.io/capa-proxy-role created
[stdout] rolebinding.rbac.authorization.k8s.io/capa-leader-election-rolebinding created
[stdout] clusterrolebinding.rbac.authorization.k8s.io/capa-manager-rolebinding created
[stdout] clusterrolebinding.rbac.authorization.k8s.io/capa-proxy-rolebinding created
[stdout] secret/capa-manager-bootstrap-credentials created
[stdout] service/capa-controller-manager-metrics-service created
[stdout] deployment.apps/capa-controller-manager created
[stdout] [stderr] Ensuring capi-system/capi-controller-manager is deployed
Ensuring cabpk-system/cabpk-controller-manager is deployed
Ensuring capa-system/capa-controller-manager is deployed
S
------------------------------
functional tests workload cluster lifecycle
  It should be creatable and deletable
  /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:133
creating namespace "test-0z16km"
STEP: Creating a cluster with single control plane
STEP: Creating an AWSCluster
Creating AWSCluster test-0z16km/test-infra-ayir60
STEP: Creating a Cluster
Creating Cluster test-0z16km/test-d8f21m
STEP: Ensuring Cluster Infrastructure Reports as Ready
Ensuring infrastructure is ready for cluster test-0z16km/test-d8f21m
STEP: Creating the initial Control Plane Machine
Creating AWSMachine test-0z16km/test-infra-ea8i4w-0
Creating Init KubeadmConfig test-0z16km/test-boot-m0sm56-0
Creating Machine test-0z16km/test-ss90r8-0
Ensuring Machine test-0z16km/test-ss90r8-0 has bootstrapReady
Ensuring control plane initialized for cluster test-0z16km/test-d8f21m
STEP: Deploying CNI to created Cluster
STEP: Creating the second Control Plane Machine
Creating AWSMachine test-0z16km/test-infra-ea8i4w-1
Creating Join KubeadmConfig test-0z16km/test-boot-m0sm56-1
Creating Machine test-0z16km/test-ss90r8-1
Ensuring Machine test-0z16km/test-ss90r8-1 has bootstrapReady
STEP: Creating the third Control Plane Machine
Creating AWSMachine test-0z16km/test-infra-ea8i4w-2
Creating Join KubeadmConfig test-0z16km/test-boot-m0sm56-2
Creating Machine test-0z16km/test-ss90r8-2
Ensuring Machine test-0z16km/test-ss90r8-2 has bootstrapReady
STEP: Creating the MachineDeployment
Creating MachineDeployment in namespace test-0z16km with name test-capa-mdl49vue
Creating AWSMachineTemplate test-0z16km/test-infra-capa-mtvkfv3s
Creating Join KubeadmConfigTemplate test-0z16km/test-boot-mdcppxuv
Creating MachineDeployment test-0z16km/test-capa-mdl49vue
Ensuring Machine count matched to 2
Verifying MachineDeployment test-0z16km/test-capa-mdl49vue is running..
STEP: Scale the MachineDeployment up
Scaling MachineDeployment from 2 to 5
Ensuring Machine count matched to 5
Verifying MachineDeployment test-0z16km/test-capa-mdl49vue is running..
STEP: Scale the MachineDeployment down
Scaling MachineDeployment from 5 to 0
Ensuring Machine count matched to 0
Verifying MachineDeployment test-0z16km/test-capa-mdl49vue is running..
STEP: Scale the MachineDeployment up again
Scaling MachineDeployment from 0 to 2
Ensuring Machine count matched to 2
Verifying MachineDeployment test-0z16km/test-capa-mdl49vue is running..
STEP: Deleting the Cluster
Deleting Cluster test-0z16km/test-d8f21m

• [SLOW TEST:2118.934 seconds]
functional tests
/home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:105
  workload cluster lifecycle
  /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:132
    It should be creatable and deletable
    /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:133
------------------------------
functional tests Provisioning LoadBalancer dynamically and deleting on cluster deletion
  It should create and delete Load Balancer
  /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:168
creating namespace "test-qf3qar"
STEP: Creating a cluster with single control plane
STEP: Creating an AWSCluster
Creating AWSCluster test-qf3qar/test-infra-jsj92c
STEP: Creating a Cluster
Creating Cluster test-qf3qar/test-n7wmw1
STEP: Ensuring Cluster Infrastructure Reports as Ready
Ensuring infrastructure is ready for cluster test-qf3qar/test-n7wmw1
STEP: Creating the initial Control Plane Machine
Creating AWSMachine test-qf3qar/test-infra-oktt7a-0
Creating Init KubeadmConfig test-qf3qar/test-boot-jjpg82-0
Creating Machine test-qf3qar/test-c3aacx-0
Ensuring Machine test-qf3qar/test-c3aacx-0 has bootstrapReady
Ensuring control plane initialized for cluster test-qf3qar/test-n7wmw1
STEP: Deploying CNI to created Cluster
STEP: Creating the MachineDeployment
Creating MachineDeployment in namespace test-qf3qar with name test-capa-mdt6q0xg
Creating AWSMachineTemplate test-qf3qar/test-infra-capa-mt178ofb
Creating Join KubeadmConfigTemplate test-qf3qar/test-boot-md46xd9u
Creating MachineDeployment test-qf3qar/test-capa-mdt6q0xg
Ensuring Machine count matched to 2
Verifying MachineDeployment test-qf3qar/test-capa-mdt6q0xg is running..
STEP: Creating the LB service
Creating service of type Load Balancer with name: test-svc-8skjg8 under namespace: default
Created Load Balancer service and ELB name is: acf9cb709c7684b07bbd0bb49669f087
Verifying ELB with name acf9cb709c7684b07bbd0bb49669f087 present
ELB with name acf9cb709c7684b07bbd0bb49669f087 exists
STEP: Deleting the Cluster
Deleting Cluster test-qf3qar/test-n7wmw1
STEP: Verifying whether provisioned LB deleted
Verifying ELB with name acf9cb709c7684b07bbd0bb49669f087 present
ELB with name acf9cb709c7684b07bbd0bb49669f087 doesn't exists

• [SLOW TEST:932.920 seconds]
functional tests
/home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:105
  Provisioning LoadBalancer dynamically and deleting on cluster deletion
  /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:166
    It should create and delete Load Balancer
    /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:168
------------------------------
functional tests Provisioning volumes dynamically and retain on cluster deletion
  It should create volumes and volumes should not be deleted along with cluster infra
  /home/naadir/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:205
creating namespace "test-qfma5m"
STEP: Creating a cluster with single control plane
STEP: Creating an AWSCluster
Creating AWSCluster test-qfma5m/test-infra-wi6s9i
STEP: Creating a Cluster
Creating Cluster test-qfma5m/test-viqu1y
STEP: Ensuring Cluster Infrastructure Reports as Ready
Ensuring infrastructure is ready for cluster test-qfma5m/test-viqu1y
STEP: Creating the initial Control Plane Machine
Creating AWSMachine test-qfma5m/test-infra-m9ojku-0
Creating Init KubeadmConfig test-qfma5m/test-boot-9190s0-0
Creating Machine test-qfma5m/test-btkoh5-0
Ensuring Machine test-qfma5m/test-btkoh5-0 has bootstrapReady
```

File: controllers/awsmachine_controller.go (hunk 15 above)
Comment (detiber) [reply controllers/awsmachine_controller.go]: Correct, but it's no worse than it would be for other resources that can't be tagged on creation :)

File: go.mod [hunk 17]
```diff
@@ -25,3 +25,5 @@ require (
 	sigs.k8s.io/controller-runtime v0.3.0
 	sigs.k8s.io/yaml v1.1.0
 )
+
+replace k8s.io/client-go => k8s.io/client-go v0.0.0-20190918200256-06eb1244587a
```
Comment (detiber) [inline go.mod]: :grimacing: why the replace here?

Comment (randomvariable) [reply go.mod]: keeps randomly changing to an incompatible version. doing that seems to hold it constant.
