### PR TITLE
🐛 Fix nil pointer panic in ROSARoleConfig when AWS client initialization fails

### LINKED ISSUE #5860: ROSARoleConfig Controller Crashes with Nil Pointer Dereference
/kind bug
 ROSARoleConfig controller panic: nil pointer dereference in reconcileAccountRoles()

**Environment:**
 Image: quay.io:443/acm-d/cluster-api-provider-aws-rhel9@sha256:f91ab377cef69fd7df28cd1afc8af87dcca62552fb2192e77adcdfb13b482754
  - Component: Red Hat MCE 2.11.0 downstream build

The ROSARoleConfig controller intermittently crashes with a nil pointer dereference panic during the first reconciliation of new ROSARoleConfig resources. The crash occurs in the reconcileAccountRoles() function when attempting to access r.Runtime.AWSClient.

  Impact:
  - Some ROSARoleConfig resources successfully create AWS IAM roles (14s-2m37s)
  - Others fail and remain stuck for 15+ minutes before timeout
  - The crash is non-deterministic, making ROSA HCP cluster provisioning unreliable

```
Full Panic Stack Trace:
E0205 09:57:27.912082       1 signal_unix.go:925] "Observed a panic" 
  controller="rosaroleconfig" 
  controllerGroup="infrastructure.cluster.x-k8s.io" 
  controllerKind="ROSARoleConfig" 
  ROSARoleConfig="ns-rosa-hcp/abc-ui-rosa-hcp-test-roles" 
  namespace="ns-rosa-hcp" 
  name="abc-ui-rosa-hcp-test-roles" 
  reconcileID="3872e30c-f6c7-404d-89f0-4d9ad903821d" 
  panic="runtime error: invalid memory address or nil pointer dereference" 
  panicGoValue="\"invalid memory address or nil pointer dereference\"" 
  stacktrace=<
  	panic({0x5357620?, 0x8a61240?})
  		/usr/lib/golang/src/runtime/panic.go:792 +0x132
```

```
Controller Error:
  E0205 09:57:27.912147       1 controller.go:347] "Reconciler error"
  err="panic: runtime error: invalid memory address or nil pointer dereference [recovered]"
  controller="rosaroleconfig"
  controllerGroup="infrastructure.cluster.x-k8s.io"
  controllerKind="ROSARoleConfig"
  ROSARoleConfig="ns-rosa-hcp/abc-ui-rosa-hcp-test-roles"
  namespace="ns-rosa-hcp"
  name="abc-ui-rosa-hcp-test-roles"
  reconcileID="3872e30c-f6c7-404d-89f0-4d9ad903821d"
```

Additional Context
The crash is recoverable at times:

Successful ROSARoleConfigs (recovered from crash or avoided it):
  - test-rosa-hcp-roles: 14 seconds
  - new-rosa-hcp-test-roles: 2 minutes 37 seconds

Failed ROSARoleConfigs (stuck in crash loop):
  - tst-rosa-hcp-roles: 15+ minutes before manual deletion
  - abc-ui-rosa-hcp-test-roles: Crashed on first reconcile

### PR DESCRIPTION
**Pull request by andclt**
**What type of PR is this?**

  /kind bug

  **What this PR does / why we need it**:

  Fixes a nil pointer dereference bug in `ROSARoleConfigReconciler.setUpRuntime()` that occurs when AWS client initialization fails (e.g., expired credentials). This addresses the
crash reported in #5860 where the controller would panic when accessing `r.Runtime.AWSClient`.

  **Root cause:** The original code created `r.Runtime` before all components were successfully initialized. When AWS client creation failed, `r.Runtime` existed but `r.Runtime.AWSClient` was nil (partial initialization). On retry, the guard clause `if r.Runtime != nil` returned early, preventing re-initialization. Later code accessing `r.Runtime.AWSClient` would panic.

  **Fix:**
  1. **Atomic assignment pattern**: Build `Runtime` in a local variable; only assign to `r.Runtime` after ALL components (`OCMClient`, `AWSClient`, `Creator`) succeed. On error, the local variable is discarded
  and `r.Runtime` remains nil, allowing retry on next reconciliation.
  2. **Session configuration**: Added `.ExternalConfig(&session)` to `aws.NewClient()` to properly configure AWS region and credentials from scope, matching the pattern used in `rosanetwork_controller.go`.

  **Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
  Fixes #5860

  **Special notes for your reviewer**:

  This fix follows the same atomic assignment pattern already used in `exp/controllers/rosanetwork_controller.go` (lines 90-101) for consistency across ROSA controllers.

  **Testing performed:**
  - **Integration test** (`TestROSARoleConfigSetUpRuntimeWithExpiredAWSCredentials`): Validates atomic assignment prevents partial initialization by simulating credential failures
  - **Manual validation**: Built and deployed patched controller to kind cluster (v1.35.0) with expired AWS STS credentials:
    - ✅ No panics with expired credentials (previously panicked)
    - ✅ Graceful error handling with clear error messages
    - ✅ Automatic recovery after credential refresh (no pod restart required)
    - ✅ Controller remained healthy and continued reconciling other resources

  **Checklist**:

  - [ ] squashed commits
  - [ ] includes documentation
  - [ ] includes AI generated content
  - [x] includes emoji in title
  - [x] adds unit tests
  - [ ] adds or updates e2e tests

  **Release note**:

  ```release-note
   Fixed nil pointer panic in ROSARoleConfig controller when AWS client initialization failed due to expired credentials or missing region configuration.
```

### CODE REVIEW

File: exp/controllers/rosaroleconfig_controller.go
Comment (serngawy) [inline exp/controllers/rosaroleconfig_controller.go:451]: I believe the issue mentioned that the r.Runtime.AWSClient was nil value [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/controllers/rosaroleconfig_controller.go#L305) so we should check here for AWSClient 
```suggestion
	if r.Runtime != nil && r.Runtime.AWSClient != nil {
```

File: exp/controllers/rosaroleconfig_controller.go [hunk 1]
```diff
@@ -463,20 +463,28 @@ func (r *ROSARoleConfigReconciler) setUpRuntime(ctx context.Context, scope *scop
...
-	r.Runtime.Reporter = reporter.CreateReporter() // &rosa.Reporter{}
-	r.Runtime.Logger = rosalogging.NewLogger()
-
-	r.Runtime.AWSClient, err = aws.NewClient().Logger(r.Runtime.Logger).Build()
+	runtime := rosacli.NewRuntime()
+	runtime.OCMClient = ocmClient
+	runtime.Reporter = reporter.CreateReporter() // &rosa.Reporter{}
+	runtime.Logger = rosalogging.NewLogger()
+
+	session := scope.Session()
```
Comment (serngawy) [inline exp/controllers/rosaroleconfig_controller.go:471]: Not sure, how we never hit this before, it should uses the roleConfigScop.session.  When the controller is initialized it sets the STS and session [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/controllers/rosaroleconfig_controller.go#L72) . To clarify the case, did you had a valid aws credential->session and while using CAPA does the aws credential get unvalid/expired ?

File: exp/controllers/rosaroleconfig_controller.go
Comment (andclt) [reply exp/controllers/rosaroleconfig_controller.go:451]: With atomic assignment, if `r.Runtime != nil` then `r.Runtime.AWSClient` is guaranteed to be non-nil since we only assign after all components succeed. So this the defensive check would be redundant here.

File: exp/controllers/rosaroleconfig_controller.go (hunk 1 above)
Comment (andclt) [reply exp/controllers/rosaroleconfig_controller.go:471]: > To clarify the case, did you had a valid aws credential->session and while using CAPA does the aws credential get unvalid/expired ?

I had valid AWS credentials initially, started the ROSA cluster creation, and the credentials expired during reconciliation because I was using temporary credentials that expire after 1hr. On retry, the original code hit the bug: `r.Runtime` was created but `AWSClient` initialization failed leaving it partially initialized.

**Review by serngawy — APPROVED** [review]

**Review by damdo — COMMENTED** [review]
/approve
