### PR TITLE
🐛Add cert-manager to output of generate-examples

### LINKED ISSUE #1233: Unable to generate examples with cert-manager definitions
/kind bug

**What steps did you take and what happened:**
When I run the following command:
`CAPI_BRANCH=master SSH_KEY_NAME=my-ssh-key CLUSTER_NAME=oct21-cluster make generate-examples`
I get the following output:
```
rm -rf examples/_out/
rm -f examples/provider-components/provider-components-*.yaml
go build -o bin/clusterawsadm ./cmd/clusterawsadm
./examples/generate.sh
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/cluster.yaml
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/controlplane.yaml
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/machinedeployment.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  502k  100  502k    0     0  3327k      0 --:--:-- --:--:-- --:--:-- 3328k
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/provider-components/provider-components-cluster-api.yaml from cluster-api - master
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   616    0   616    0     0   2786      0 --:--:-- --:--:-- --:--:--  2774
100 96201  100 96201    0     0   119k      0 --:--:-- --:--:-- --:--:--  119k
Downloaded /Users/wfernandes/workspace/cluster-api-provider-aws/examples/provider-components/provider-components-kubeadm.yaml from cluster-api-bootstrap-provider-kubeadm stable branch - v0.1.2
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/provider-components/provider-components-aws.yaml
Error: accumulating resources: merging resources from 'provider-components-cluster-api.yaml': may not add resource with an already registered id: apiextensions.k8s.io_v1beta1_CustomResourceDefinition|~X|kubeadmconfigs.bootstrap.cluster.x-k8s.io
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/provider-components.yaml
WARNING: /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/provider-components.yaml includes AWS credentials
```

**What did you expect to happen:**
I was expecting the `examples/_out/provider-components.yaml` to include all the cert-manager CRD definitions, etc...

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: master (172c72508a4eef74d937845329aa9e0d652dcd12)

/cc @tahsinrahman

### PR DESCRIPTION
**Pull request by wfernandes**
cert-manager components is required by the capa-controller-manager. The
user should create cert-manager components before creating capa
control-plane.

Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

**What this PR does / why we need it**:
This PR creates `examples/_out/cert-manager.yaml` when running `make generate-examples`.
This PR improves the user experience for those using the `make generate-examples` command to understand how to deploy capa control plane.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1233

### CODE REVIEW

**Comment by detiber** [comment]
@wfernandes I believe the current idea is to make having cert-manager deployed a pre-requisite to deploying Cluster API for v1alpha3, with the potential for `clusterctl` to handle this dependency.

The main reason for this is that cert-manager needs to be both deployed and running prior to deploying any components that need webhook support.

**Comment by wfernandes** [comment]
@detiber That makes sense! I was hoping to provide a way to let those using the `make generate-examples` command aware that cert-manager is a pre-requisite and give them a way to get the `cert-manager.yaml`.
I could either change the last message from 

`NOTE: Ensure that the cert-manager components are running before creating the provider-components, cluster and control-plane.` 
to be something more descriptive like 
`NOTE: cert-manager is a pre-requisite that is required to be Running on the management cluster.`

Again, I just wanted to improve the user experience instead of having users inspect the Makefile to understand what needs to be installed.

I thought providing the `cert-manager.yaml` in the `examples/_out` directory since that directory is generated.

File: examples/generate.sh [hunk 1]
```diff
@@ -103,9 +104,12 @@ echo "Generated ${MACHINEDEPLOYMENT_GENERATED_FILE}"
 CAPI_BRANCH=${CAPI_BRANCH:-"master"}
 if [[ ${CAPI_BRANCH} == "stable" ]]; then
   # TODO(vincepri): Fix the version once the first v0.3.x is released.
-  curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.2.5/cluster-api-components.yaml > "${COMPONENTS_CLUSTER_API_GENERATED_FILE}"
+  curl -sL https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.2.5/cluster-api-components.yaml > "${COMPONENTS_CLUSTER_API_GENERATED_FILE}"
   echo "Downloaded ${COMPONENTS_CLUSTER_API_GENERATED_FILE} from cluster-api stable branch - v0.2.5"
 else
+  # This version of cert-manager is pulled from Makefile - create-cluster-management
+  curl -sL https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml > "${CERTMANAGER_COMPONENTS_GENERATED_FILE}"
```
Comment (vincepri) [inline examples/generate.sh]: The file should be downloaded all the time, i.e. outside the if/else conditions

File: examples/generate.sh [hunk 2]
```diff
@@ -121,3 +125,5 @@ echo "WARNING: ${PROVIDER_COMPONENTS_GENERATED_FILE} includes AWS credentials"
 
 # Patch kubernetes version
 sed -i'' -e 's|kubernetesVersion: .*|kubernetesVersion: '$KUBERNETES_VERSION'|' examples/_out/controlplane.yaml
+
+echo "NOTE: Ensure that the cert-manager components are running before creating the provider-components, cluster and control-plane."
```
Comment (vincepri) [inline examples/generate.sh]: This should either link the quick start instructions or some other pre-req document, wdyt?

Comment (wfernandes) [reply examples/generate.sh]: That's a great idea. This issue is open currently (https://github.com/kubernetes-sigs/cluster-api/issues/1561). Once this is done I can update this script with the relevant link. But I don't think this should be a blocker.
