### PR TITLE
🐛Fix creation of Internet-facing ELB

### LINKED ISSUE #1423: Error creating internet-facing ELB, missing subnets
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

`make create-cluster`

Errors:

`I1215 03:50:34.802856       1 awsmachine_controller.go:270] controllers/AWSMachine "msg"="Reconciling AWSMachine" "awsCluster"="capa-dev" "awsMachine"="capa-dev-controlplane-2" "cluster"="capa-dev" "machine"="capa-dev-controlplane-2" "namespace"="default"
I1215 03:50:34.805080       1 awsmachine_controller.go:284] controllers/AWSMachine "msg"="Cluster infrastructure is not ready yet" "awsCluster"="capa-dev" "awsMachine"="capa-dev-controlplane-2" "cluster"="capa-dev" "machine"="capa-dev-controlplane-2" "namespace"="default"
E1215 03:50:36.979964       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile load balancers for AWSCluster default/capa-dev: failed to create classic load balancer: \u0026{capa-dev-apiserver  Internet-facing [] [] [sg-0f0085bfa36e4ac74] [0xc0007b19b0] 0xc0007b19e0 {10m0s} map[sigs.k8s.io/cluster-api-provider-aws/cluster/capa-dev:owned sigs.k8s.io/cluster-api-provider-aws/role:apiserver]}: ValidationError: Either AvailabilityZones or SubnetIds must be specified\n\tstatus code: 400, request id: 0912203e-a466-486e-916a-1ba3978a46f1"  "controller"="awscluster" "request"={"Namespace":"default","Name":"capa-dev"}
`

**What did you expect to happen:**
ELB to be created.

**Anything else you would like to add:**
Bug may have been introduced in PR #1420 

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): v1.16.3
- OS (e.g. from `/etc/os-release`): N/A

### PR DESCRIPTION
**Pull request by aaroniscode**
**What this PR does / why we need it**:
Fix the ELB subnets filter

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1423

### CODE REVIEW

File: pkg/cloud/services/elb/loadbalancer.go [hunk 1]
```diff
@@ -267,9 +267,12 @@ func (s *Service) getAPIServerClassicELBSpec() (*infrav1.ClassicELB, error) {
 	})
 
 	// The load balancer APIs require us to only attach one subnet for each AZ.
-	subnets := s.scope.Subnets().FilterPrivate()
```
Comment (vincepri) [inline pkg/cloud/services/elb/loadbalancer.go]: Instead of removing this, you can change line 272 to `subnets = s.scope.Subnets().FilterPublic()`.

Thanks for catching this!

Comment (aaroniscode) [reply pkg/cloud/services/elb/loadbalancer.go]: Thanks for the review @vincepri .  As soon as I submitted the PR I thought you might prefer NOT having the `else` statement.   I've updated and force pushed.

**Comment by aaroniscode** [comment]
@vincepri also had a question ... should the PR have the 🐛identifier?  I think that's used for release notes and this bug wasn't in any released version, just in master. Still learning how this all works. Thanks.
