### PR TITLE
Fix EKSControlPlaneReconciliationFailed when OIDC already exists

### LINKED ISSUE #3972: Clusterctl move stucks after migration at OIDC provider
/kind bug

**What steps did you take and what happened:**

- create two management cluster with CAPI/CAPA
- create a workload cluster with `AWSManagedControlPlane (v1beta2)`
- use clusterctl move to migrate workload cluster

When using `clusterctl move` on clusters with enabled `associateOIDCProvider: true` the OIDC provider cannot be adopted anymore. 
I had to delete the identity provider manually and let the capa controller re-create it to fix it.

```
I0110 16:28:19.289830       1 logger.go:68] "Reconciling EKS OIDC Provider" cluster-name=0xc0007c3300
E0110 16:28:20.396962       1 controller.go:326] "Reconciler error" err=<
	failed to reconcile control plane for AWSManagedControlPlane default/t00-euc1-eks-rh-cp: failed reconciling OIDC provider for cluster: failed to create OIDC provider: error creating provider: EntityAlreadyExists: Provider with url https://oidc.eks.eu-central-1.amazonaws.com/id/C5E4BEAA7CA5AF038A8CA37B42560F80 already exists.
		status code: 409, request id: 937d1a9b-a8a7-47b3-a006-fff3f010e550
 > controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" aWSManagedControlPlane="default/t00-euc1-eks-rh-cp" namespace="default" name="t00-euc1-eks-rh-cp" reconcileID=afd5887d-2714-4f71-a292-86e4da782ceb
```

**What did you expect to happen:**
No error after migrating clusters, adopting the previous created OIDC without human intervention

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`): not relevant

### PR DESCRIPTION
**Pull request by iamjanr**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Avoid "failed to create OIDC provider: error creating provider: EntityAlreadyExists" and "EKSControlPlaneReconciliationFailed" errors when provider.Url do not contain https

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3972 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by iamjanr** [comment]
Hey how's it going?, if someone could take a look at the pull request I would appreciate it, thank you very much

File: pkg/cloud/services/eks/iam/iam.go [hunk 1]
```diff
@@ -461,7 +462,7 @@ func (s *IAMService) FindAndVerifyOIDCProvider(cluster *eks.Cluster) (string, er
 			return "", errors.Wrap(err, "error getting provider")
 		}
 		// URL should always contain `https`.
-		if *provider.Url != issuerURL.String() {
+		if *provider.Url != issuerURL.String() && *provider.Url != strings.Replace(issuerURL.String(), "https://", "", 1) {
```
Comment (Ankitasw) [inline pkg/cloud/services/eks/iam/iam.go:465]: I think this check could be enhanced, may be like check if the err is OIDCAlreadyExist, then break, else have this https check. wdyt?

Comment (iamjanr) [reply pkg/cloud/services/eks/iam/iam.go:465]: Hi @Ankitasw, first of all thanks for reviewing the PR, it seems like a good idea, I'll get to work :)

**Comment by Ankitasw** [comment]
Hey @iamjanr any progress on this PR?

File: pkg/cloud/services/eks/iam/iam.go (hunk 1 above)
Comment (iamjanr) [reply pkg/cloud/services/eks/iam/iam.go:465]: Hi @Ankitasw
I'm sorry, it has been impossible for me to dedicate time to it, this week it will be closed

Comment (iamjanr) [reply pkg/cloud/services/eks/iam/iam.go:465]: Hi @Ankitasw,
I have been reviewing the issue, function FindAndVerifyOIDCProvider never return "https" in the identity provider response so never complain the condition and always returns "" and because of that, the function CreateOIDCProvider always return the error "EntityAlreadyExists" if OIDC already exists; if you agree we could enhance the check just using this code (if we are sure https is always present) like this:
if *provider.Url != strings.Replace(issuerURL.String(), "https://", "", 1) {
            continue
        }

**Comment by iamjanr** [comment]
Hi! any update?

**Comment by iamjanr** [comment]
@richardcase is ok to merge?

File: pkg/cloud/services/eks/iam/iam.go (hunk 1 above)
Comment (Skarlso) [reply pkg/cloud/services/eks/iam/iam.go:465]: There is a requirement in the docs stating:
> The URL must begin with https://.

So I think that's a safe bet.
