### PR TITLE
🏃Fix log names are too verbose

### LINKED ISSUE #1121: Controller log names are too verbose
We have log "names" (`r.Log.WithName()`) that are too verbose. Here is an example for the AWSCluster controller, and we have a similar issue with AWSMachine.

```
controllers/AWSCluster/awscluster-controller/namespace=default/awsCluster=capi-quickstart/infrastructure.cluster.x-k8s.io/v1alpha2/cluster=capi-quickstart
```

If we break that apart:

1. `controllers/AWSCluster` comes from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/main.go#L142
1. `awscluster-controller` is a repeat of the previous name, and it comes from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L57
1. `namespace=default` is ok (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L58)
1. `awsCluster=capi-quickstart` is ok (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L59)
1. `infrastructure.cluster.x-k8s.io/v1alpha2` we should either remove or include what this is (`apiVersion=infrastructure.cluster.x-k8s.io/v1alpha2`) (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L71)
1. `cluster=capi-quickstart` is ok (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L83)

One other thing that's a little confusing is that the "name separator" is `/`, and some of our names have slashes in them. So it makes it hard to know where the separation of each name segment is.

/kind cleanup
/help
/good-first-issue
/priority important-longterm
/milestone Next

### PR DESCRIPTION
**Pull request by tahsinrahman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1121

### CODE REVIEW

File: controllers/awscluster_controller.go [hunk 1]
```diff
@@ -80,7 +76,7 @@ func (r *AWSClusterReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reter
 		return reconcile.Result{}, nil
 	}
 
-	log = log.WithName(fmt.Sprintf("cluster=%s", cluster.Name))
+	log = log.WithValues("cluster", fmt.Sprintf("%s/%s", cluster.Namespace, cluster.Name))
```
Comment (detiber) [inline controllers/awscluster_controller.go]: We can likely leave off namespace here, since the namespace will be the same as the related `AWSCluster`.

File: controllers/awsmachine_controller.go [hunk 2]
```diff
@@ -85,7 +80,7 @@ func (r *AWSMachineReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reter
 		return reconcile.Result{}, nil
 	}
 
-	logger = logger.WithName(fmt.Sprintf("machine=%s", machine.Name))
+	logger = logger.WithValues("machine", fmt.Sprintf("%s/%s", machine.Namespace, machine.Name))
```
Comment (detiber) [inline controllers/awsmachine_controller.go]: From here and blow we can likely leave off the namespace, since they will be the same as the `AWSMachine` above.

**Comment by detiber** [comment]
lgtm, but in need of a rebase.

File: controllers/awscluster_controller.go [hunk 3]
```diff
@@ -80,7 +74,7 @@ func (r *AWSClusterReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reter
 		return reconcile.Result{}, nil
 	}
 
-	log = log.WithName(fmt.Sprintf("cluster=%s", cluster.Name))
+	log = log.WithValues("cluster", cluster.Name)
```
Comment (vincepri) [inline controllers/awscluster_controller.go]: Do we even need this given that we're working on the awsCluster field?

File: controllers/awsmachine_controller.go [hunk 4]
```diff
@@ -85,7 +80,7 @@ func (r *AWSMachineReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reter
 		return reconcile.Result{}, nil
 	}
 
-	logger = logger.WithName(fmt.Sprintf("machine=%s", machine.Name))
+	logger = logger.WithValues("machine", machine.Name)
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: Same here, what if we remove this as well?

File: controllers/awscluster_controller.go (hunk 3 above)
Comment (detiber) [reply controllers/awscluster_controller.go]: This gives context back to the related Cluster. I'm not sure we should remove it.

File: controllers/awsmachine_controller.go (hunk 4 above)
Comment (detiber) [reply controllers/awsmachine_controller.go]: I think we lose context here if we don't provide the associated Machine.

File: controllers/awscluster_controller.go [hunk 5]
```diff
@@ -53,9 +48,7 @@ type AWSClusterReconciler struct {
 
 func (r *AWSClusterReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr error) {
 	ctx := context.TODO()
-	log := r.Log.WithName(controllerName).
-		WithName(fmt.Sprintf("namespace=%s", req.Namespace)).
-		WithName(fmt.Sprintf("awsCluster=%s", req.Name))
+	log := r.Log.WithValues("namespace", req.Namespace).WithValues("awsCluster", req.Name)
```
Comment (ncdc) [inline controllers/awscluster_controller.go]:
```suggestion
	log := r.Log.WithValues("namespace", req.Namespace, "awsCluster", req.Name)
```

File: controllers/awscluster_controller.go (hunk 3 above)
Comment (ncdc) [reply controllers/awscluster_controller.go]: +1 for keeping

File: controllers/awsmachine_controller.go [hunk 6]
```diff
@@ -58,10 +58,7 @@ type AWSMachineReconciler struct {
 
 func (r *AWSMachineReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr error) {
 	ctx := context.TODO()
-	logger := r.Log.
-		WithName(controllerName).
-		WithName(fmt.Sprintf("namespace=%s", req.Namespace)).
-		WithName(fmt.Sprintf("awsMachine=%s", req.Name))
+	logger := r.Log.WithValues("namespace", req.Namespace).WithValues("awsMachine", req.Name)
```
Comment (ncdc) [inline controllers/awsmachine_controller.go]:
```suggestion
	logger := r.Log.WithValues("namespace", req.Namespace, "awsMachine", req.Name)
```

File: controllers/awsmachine_controller.go (hunk 4 above)
Comment (ncdc) [reply controllers/awsmachine_controller.go]: +1 for keeping
