### PR TITLE
🐛 ROSA: Fix issue-4936 delete rosaMachinePool and rosaControlPlane

### LINKED ISSUE #4936: ROSA: RosaMachinePool and MachinePool CRs stuck at de-provision ROSA-HCP
/kind bug

**What steps did you take and what happened:**
We using gitOps workflow to provision ROSA-HCP. The required CRs; RosaControlPlane, RosaCluster, RosaMachinePool, Cluster and MachinePool are stored in a git repo and ArgoCDs is used to Sync the CRs to the installer cluster.  
At the time to de-provision the ROSA-HCP;
1- Delete all the required CRs from the git repo 
2- Let ArgoCD sync the git repo status and delete all the required CRs from the installer cluster. 
3- The ROSA-HCP start the uninstall process
4- The RosaControlPlace and RosaCluster CRs are deleted however RosaMachinePool, MachinePool and Cluster CR stuck never get deleted.
5- Checking the aws console and the redhat console all the ROSA-HCP and AWS resources are destroyed. 
6- After manually cleaning the finalizers from RosamachinePool and MachinePool CRs the Cluster CR is deleted.

**What did you expect to happen:**
We expect at the cluster uninstall all the CRs get deleted.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Checking the logs for capa-controller-manager deployment during the uninstall process, the logs below is shown

```
E0415 22:22:23.974724       1 controller.go:329] "Reconciler error" err="Node pools can only be deleted on clusters in 'ready' state, cluster requested is in 'uninstalling' state." controller="rosamachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ROSAMachinePool" ROSAMachinePool="ns-rosa-hcp/workers-ex" namespace="ns-rosa-hcp" name="workers-ex" reconcileID="4a8dfbec-4fb6-48ff-aa07-bf75ba7cd31b"
```

After the aws and rosa-hcp resources destroyed the logs below is shown

```
I0415 22:42:21.241631       1 rosamachinepool_controller.go:142] "Failed to retrieve ControlPlane from MachinePool" controller="rosamachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ROSAMachinePool" ROSAMachinePool="ns-rosa-hcp/workers-ex" namespace="ns-rosa-hcp" name="workers-ex" reconcileID="78e9b21b-937c-41fe-9550-34b974be85dc" MachinePool="ns-rosa-hcp/workers-ex" cluster="ns-rosa-hcp/rosa-hcp-2"
```

The Logs for  capi-controller-manager deployment during the uninstall process, the logs below is shown

```
I0415 22:49:51.074671       1 cluster_controller.go:269] "Cluster still has descendants - need to requeue" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="ns-rosa-hcp/rosa-hcp-2" namespace="ns-rosa-hcp" name="rosa-hcp-2" reconcileID="6d892381-4d67-402d-97da-c4a2f76c7a57" descendants="Machine pools: workers-ex" indirect descendants count=0
E0415 22:49:54.492574       1 controller.go:329] "Reconciler error" err="failed to create cluster accessor: error fetching REST client config for remote cluster \"ns-rosa-hcp/rosa-hcp-2\": failed to retrieve kubeconfig secret for Cluster ns-rosa-hcp/rosa-hcp-2: Secret \"rosa-hcp-2-kubeconfig\" not found" controller="machinepool" controllerGroup="cluster.x-k8s.io" controllerKind="MachinePool" MachinePool="ns-rosa-hcp/workers-ex" namespace="ns-rosa-hcp" name="workers-ex" reconcileID="c2c91b09-2e38-4dfd-9a2f-c0478de02ac1"
```

[capi-logs.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/15026459/capi-logs.txt)
[capa-logs.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/15026460/capa-logs.txt)
[rosa-hcp-2.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/15026519/rosa-hcp-2.txt)

**Environment:**

- Cluster-api-provider-aws version:  v2.4.2
- Kubernetes version: (use `kubectl version`):  v1.27.3

- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by serngawy**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix delete rosaControlPlane and rosaMachinePool

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4936

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
None
```

### CODE REVIEW

File: exp/controllers/rosamachinepool_controller.go [hunk 1]
```diff
@@ -123,7 +123,21 @@ func (r *ROSAMachinePoolReconciler) Reconcile(ctx context.Context, req ctrl.Requ
 	controlPlane := &rosacontrolplanev1.ROSAControlPlane{}
 	if err := r.Client.Get(ctx, controlPlaneKey, controlPlane); err != nil {
 		log.Info("Failed to retrieve ControlPlane from MachinePool")
-		return reconcile.Result{}, nil
+
+		if apierrors.IsNotFound(err) && rosaMachinePool.DeletionTimestamp != nil && !rosaMachinePool.DeletionTimestamp.IsZero() {
```
Comment (muraee) [inline exp/controllers/rosamachinepool_controller.go:127]:
```suggestion
		if apierrors.IsNotFound(err) && !rosaMachinePool.DeletionTimestamp.IsZero() {
```
no need to check for nil, `isZero()` does that.

File: exp/controllers/rosamachinepool_controller.go [hunk 2]
```diff
@@ -123,7 +123,21 @@ func (r *ROSAMachinePoolReconciler) Reconcile(ctx context.Context, req ctrl.Requ
...
+			// Remove the finalizer as the controlPlan is deleted and deleting rosaMachinePool.
+			patcher, err := scope.NewRosaMachinePoolPatchHelper(rosaMachinePool, r.Client)
+			if err != nil {
+				return reconcile.Result{}, err
+			}
+			if controllerutil.RemoveFinalizer(rosaMachinePool, expinfrav1.RosaMachinePoolFinalizer) {
+				if err = patcher.Patch(context.TODO(), rosaMachinePool); err != nil {
+					return reconcile.Result{}, err
```
Comment (muraee) [inline exp/controllers/rosamachinepool_controller.go:135]:
```suggestion
					return ctrl.Result{}, err
```

File: exp/controllers/rosamachinepool_controller.go [hunk 3]
```diff
@@ -123,7 +123,21 @@ func (r *ROSAMachinePoolReconciler) Reconcile(ctx context.Context, req ctrl.Requ
...
+				}
+			}
+			return ctrl.Result{}, nil
+		}
+		return reconcile.Result{}, err
```
Comment (muraee) [inline exp/controllers/rosamachinepool_controller.go:140]:
```suggestion
		return ctrl.Result{}, err
```
let's keep it consistent and always use `ctrl.Result{}`

File: exp/controllers/rosamachinepool_controller.go [hunk 4]
```diff
@@ -123,7 +123,21 @@ func (r *ROSAMachinePoolReconciler) Reconcile(ctx context.Context, req ctrl.Requ
...
-		return reconcile.Result{}, nil
+
+		if apierrors.IsNotFound(err) && rosaMachinePool.DeletionTimestamp != nil && !rosaMachinePool.DeletionTimestamp.IsZero() {
+			// Remove the finalizer as the controlPlan is deleted and deleting rosaMachinePool.
+			patcher, err := scope.NewRosaMachinePoolPatchHelper(rosaMachinePool, r.Client)
+			if err != nil {
+				return reconcile.Result{}, err
+			}
+			if controllerutil.RemoveFinalizer(rosaMachinePool, expinfrav1.RosaMachinePoolFinalizer) {
+				if err = patcher.Patch(context.TODO(), rosaMachinePool); err != nil {
```
Comment (muraee) [inline exp/controllers/rosamachinepool_controller.go:134]:
```suggestion
				if err = patcher.Patch(ctx, rosaMachinePool); err != nil {
```

File: exp/controllers/rosamachinepool_controller.go [hunk 5]
```diff
@@ -305,6 +319,7 @@ func (r *ROSAMachinePoolReconciler) reconcileDelete(
 		if err := ocmClient.DeleteNodePool(machinePoolScope.ControlPlane.Status.ID, nodePool.ID()); err != nil {
 			return err
 		}
+		machinePoolScope.Info("Deleting NodePool %s", nodePool.ID())
```
Comment (muraee) [inline exp/controllers/rosamachinepool_controller.go:322]:
```suggestion
		machinePoolScope.Info("Successfully deleted NodePool %s", nodePool.ID())
```

File: pkg/cloud/scope/rosacontrolplane.go [hunk 6]
```diff
@@ -201,3 +202,18 @@ func (s *ROSAControlPlaneScope) PatchObject() error {
...
+
+// GetMachinePools belong to the controlPlane managed cluster.
+func (s *ROSAControlPlaneScope) GetMachinePools() ([]expclusterv1.MachinePool, error) {
+	machinePoolList := expclusterv1.MachinePoolList{}
+	listOptions := []client.ListOption{
+		client.InNamespace(s.Cluster.Namespace),
+		client.MatchingLabels(map[string]string{clusterv1.ClusterNameLabel: s.Cluster.Name}),
+	}
+
+	if err := s.Client.List(context.TODO(), &machinePoolList, listOptions...); err != nil {
```
Comment (muraee) [inline pkg/cloud/scope/rosacontrolplane.go:214]: please pass a `context` parament to this function and use it here instead of `context.TODO()`

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 7]
```diff
@@ -327,6 +328,35 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
+		for id, mp := range machinePools {
+			if mp.DeletionTimestamp != nil && !mp.DeletionTimestamp.IsZero() {
+				continue
+			}
+			err = rosaScope.Client.Delete(context.TODO(), &machinePools[id])
+			if err != nil {
+				rosaScope.Info("Error deleting machinePool ", err)
+				errs = append(errs, err)
+				continue
+			}
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:347]:
```suggestion
			if err := rosaScope.Client.Delete(ctx, &machinePools[id]); err != nil {
				errs = append(errs, err)
			}
```
why log an error as info? we are returning the errors, so they will be logged anyway.
Also, there is no need to `continue` here.
Please always use the provided context over `context.TODO()`

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 8]
```diff
@@ -327,6 +328,35 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
 	if cluster.Status().State() != cmv1.ClusterStateUninstalling {
+		machinePools, err := rosaScope.GetMachinePools()
+		if err != nil {
+			rosaScope.Info("Error getting controlPlan machinePools ", err)
+			return ctrl.Result{}, err
+		}
+
+		var errs []error
+		for id, mp := range machinePools {
+			if mp.DeletionTimestamp != nil && !mp.DeletionTimestamp.IsZero() {
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:339]:
```suggestion
			if !mp.DeletionTimestamp.IsZero() {
```
no need to check for nil, `IsZero()` already does that.

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 9]
```diff
@@ -327,6 +328,35 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
 	}
 
 	if cluster.Status().State() != cmv1.ClusterStateUninstalling {
+		machinePools, err := rosaScope.GetMachinePools()
+		if err != nil {
+			rosaScope.Info("Error getting controlPlan machinePools ", err)
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:333]: why log an error as info? we are returning the error, so it will be logged anyway.

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 10]
```diff
@@ -327,6 +328,35 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
+			return ctrl.Result{}, err
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:334]:
```suggestion
			return ctrl.Result{}, fmt.Errorf("failed to list machine pools for cluster %s: %v, rosaScope.Name() ,err)
```

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 11]
```diff
@@ -350,6 +373,32 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
 	return ctrl.Result{RequeueAfter: time.Second * 60}, nil
 }
 
+// isMachinePoolsDeleted check if the controlplane related machinePools are deleted.
+func (r *ROSAControlPlaneReconciler) isMachinePoolsDeleted(ctx context.Context, rosaScope *scope.ROSAControlPlaneScope) (bool, error) {
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:377]:
```suggestion
func (r *ROSAControlPlaneReconciler) ensureMachinePoolsDeleted(ctx context.Context, rosaScope *scope.ROSAControlPlaneScope) (bool, error) {
```

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 12]
```diff
@@ -350,6 +373,32 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
+	if err != nil {
+		return false, err
+	}
+
+	var errs []error
+	for id, mp := range machinePools {
+		if !mp.DeletionTimestamp.IsZero() {
+			continue
+		}
+		err = rosaScope.Client.Delete(context.TODO(), &machinePools[id])
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:388]:
```suggestion
		err = rosaScope.Client.Delete(ctx, &machinePools[id])
```

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 13]
```diff
@@ -350,6 +373,32 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
+		if err != nil {
+			errs = append(errs, err)
+			continue
+		}
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:392]:
```suggestion
		if err := rosaScope.Client.Delete(context.TODO(), &machinePools[id]); err != nil {
			errs = append(errs, err)
		}
```
no need for `continue`

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 14]
```diff
@@ -327,6 +339,17 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
+		// Deleting MachinePools first.
+		deleted, err := r.isMachinePoolsDeleted(ctx, rosaScope)
+		if err != nil {
+			return ctrl.Result{}, err
+		}
+
+		if !deleted {
+			// Reconcile after 1 min giving time for machinePools to be deleted.
+			return ctrl.Result{RequeueAfter: time.Minute}, nil
+		}
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:351]: why do we call this code twice? we can just do it once at the start of `reconcileDelete()` at L303

File: controlplane/rosa/controllers/rosacontrolplane_controller.go (hunk 11 above)
Comment (serngawy) [reply controlplane/rosa/controllers/rosacontrolplane_controller.go:366]: I believe isMachinePoolsDeleted  is better naming (commonly function name start with is ) as well as matching the return boolean as an answer.

Comment (muraee) [reply controlplane/rosa/controllers/rosacontrolplane_controller.go:366]: a function starting with `isSomething`  shouldn't be doing any object mutations. Your function does actually delete machinepools not only check if they are deleted or not.

Comment (serngawy) [reply controlplane/rosa/controllers/rosacontrolplane_controller.go]: okay, I made it deleteMachinePools instead.

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 15]
```diff
@@ -350,6 +362,30 @@ func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaSc
...
+	if err != nil {
+		return false, err
+	}
+
+	var errs []error
+	for id, mp := range machinePools {
+		if !mp.DeletionTimestamp.IsZero() {
+			continue
+		}
+		if err = rosaScope.Client.Delete(context.TODO(), &machinePools[id]); err != nil {
```
Comment (muraee) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:377]:
```suggestion
		if err = rosaScope.Client.Delete(ctx, &machinePools[id]); err != nil {
```

**Comment by serngawy** [comment]
@nrb would you approve this PR

File: pkg/cloud/scope/rosacontrolplane.go [hunk 16]
```diff
@@ -201,3 +202,18 @@ func (s *ROSAControlPlaneScope) PatchObject() error {
 func (s *ROSAControlPlaneScope) Close() error {
 	return s.PatchObject()
 }
+
+// GetMachinePools belong to the controlPlane managed cluster.
+func (s *ROSAControlPlaneScope) GetMachinePools(ctx context.Context) ([]expclusterv1.MachinePool, error) {
```
Comment (dlipovetsky) [inline pkg/cloud/scope/rosacontrolplane.go:207]: This seems generic--is this defined elsewhere? cluster-api utils, maybe?

**Comment by enxebre** [comment]
Thanks! How do we know this work? We need to start working towards having CI gating in place, that might be a full rosa CRUD, that might be something lighter for starters.

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 17]
```diff
@@ -300,6 +301,16 @@ func (r *ROSAControlPlaneReconciler) reconcileNormal(ctx context.Context, rosaSc
...
 	rosaScope.Info("Reconciling ROSAControlPlane delete")
 
+	// Deleting MachinePools first.
+	deleted, err := r.deleteMachinePools(ctx, rosaScope)
+	if err != nil {
+		return ctrl.Result{}, err
+	}
+	if !deleted {
+		// Reconcile after 1 min giving time for machinePools to be deleted.
+		return ctrl.Result{RequeueAfter: time.Minute}, nil
```
[the remark this answers is not in the document]
Comment (serngawy) [reply controlplane/rosa/controllers/rosacontrolplane_controller.go:311]: no need to be configurable, it's just to have safe delete and removing the finalizer.

**Comment by serngawy** [comment]
> Thanks! How do we know this work? We need to start working towards having CI gating in place, that might be a full rosa CRUD, that might be something lighter for starters.

There is e2e and integration test effort is happening, I believe it will be in another PR.

**Comment by enxebre** [comment]
lgtm pending Daniels open comments

File: controlplane/rosa/controllers/rosacontrolplane_controller.go [hunk 18]
```diff
@@ -300,6 +301,16 @@ func (r *ROSAControlPlaneReconciler) reconcileNormal(ctx context.Context, rosaSc
 func (r *ROSAControlPlaneReconciler) reconcileDelete(ctx context.Context, rosaScope *scope.ROSAControlPlaneScope) (res ctrl.Result, reterr error) {
 	rosaScope.Info("Reconciling ROSAControlPlane delete")
 
+	// Deleting MachinePools first.
+	deleted, err := r.deleteMachinePools(ctx, rosaScope)
```
Comment (dlipovetsky) [inline controlplane/rosa/controllers/rosacontrolplane_controller.go:305]: Forgive my ignorance of ROSA here, but by comparison, the EKS control plane controller does not delete machine pools.

AFAIK, either the user deletes them directly, or relies on the topology controller (for a ClusterClass cluster) to do so.

File: pkg/cloud/scope/rosacontrolplane.go (hunk 16 above)
Comment (serngawy) [reply pkg/cloud/scope/rosacontrolplane.go]: I moved the func to util pkg so it can be re-used with any other controlPlane if needed

File: controlplane/rosa/controllers/rosacontrolplane_controller.go (hunk 18 above)
Comment (serngawy) [reply controlplane/rosa/controllers/rosacontrolplane_controller.go:306]: Not sure about EKS , but from what I can see eks controlPlane is creating/deleting the infra (network, subnets,...etc) while rosa controlPlane creates/deletes the rosaCluster and RosaMachinePool. 
The PR is fixing this [issue-4936](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4936) which as explained handling the gitops workflow for deprovision the clusters. It has a related [issue-10544](https://github.com/kubernetes-sigs/cluster-api/issues/10544) for the cluster-api machinePool as well.

**Comment by serngawy** [comment]
@enxebre would you lgtm the PR

**Comment by serngawy** [comment]
@dlipovetsky Do you have any other comment on the PR ? would you lgtm if not
