### PR TITLE
🐛 Generate event when instance fails to launch because no subnets available in an availability zone

### LINKED ISSUE #1425: Warning Events were not available for awsmachine even though errors occurred during reconciling
/kind bug

1. Create the management cluster
2. Create Cluster API infrastructure
3. Create CABPK infrastructure
4. Create AWS user stack
5. Set AWS Credentials as Environment variables
6. Create CAPA infrastructure
7. Create Cluster
8. Create MachineDeployment where AWSMachineTemplate spec has Availability Zone which was no configured during cluster configuration

Expecting that AWSMachine object will have warning event with message: failed to create AWSMachine instance: failed to run machine \"test-infra-capa-mt9yuqpw-2-7pgh6\", no subnets available in availaibility zone \"us-east-2b\"

In case of Machine deployment creation, where AWSMachineTemplat having non-existing subnet ID configured, AWSMachine object having events. In case of invalid AZ scenario, events were not present. But, in both scenarios reconcile errors happened.

```
I1216 11:09:50.993304       1 awsmachine_controller.go:261] controllers/AWSMachine "msg"="Reconciling AWSMachine" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-1-s76nm" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-1-6b8c574869-jt544" "namespace"="test-zfyu86" 
I1216 11:09:51.030851       1 awsmachine_controller.go:261] controllers/AWSMachine "msg"="Reconciling AWSMachine" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-1-dwhtp" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-1-6b8c574869-k7rtt" "namespace"="test-zfyu86" 
I1216 11:09:51.268676       1 awsmachine_controller.go:376] controllers/AWSMachine "msg"="Creating EC2 instance" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-1-s76nm" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-1-6b8c574869-jt544" "namespace"="test-zfyu86" 
I1216 11:09:51.541880       1 awsmachine_controller.go:376] controllers/AWSMachine "msg"="Creating EC2 instance" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-1-dwhtp" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-1-6b8c574869-k7rtt" "namespace"="test-zfyu86" 
E1216 11:09:52.527782       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AWSMachine instance: failed to run instance: InvalidSubnetID.NotFound: The subnet ID 'notcreated' does not exist\n\tstatus code: 400, request id: aec19f29-bab5-465d-bffd-dba75a2d8c13"  "controller"="awsmachine" "request"={"Namespace":"test-zfyu86","Name":"test-infra-capa-mt9yuqpw-1-s76nm"}
E1216 11:09:53.152206       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AWSMachine instance: failed to run instance: InvalidSubnetID.NotFound: The subnet ID 'notcreated' does not exist\n\tstatus code: 400, request id: 71eb0ce2-5d5a-4f1c-913c-d4e2167c7343"  "controller"="awsmachine" "request"={"Namespace":"test-zfyu86","Name":"test-infra-capa-mt9yuqpw-1-dwhtp"}
I1216 11:09:54.516126       1 awsmachine_controller.go:261] controllers/AWSMachine "msg"="Reconciling AWSMachine" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-2-lwtt4" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-2-86b74f4cd-56s7x" "namespace"="test-zfyu86" 
I1216 11:09:54.583399       1 awsmachine_controller.go:261] controllers/AWSMachine "msg"="Reconciling AWSMachine" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-2-7pgh6" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-2-86b74f4cd-8t5mw" "namespace"="test-zfyu86" 
I1216 11:09:54.789130       1 awsmachine_controller.go:376] controllers/AWSMachine "msg"="Creating EC2 instance" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-2-lwtt4" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-2-86b74f4cd-56s7x" "namespace"="test-zfyu86" 
I1216 11:09:55.071859       1 awsmachine_controller.go:376] controllers/AWSMachine "msg"="Creating EC2 instance" "awsCluster"="test-infra-nv978a" "awsMachine"="test-infra-capa-mt9yuqpw-2-7pgh6" "cluster"="test-flkpyr" "machine"="test-capa-mdnu7ykv-2-86b74f4cd-8t5mw" "namespace"="test-zfyu86" 
E1216 11:09:55.656366       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AWSMachine instance: failed to run machine \"test-infra-capa-mt9yuqpw-2-lwtt4\", no subnets available in availaibility zone \"us-east-2b\""  "controller"="awsmachine" "request"={"Namespace":"test-zfyu86","Name":"test-infra-capa-mt9yuqpw-2-lwtt4"}
E1216 11:09:55.818887       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AWSMachine instance: failed to run machine \"test-infra-capa-mt9yuqpw-2-7pgh6\", no subnets available in availaibility zone \"us-east-2b\""  "controller"="awsmachine" "request"={"Namespace":"test-zfyu86","Name":"test-infra-capa-mt9yuqpw-2-7pgh6"}
```

**Environment:**

- Cluster-api-provider-aws version: v0.4.6
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): darwin x86_64

### PR DESCRIPTION
**Pull request by aaroniscode**
**What this PR does / why we need it**:
When a user specifies the `availabilityZone` or `failureDomain` in a `AWSMachine` and there are no available subnets to launch the EC2 instance, there are no events registered with the `AWSMachine`. This PR adds the event.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #1425

### CODE REVIEW

File: pkg/cloud/services/ec2/instances.go [hunk 1]
```diff
@@ -159,6 +159,9 @@ func (s *Service) CreateInstance(scope *scope.MachineScope) (*infrav1.Instance,
 
 		sns := s.scope.Subnets().FilterPrivate().FilterByZone(*availabilityZone)
 		if len(sns) == 0 {
+			record.Warnf(scope.AWSMachine, "FailedCreate",
+				"Failed to create instance: no subnets available in availaibility zone %q", *availabilityZone)
```
Comment (detiber) [inline pkg/cloud/services/ec2/instances.go]:
```suggestion
				"Failed to create instance: no subnets available in availability zone %q", *availabilityZone)
```

File: pkg/cloud/services/ec2/instances.go [hunk 2]
```diff
@@ -159,6 +159,9 @@ func (s *Service) CreateInstance(scope *scope.MachineScope) (*infrav1.Instance,
...
+
 			return nil, awserrors.NewFailedDependency(
 				errors.Errorf("failed to run machine %q, no subnets available in availaibility zone %q",
```
Comment (detiber) [inline pkg/cloud/services/ec2/instances.go]:
```suggestion
				errors.Errorf("failed to run machine %q, no subnets available in availability zone %q",
```

**Comment by ncdc** [comment]
Looking at the code in `CreateInstance`, there are other places where we might return an error without recording an event. Do we want to reevaluate this function in terms of event generation? Perhaps move them up a level (and maybe reevaluate the "failed dependency" errors too)?

**Comment by aaroniscode** [comment]
> Looking at the code in `CreateInstance`, there are other places where we might return an error without recording an event. Do we want to reevaluate this function in terms of event generation? Perhaps move them up a level (and maybe reevaluate the "failed dependency" errors too)?

@ncdc I can take a look at `CreateInstance` and see if I can identity all the places where events should be generated and perhaps look at a different approach. Will likely be next week.

**Comment by randomvariable** [comment]
@aaroniscode, @ncdc  what do you want to do with this PR?

**Comment by ncdc** [comment]
It's definitely helpful, but it doesn't cover 100% of the possible errors where we are not generating events. I guess let's get the 2 typos fixed and merge it for now until we have a more comprehensive solution.

**Comment by vincepri** [comment]
If we merge this but it's not complete, we shouldn't close the related issue

**Comment by randomvariable** [comment]
Edited PR desc so it won't close the issue

**Comment by aaroniscode** [comment]
spelling fixed

/unhold
/assign @ncdc

**Comment by vincepri** [comment]
@aaroniscode It looks like the updated version with the fixed spelling didn't got pushed?

**Comment by aaroniscode** [comment]
> @aaroniscode It looks like the updated version with the fixed spelling didn't get pushed?

sorry @vincepri was git error on my side ... fixed now
