### PR TITLE
🐛  Fixes cluster creation with names starting with 'sg-'

### LINKED ISSUE #1725: Allow clusters to be created when named starting sg-
/kind bug

**What steps did you take and what happened:**
Create a cluster with the prefix `sg-`

The controller will fail with the following error:
```
1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster default/sg-cluster: failed to create security group \"bastion\" in vpc \"vpc-0db5779f71b3ed663\": InvalidParameterValue: Value (sg-cluster-bastion) for parameter GroupName is invalid. Group names may not be in the format sg-.\n\tstatus code: 400, request id: 525f5d67-7926-42f0-931e-0def5cab93da"  "controller"="awscluster" "request"={"Namespace":"default","Name":"sg-cluster"}*
```

**What did you expect to happen:**
The cluster gets created.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The restriction is listed in API docs at https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSecurityGroup.html

**Environment:**

- Cluster-api-provider-aws version: 0.5.3
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

### PR DESCRIPTION
**Pull request by gab-satchi**
**What this PR does / why we need it**:
- Fixes security group failures when attempting to create a cluster that has a name starting with 'sg-'

Fixes #1725

### CODE REVIEW

File: pkg/cloud/services/ec2/securitygroups.go [hunk 1]
```diff
@@ -455,7 +456,7 @@ func (s *Service) getSecurityGroupIngressRules(role infrav1.SecurityGroupRole) (
 }
 
 func (s *Service) getSecurityGroupName(clusterName string, role infrav1.SecurityGroupRole) string {
-	return fmt.Sprintf("%s-%v", clusterName, role)
+	return fmt.Sprintf("%s-%v", strings.TrimPrefix(clusterName, "sg-"), role)
```
Comment (randomvariable) [inline pkg/cloud/services/ec2/securitygroups.go:459]: Is there a way to account for two clusters with names "test" and "sg-test"?

Comment (randomvariable) [inline pkg/cloud/services/ec2/securitygroups.go:459]:
```suggestion
    groupPrefix := clusterName
	if strings.HasPrefix(clusterName, "sg-") {
		groupPrefix = "@" + clusterName 
	}
	return fmt.Sprintf("%s-%v", groupPrefix, role)
```

Reason for this is that Kubernetes names are DNS RFC-1123, and AWS allows 
> Allowed characters are a-z, A-Z, 0-9, spaces, and ._-:/()#,@[]+=;{}!$*.
Prefixing with @ for the `sg-` special case won't conflict with the same name without the `sg-` prefix.
