### PR TITLE
Fail creation of machine pool if no subnets matching filters found

### LINKED ISSUE #3977: AWSMachinePool subnet filters ignored if no matches found
/kind bug

**What steps did you take and what happened:**

Create an `AWSMachinePool` CR with a subnet filter that doesn't match any existing subnet in the account. 
E.g.

```yeaml
subnet:
  filters:
    - name: tag:subnet-role
      values: ["non-existent"]
```

When no subnets are found to match the provided filter the [SubnetIDs](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7411875ed5505b2c3841ae142ffba651b16c93d8/pkg/cloud/services/autoscaling/autoscalinggroup.go#L500) function in the autoscaling service will use an empty array for `subnetIDs` (rather than populating it with the IDs of any subnets found to match the filter). This empty array is then passed on to the [SubnetIDs](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7411875ed5505b2c3841ae142ffba651b16c93d8/pkg/cloud/scope/machinepool.go#L294) function on the scope which mistakenly treats the empty array of subnets IDs as no desired subnets were provided on the `AWSMachinePool` CR. This will then fall back to fetching any subnet that matches the provided availability zone (or the subnets of the `AWSCluster` if no AZs provided).

**What did you expect to happen:**

If no matching subnet is found to match the provided filters an error should be shown instead to avoid mistakenly placing instances into incorrect subnets.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

* More discussion can be found in this [Slack thread](https://kubernetes.slack.com/archives/CD6U2V71N/p1673531348507519)
* `AWSMachine` CRs respect the filter and will display an error if no matching subnet is found.
* Proposed solution: have the `SubnetIDs` function of the autoscaling service return an error if `inputFilters` are provided but `subnetIDs` is empty at the end of the function.

**Environment:**

- Cluster-api-provider-aws version: >= 1.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by AverageMarcus**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Currently if when using subnet filters with an AWSMachinePool no subnets are found to match the code will fallback to using any matching the AZs specified on the CR. This is unexpected and in contrast to how AWSMachine is handled in the same situation. 
This PR causes an error to be raised if the filters provided result in no subnets matching.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3977

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: pkg/cloud/services/autoscaling/autoscalinggroup.go [hunk 1]
```diff
@@ -526,6 +526,12 @@ func (s *Service) SubnetIDs(scope *scope.MachinePoolScope) ([]string, error) {
 		for _, subnet := range out.Subnets {
 			subnetIDs = append(subnetIDs, *subnet.SubnetId)
 		}
+
+		if len(subnetIDs) == 0 {
```
Comment (Skarlso) [inline pkg/cloud/services/autoscaling/autoscalinggroup.go:530]: Hm. So what happens if in the above there are filters and IDs defined? It might be that the list is not empty so the filter might not return anything, but the list still has a subnet ID in it.

I imagine we want that to proceed though and not care about the filter not working, right?

Comment (AverageMarcus) [reply pkg/cloud/services/autoscaling/autoscalinggroup.go:530]: Yeah in that scenario I'd expect it just to make use of the subnets with the matching IDs.

**Comment by Skarlso** [comment]
/lgtm
/approve
/hold

until tests

@AverageMarcus you can unhold if tests passed :)
