### PR TITLE
fix: added missing kms permissions required for EKS encryption

### LINKED ISSUE #2432: Permission error when enable EKS encryption
/kind bug
/area provider/eks
/priority important-soon
/milestone v0.7.0

**What steps did you take and what happened:**
Create an EK cluster and enable encruption using a KMS key. For example:
```yaml
 encryptionConfig:
    provider: "arn:aws:kms:us-east-1:12345678:alias/aws/eks"
    resources:
    - "secrets"
```

You then receive the following error:
```
 Warning  FailedCreateEKSControlPlane                   2s    aws-controller  Failed to initiate creation of a new EKS control plane: InvalidRequestException: User not authori │
│ zed to perform kms:CreateGrant operatio
```

**What did you expect to happen:**

I expect the cluster to provision with an error or warning and the EKS encryption settings to be set. 

**Environment:**

- Cluster-api-provider-aws version: 0.6.6

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard@weave.works>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
If you are using encryption with EKS there are missing permission on the controllers policy to allow using the specified KMS key.

Added missing IAM permission required to use EKS encryption. The permissions are scoped to KMS keys that have an alias name with a prefix of cluster-api-provider-aws-*.

The prefix is configurable via clusterawsadm config file.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2432 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
action required
Controllers policy updated with missing KMS permissions required to use EKS encryption, if you are planning to use EKS encryption then you will need to update your controllers policy by running `clusterawsadm bootstrap iam create-cloudformation-stack` again.  And then when you create a cluster with encryption enabled you will need to use a KMS key that has an alias name starting with `cluster-api-provider-aws-`. For further information see docs. 

```

### CODE REVIEW

File: cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go [hunk 1]
```diff
@@ -360,6 +360,16 @@ func (t Template) ControllersPolicy() *infrav1.PolicyDocument {
 				},
 				Effect: infrav1.EffectAllow,
 			},
+			{
+				Action: infrav1.Actions{
+					"kms:CreateGrant",
+					"kms:DescribeKey",
+				},
+				Resource: infrav1.Resources{
+					"arn:aws:kms:*:*:key/*",
```
Comment (randomvariable) [inline cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: `"arn:aws:kms:*:*:key/*",`

allows the creation of grants across all KMS keys which would defeat the usage of customer managed keys. I think this will need to be configurable. Is there some default key that this can be restricted to?

Comment (richardcase) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: I don't think there is a default. (@martin-ducar-gd do you know?)

We could do this instead perhaps:
- restrict to a default key name / prefix and put in the docs saying the key must have an alias of `XYZ` 
- have a feature flag or override where you explicitly change this key name/pattern

What do you think?

Comment (richardcase) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: @martin-ducar-gd - i'd be keen to get your thoughts on this.

**Comment by richardcase** [comment]
For the time being:

/hold

File: cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go (hunk 1 above)
Comment (martin-ducar-gd) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: @richardcase @randomvariable there is default alias from AWS if you do ```sh
aws kms list-aliases
```
there is this for example:

Comment (martin-ducar-gd) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: aliases are visible from API/CLI only unless you use them only then they are in Console UI

Comment (martin-ducar-gd) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: the final key alias points to still looks like wildcard you specified.
```
arn:aws:kms:<region>:<accountid>:key/<uuid>
```
no special key ids for aws managed keys

Comment (martin-ducar-gd) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: In your IAM code not sure if you specify alias "arn:aws:kms:*:*:alias/capa-alias" as an example if it will work as really its just an alias real kms is nothing that can be abstracted, but I would say we need to test

Comment (richardcase) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: Interesting, i don't have that alias if i run that command.

Comment (richardcase) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:369]: I will make some changes based on the above.

**Comment by richardcase** [comment]
@randomvariable @sedefsavas  - currently the KMS permissions are only added when EKS is enabled. It feels like this should always be added. WDYT?

**Comment by randomvariable** [comment]
> It feels like this should always be added. WDYT?

I don't think so, since the more common use case is to use default KMS encryption key for EBS volume provisioning. In terms of KMS encryption provider for EC2 CAPI, i'm not convinced of the benefit over root volume encryption. SIG Security also does not want to make a strong recommendation to use it because of concerns over performance.

**Comment by richardcase** [comment]
> I don't think so, since the more common use case is to use default KMS encryption key for EBS volume provisioning

Ok, understood. In that case i will move the configuration of the custom prefix under `EKS` in the config file. Changing back to WIP
