### PR TITLE
Fix AMI publishing failure for patch versions in book

### LINKED ISSUE #3061: AMIs with some versions (e.g., vx.x.0) not showing up on the AMI list
We have a lambda function that updates automatically the list of AMIs we list in the [docs](https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis.html).

AMIs with Kubernetes v1.23.0 is released but not showing up on that list. We were not publishing AMIs with .0 patch releases before so probably the logic is not supporting it currently. This must be a very minor fix.

/assign @Ankitasw 

/kind documentation
/triage accepted
/priority backlog
/milestone Backlog

### PR DESCRIPTION
**Pull request by shivi28**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR helps in publishing AMI images for last 4 Kubernetes releases in [book](https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis.html).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3061 

**Special notes for your reviewer**:
To find out all Patch versions for a given kubernetes release, we are taking all versions from vx.x.0 to vx.x.latest_stable_patch. And during finding images I am ignoring those patches for which image is not found

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Publish CAPA AMI images for last 4 k8s releases in CAPA book. 
```

### CODE REVIEW

File: cmd/clusterawsadm/ami/helper.go [hunk 1]
```diff
@@ -58,27 +61,54 @@ func getimageRegionList() []string {
...
+	patchVersions, err := allPatchVersions(currentVersion)
 	if err != nil {
 		return nil, err
 	}
-	supportedVersions = append(supportedVersions, nMinusOne)
 
-	nMinusTwo, err := kubernetesversions.PreviousMinorRelease(nMinusOne)
+	supportedVersions = append(supportedVersions, currentVersion)
+	supportedVersions = append(supportedVersions, patchVersions...)
+
```
Comment (sedefsavas) [inline cmd/clusterawsadm/ami/helper.go:79]:
```suggestion
	patchVersions = append(supportedVersions, currentVersion)
```

Comment (shivi28) [reply cmd/clusterawsadm/ami/helper.go:79]: I am returning supportedVersions from func, and first I will currentVersion and then add related patch versions in supportedVersions

> patchVersions = append(supportedVersions, currentVersion)

I am not able to understand the purpose of this suggestion, with this way, will loose all patch versions and supportedVersions is still empty

Comment (sedefsavas) [reply cmd/clusterawsadm/ami/helper.go:79]: Sorry I meant 
`patchVersions = append(patchVersions, currentVersion)` to avoid having a new `supportedVersions` variable.

File: hack/tools/go.mod [hunk 2]
```diff
@@ -279,4 +279,3 @@ require (
 	sigs.k8s.io/yaml v1.3.0 // indirect
 )
 
-replace sigs.k8s.io/cluster-api/hack/tools => github.com/sbueringer/cluster-api/hack/tools v0.0.0-20211111153850-3b4953a9021d
```
Comment (shivi28) [inline hack/tools/go.mod:282]: Just a cleanup, not related with this PR

File: cmd/clusterawsadm/ami/helper.go (hunk 1 above)
Comment (shivi28) [reply cmd/clusterawsadm/ami/helper.go]: done
