### PR TITLE
🐛 Reconcile target groups and listeners as their own entities

### LINKED ISSUE #5002: Load Balancer creation is not re-entrant, ELB Listeners (+ target group) failure is never retried
/kind bug

**What steps did you take and what happened:**

We were creating a new cluster and the AWSCluster resource reconciliation hit an error. In particular, we hit a rate limit which meant that a [CreateTargetGroup](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3a28a4dc361b7f106205d0f1bc263cb20df041a8/pkg/cloud/services/elb/loadbalancer.go#L430-L433) call failed.

The AWSCluster is then requeued, and the LB is reconciled again.

Because the LB is created already, the [decribeLB](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3a28a4dc361b7f106205d0f1bc263cb20df041a8/pkg/cloud/services/elb/loadbalancer.go#L94) returns the load balancer and we fall into the [update](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3a28a4dc361b7f106205d0f1bc263cb20df041a8/pkg/cloud/services/elb/loadbalancer.go#L114-L149) logic for the managed load balancer.

However, this logic does not include any management of the target groups or listeners, which leaves the load balancer in a pretty useless state with no listeners.

**What did you expect to happen:**

When the load balancer creation fails part way, the next reconcile should complete any incomplete steps, in particular, it should check that the target group and listener spec are accurate.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 2.5.0
- Kubernetes version: (use `kubectl version`): 1.30 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nrb**
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

If a load balancer is created but the calls to create a target group or
listener fails (for example, due to a rate limit), creating the group or
listener is never retried. This results in a load balancer that's
created, but there is nothing attached to it, making it useless.

This change reconciles the target groups and listeners as their own entities, so that even if they fail to create initially, we'll keep retrying.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5002

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
    Reconcile target groups and listeners independently of load balancers to handle failures more gracefully.
```

### CODE REVIEW

File: pkg/cloud/services/elb/loadbalancer.go [hunk 1]
```diff
@@ -112,6 +112,12 @@ func (s *Service) reconcileV2LB(lbSpec *infrav1.AWSLoadBalancerSpec) error {
 	// set up the type for later processing
 	lb.LoadBalancerType = lbSpec.LoadBalancerType
 	if lb.IsManaged(s.scope.Name()) {
+		// Reconcile the target groups and listeners from the spec and the ones currently attached to the load balancer.
+		_, err := s.reconcileTargetGroupsAndListeners(lb, lbSpec)
```
Comment (nrb) [inline pkg/cloud/services/elb/loadbalancer.go:116]: These should probably be split up rather than sitting in one function.

File: pkg/cloud/services/elb/loadbalancer.go [hunk 2]
```diff
@@ -1604,6 +1529,113 @@ func (s *Service) reconcileV2LBTags(lb *infrav1.LoadBalancer, desiredTags map[st
...
+						Value: aws.String("false"),
+					},
+				},
+			}
+			if _, err := s.ELBV2Client.ModifyTargetGroupAttributes(targetGroupAttributeInput); err != nil {
+				return nil, errors.Wrapf(err, "failed to modify target group attribute")
+			}
+		}
+
+		listenerInput := &elbv2.CreateListenerInput{
```
Comment (nrb) [inline pkg/cloud/services/elb/loadbalancer.go:1614]: Listeners do not appear to get names, only ARNs. I need to double check to see if we track those anywhere so we could look them up. That would make reconciling the listeners in their own function easier.

Comment (nrb) [reply pkg/cloud/services/elb/loadbalancer.go:1614]: I guess we can use the LoadBalancer ARN to get the list of listeners, then iterate through them and making sure there's one for each target group.

**Comment by nrb** [comment]
/retitle 🐛 Reconcile target groups and listeners as their own entities

File: pkg/cloud/services/elb/loadbalancer.go [hunk 3]
```diff
@@ -1604,6 +1528,164 @@ func (s *Service) reconcileV2LBTags(lb *infrav1.LoadBalancer, desiredTags map[st
 	return nil
 }
 
+// reconcileTargetGroupsAndListeners reconciles a Load Balancer's defined listeners with corresponding AWS Target Groups and Listeners.
+// These are combined into a single function since they are tightly integrated.
+func (s *Service) reconcileTargetGroupsAndListeners(spec *infrav1.LoadBalancer, lbSpec *infrav1.AWSLoadBalancerSpec) ([]*elbv2.TargetGroup, []*elbv2.Listener, error) {
+	existingTargetGroups, err := s.ELBV2Client.DescribeTargetGroups(
+		&elbv2.DescribeTargetGroupsInput{
+			LoadBalancerArn: aws.String(spec.ARN),
```
Comment (nrb) [inline pkg/cloud/services/elb/loadbalancer.go:1536]: For some reason, we're getting here without an ARN, which is causing failures.

Comment (r4f4) [reply pkg/cloud/services/elb/loadbalancer.go:1536]: I think this is the reason:
```
diff --git a/pkg/cloud/services/elb/loadbalancer.go b/pkg/cloud/services/elb/loadbalancer.go
index 0e203e870..d9a5fe400 100644
--- a/pkg/cloud/services/elb/loadbalancer.go
+++ b/pkg/cloud/services/elb/loadbalancer.go
@@ -401,6 +401,7 @@ func (s *Service) createLB(spec *infrav1.LoadBalancer, lbSpec *infrav1.AWSLoadBa
        res := spec.DeepCopy()
        s.scope.Debug("applying load balancer DNS to result", "dns", *out.LoadBalancers[0].DNSName)
        res.DNSName = *out.LoadBalancers[0].DNSName
+       res.ARN = *out.LoadBalancers[0].LoadBalancerArn
        return res, nil
 }
```
Right after we create the LB, we don't set the ARN in the output. That only happens in `describeLB`.

Comment (r4f4) [reply pkg/cloud/services/elb/loadbalancer.go:1536]: With the above change I got a successful install. But there is something I don't understand. In the first reconcile loop, the LB is created but we were not saving its ARN to the output so the TG creation failed. But in the subsequent reconcile loops, the LB exists and we should get the output from `describeLB` which should contain the ARN. It looks like the TG creation is not being attempted in that case. Maybe https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5004/files#diff-ee38bda5efe2606e7e7746a556c49a2d53d14eca60c029b8efebea657b8718f1R1551-R1553 is comparing `0 == 0` and returning `nil, nil, nil`.

File: pkg/cloud/services/elb/loadbalancer.go [hunk 4]
```diff
@@ -112,6 +112,12 @@ func (s *Service) reconcileV2LB(lbSpec *infrav1.AWSLoadBalancerSpec) error {
 	// set up the type for later processing
 	lb.LoadBalancerType = lbSpec.LoadBalancerType
 	if lb.IsManaged(s.scope.Name()) {
+		// Reconcile the target groups and listeners from the spec and the ones currently attached to the load balancer.
+		_, _, err := s.reconcileTargetGroupsAndListeners(lb, lbSpec)
```
Comment (r4f4) [inline pkg/cloud/services/elb/loadbalancer.go:116]:
```suggestion
		_, _, err := s.reconcileTargetGroupsAndListeners(spec, lbSpec)
```
That's why ELBListeners is empty!

File: pkg/cloud/services/elb/loadbalancer.go (hunk 3 above)
Comment (r4f4) [reply pkg/cloud/services/elb/loadbalancer.go:1536]: Answer: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5004/files#r1630996444

File: pkg/cloud/services/elb/loadbalancer.go (hunk 4 above)
Comment (nrb) [reply pkg/cloud/services/elb/loadbalancer.go:116]: Thanks for digging into this! Appreciate the help.

I'll review these variables, since we have 3 representations of roughly the same thing. `spec`, `lbSpec`, and `lb` probably need to have clearer names.

File: pkg/cloud/services/elb/loadbalancer.go (hunk 3 above)
Comment (nrb) [reply pkg/cloud/services/elb/loadbalancer.go:1536]: Hmm, I wonder if I didn't move this assignment line over when relocating code? I'll review the diff, but thank you for going through this!

Comment (r4f4) [reply pkg/cloud/services/elb/loadbalancer.go:1536]: Yes, that's it.

**Comment by nrb** [comment]
/test pull-cluster-api-provider-aws-e2e
/test pull-cluster-api-provider-aws-e2e-blocking
/test pull-cluster-api-provider-aws-e2e-clusterclass

@r4f4 I clarified some of the variables and updated the arguments for `reconcileTargetGroupsAndListeners`. 🤞 that e2es are happy again.

**Comment by r4f4** [comment]
Got a successful install this time.
/lgtm

File: pkg/cloud/services/elb/loadbalancer.go [hunk 5]
```diff
@@ -1604,6 +1530,164 @@ func (s *Service) reconcileV2LBTags(lb *infrav1.LoadBalancer, desiredTags map[st
...
+		&elbv2.DescribeListenersInput{
+			LoadBalancerArn: aws.String(lbARN),
+		})
+	if err != nil {
+		s.scope.Error(err, "could not describe listeners for load balancer", "arn", lbARN)
+	}
+
+	if len(existingTargetGroups.TargetGroups) == len(existingListeners.Listeners) && len(existingListeners.Listeners) == len(spec.ELBListeners) {
+		return existingTargetGroups.TargetGroups, existingListeners.Listeners, nil
+	}
```
Comment (damdo) [inline pkg/cloud/services/elb/loadbalancer.go:1555]: Could we add a comment on why this is necessary? Is this an optimization?

Also is this condition always a guarantee there is nothing to do?
Especially looking at, could there be a case where the count is off and doing `g.TargetGroupName == ln.TargetGroup.Name` naming matching would be better? 
```
len(existingTargetGroups.TargetGroups) == len(existingListeners.Listeners)
```

**Review by damdo — COMMENTED** [review]
Mostly LGTM, just a question/comment.

File: pkg/cloud/services/elb/loadbalancer.go (hunk 5 above)
Comment (nrb) [reply pkg/cloud/services/elb/loadbalancer.go:1555]: Yeah, it was an attempt to optimize so we don't go through the full loop every time.

Matching on the name might be better. I suppose it's possible that a user could create more target groups in AWS than CAPA knows about, though I'm not sure why they'd do that.

In any case, if we check that the target group names line up between AWS and our spec, we're still repeating the loop every time. The main benefit there would be that we could potentially skip doing more API calls within a single iteration.

Comment (dlipovetsky) [reply pkg/cloud/services/elb/loadbalancer.go:1555]: Thanks for the productive back-and-forth here.

Please consider a future PR for optimizations, because this PR is already complex (although the new tests are very helpful, they themselves are complex). :pray:

File: pkg/cloud/services/elb/loadbalancer_test.go [hunk 6]
```diff
@@ -1312,12 +1370,138 @@ func TestCreateNLB(t *testing.T) {
...
+
+	tests := []struct {
+		name          string
+		elbV2APIMocks func(m *mocks.MockELBV2APIMockRecorder)
+		check         func(t *testing.T, tgs []*elbv2.TargetGroup, listeners []*elbv2.Listener, err error)
+		awsCluster    func(acl infrav1.AWSCluster) infrav1.AWSCluster
+		spec          func(spec infrav1.LoadBalancer) infrav1.LoadBalancer
+	}{
+		{
+			name: "main create flow",
```
Comment (dlipovetsky) [inline pkg/cloud/services/elb/loadbalancer_test.go:1487]: Consider making this more descriptive

**Review by damdo — COMMENTED** [review]
/lgtm

/hold
@nrb feel free to unhold once happy with it merging
