### PR TITLE
Fix createLabelUpdate panic in nil map

### LINKED ISSUE #2893: AWSManagedMachinePool controller panics updating labels
/kind bug

**What steps did you take and what happened:**

Create a AWSManagedMachinePool with no labels:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: default-internal
```

Update the labels on the machine pool:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: default-internal
spec:
  labels:
    customer: shared
    role: node
```

AWSManagedMachinePool Controller panics. See logs below.

This seems to block MachinePool scale up as well.

**What did you expect to happen:**

Labels on to update. Machine to scale up. Don't Panic.

**Anything else you would like to add:**

Log output:

```
29 03:16:58.865907       1 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 978 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2391f00, 0x2ad7690)
        /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:74 +0x95
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1(0xc000ebde08)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:106 +0x88
panic(0x2391f00, 0x2ad7690)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.createLabelUpdate(0xc000ad96b0, 0xc000a28ff0, 0x1d)
        /workspace/pkg/cloud/services/eks/nodegroup.go:334 +0x1df
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.(*NodegroupService).reconcileNodegroupConfig(0xc000e43980, 0xc000a28ff0, 0x0, 0x0)
        /workspace/pkg/cloud/services/eks/nodegroup.go:394 +0x2c5
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.(*NodegroupService).reconcileNodegroup(0xc000e43980, 0xc000711200, 0xc000ebd7d8)
        /workspace/pkg/cloud/services/eks/nodegroup.go:481 +0x425
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.(*NodegroupService).ReconcilePool(0xc000e43980, 0xc000e43980, 0xc000116008)
        /workspace/pkg/cloud/services/eks/eks.go:107 +0x165
sigs.k8s.io/cluster-api-provider-aws/exp/controllers.(*AWSManagedMachinePoolReconciler).reconcileNormal(0xc000088410, 0x2b98578, 0xc000ad95f0, 0xc000334c80, 0xc001222000, 0xc001580000, 0xc000711200, 0xc00051b080)
        /workspace/exp/controllers/awsmanagedmachinepool_controller.go:184 +0x1ba
sigs.k8s.io/cluster-api-provider-aws/exp/controllers.(*AWSManagedMachinePoolReconciler).Reconcile(0xc000088410, 0x2b98578, 0xc000ad95f0, 0xc000d009c0, 0x8, 0xc0011af788, 0x15, 0xc000ad9500, 0x0, 0x0, ...)
        /workspace/exp/controllers/awsmanagedmachinepool_controller.go:168 +0x7e5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000f4aa0, 0x2b98578, 0xc000ad95c0, 0xc000d009c0, 0x8, 0xc0011af788, 0x15, 0xc000ad9500, 0x0, 0x0, ...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000f4aa0, 0x2b984d0, 0xc00012f4c0, 0x246afa0, 0xc000df4820)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000f4aa0, 0x2b984d0, 0xc00012f4c0, 0x0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc00057fb80, 0xc0000f4aa0, 0x2b984d0, 0xc00012f4c0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425
E1029 03:16:58.866071       1 controller.go:317] controller/awsmanagedmachinepool "msg"="Reconciler error" "error"="panic: assignment to entry in nil map [recovered]" "name"="lab1-default-internal" "namespace"="clusters" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSManagedMachinePool" 
```

I think the bug is here;

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1a61dfc39649749b8b8dfad8334909a388d675a7/pkg/cloud/services/eks/nodegroup.go#L331-L334

`payload.AddOrUpdateLabels` is default a nil map. 
I haven't add a chance to a dev environment for the capa controller and test it, but I think the fix is just
```diff
	payload := eks.UpdateLabelsPayload{
+		AddOrUpdateLabels: map[string]*string{},
	}
```

**Environment:**

- Cluster-api-provider-aws version: 1.0.0
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`):  N/A

### PR DESCRIPTION
**Pull request by zhengtianbao**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix assignment to AddOrUpdateLabels in nil map of `UpdateLabelsPayload{}`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2893

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix createLabelUpdate panic in nil map
```

### CODE REVIEW

File: pkg/cloud/services/eks/nodegroup.go [hunk 1]
```diff
@@ -328,7 +328,9 @@ func (s *NodegroupService) reconcileNodegroupVersion(ng *eks.Nodegroup) error {
 
 func createLabelUpdate(specLabels map[string]string, ng *eks.Nodegroup) *eks.UpdateLabelsPayload {
 	current := ng.Labels
-	payload := eks.UpdateLabelsPayload{}
+	payload := eks.UpdateLabelsPayload{
+		AddOrUpdateLabels: map[string]*string{},
```
Comment (randomvariable) [inline pkg/cloud/services/eks/nodegroup.go:332]:
```suggestion
		AddOrUpdateLabels: aws.StringMap(map[string]string{}),
```

By convention.
