### PR TITLE
:bug: Restore subnet management functionality

### LINKED ISSUE #4026: SubnetSpec changes in `v1beta2` break existing use-cases
/kind bug
/kind api-change

The changes introduced in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3748 (aimed at solving server side apply issues with Cluster Class) break existing use-cases around subnets created by CAPA.

The change makes the `ID` property on `SubnetSpec` now be a required field where previously this was optional. This change means that configuration to subnets used for CAPA clusters can now _only_ be done if infrastructure is created by the user resulting in CAPA only allowing for either the default subnet layout or a bring-your-own network where the user would be required to create everything (VPC, subnets, etc.) externally before the creation of the `AWSCluster` CR.

With `v1beta1` and earlier it was possible to specify some of the subnet configuration (such as the CIDR block and the AWS tags) but still have CAPA create the resources for you.

For example, we have a situation where we need more control over what resources end up in what subnets and rely on AWS tags and subnet filters to achieve this. 

```yaml
spec:
  network:
    subnets:
      - cidrBlock: 10.0.0.0/24
        availabilityZone: eu-west-1a
        tags:
          subnet-role: control-plane
      - cidrBlock: 10.0.1.0/24
        availabilityZone: eu-west-1b
        tags:
          subnet-role: control-plane
... etc ...
```

With this approach we can configure CAPA to create all the subnets we need, with the tags we can then filter on, without having to use an external process to create these resources. This is no longer possible with `v1beta2`.

In the PR it was acknowledged that this was a breaking change and that we'd need to come up with an alternative to solve this problem going forward but unfortunately was forgotten about so I'm opening this issue to have that discussion and try to come up with a solution to both the original issue the PR was fixing and the use cases currently in use that require configuring subnets in CAPA.

This also fits into the wider discussion around networking in CAPA and the improvements / changes desired.

**Related:**
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3748
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3883
* https://kubernetes.slack.com/archives/CD6U2V71N/p1675159432540519
* https://kubernetes.slack.com/archives/CD6U2V71N/p1675159036932519

**Environment:**

- Cluster-api-provider-aws version: v2.0.2 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by vincepri**
/kind bug
/kind api-change
/kind regression

**What this PR does / why we need it**:

This PR reverts some commits originally introduced in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3748 to support ClusterClass with SSA and proposes a different approach that's backward compatible with that functionality.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4026 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
action required
When the VPC is managed, the `SubnetSpec.ID` field can be used now to offload subnet management to the AWSCluster controller. The `id` should be set to a string that DOES NOT start with `subnet-`; the value is used to set the `Name` tag in the subnet resource and the actual AWS resource ID is stored in `SubnetSpec.ResourceID`.
```

### CODE REVIEW

**Comment by vincepri** [comment]
/cc @AverageMarcus @AndiDog 

Might also be good to incorporate https://github.com/giantswarm/cluster-api-provider-aws/pull/437/commits/407bd9806fd50e1c970aa75ae79acfa7728070cf

**Comment by AndiDog** [comment]
> /cc @AverageMarcus @AndiDog
> 
> Might also be good to incorporate [giantswarm@407bd98](https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf)

I'd be happy if you cherry-pick that commit. That's exactly the workaround we have in our fork for the moment. It applies almost cleanly to v2.2.1, so I'm sure the patch is still fine.

What do maintainers say about reverting to the original behavior for now? (CC @richardcase who was also involved in network discussions apart from the people already assigned on this PR)

**Comment by vincepri** [comment]
From a project and SIG perspective, we should strive to retain key features and behavior that made this project successful. With Terraform licensing change, I suspect more and more users would prefer Cluster API to manage infrastructure required to have a functional cluster. Subnets are definitely in that mix.

The reversal of these commits it's not a breaking change, but rather a regression fix; going from required to optional is fine from an API perspective.

Regarding ClusterClass and SSA, as mentioned in the PR description we should find alternative solutions rather than breaking existing functionality.

**Comment by richardcase** [comment]
> From a project and SIG perspective, we should strive to retain key features and behavior that made this project successful. With Terraform licensing change, I suspect more and more users would prefer Cluster API to manage infrastructure required to have a functional cluster. Subnets are definitely in that mix.

Agreed on this. In respect to this change, there was a steer from certain users / community that we needed ClusterClass support. And this change was positioned as changing something that wasn't documented / unintended behaviour.

However, this was an incorrect decision, like i mentioned in the other issue:

> In the slack discussion on this i did raise it was a change in behaviour but was told its undocumented and is a side effect. In hindsight, we should've been more diligent on this and not bowed to pressure to get clusterclass support out.

If we can restore the original behaviour, especially in a non-breaking API way, then I'm all for that 👍 

> Regarding ClusterClass and SSA, as mentioned in the PR description we should find alternative solutions rather than breaking existing functionality.

Agreed and again, at the time it was deemed to be changing undocumented and untested behaviour (in hindsight that assertion was incorrect).

As mentioned in other issues, the networking code in CAPA has been a mess for years and is very brittle.

So lets:

- get the original behaviour restored
- push forward on the "re-thinking networking in CAPA" so that we can enable greater flexibility and remove us from the current confines of the networking API & code (so #1484 and the proposal thats been worked on by @AndiDog )

@Skarlso @Ankitasw @dlipovetsky - wdyt?

**Comment by richardcase** [comment]
With the alternatives:


> Add a new required field, e.g. name that functions as the key in the listMap.
        Preserve the current behavior and prefill the field from the existing id if present, or generate one on the fly.

I know Sedef spent a lot of time speaking with people in CAPI about this problem before making the change. I wasn't in them so can't say if this was explicitly covered

> Create a brand new struct with a more complex networking proposal.

We have started work on this already and its the future for CAPA as it will enable a number of use cases that aren't possible now....and it will enable us to break free from the existing networking code.

File: api/v1beta2/network_types.go [hunk 1]
```diff
@@ -307,8 +308,18 @@ func (v *VPCSpec) IsIPv6Enabled() bool {
 // SubnetSpec configures an AWS Subnet.
 type SubnetSpec struct {
 	// ID defines a unique identifier to reference this resource.
+	// If you're bringing your subnet, set the AWS subnet-id here, it must start with `subnet-`.
```
Comment (JoelSpeed) [inline api/v1beta2/network_types.go:311]: This is an AWS-ism right? We aren't requiring users to go name their subnets in a specific way?

I would expect, when populating the subnets, that I should be able to provide any name and, if the subnet exists and isn't tagged with the CAPI resource management tag (`sigs.k8s.io/cluster-api-provider-aws/cluster`), is left alone, but, if it doesn't exist, is created and tagged, or is that not the expected flow? That was my understanding of how other BYO works

File: api/v1beta2/network_types.go [hunk 2]
```diff
@@ -307,8 +308,18 @@ func (v *VPCSpec) IsIPv6Enabled() bool {
...
+	//
+	// If you'd like the provider to create a subnet for you, the id can be set to
+	// any placeholder value that does not start with `subnet-`; upon creation, the provider will
+	// replace the placeholder with the actual subnet id and set the ARN field.
 	ID string `json:"id"`
 
+	// ResourceID is the subnet identifier from AWS, READ ONLY.
+	// This field is populated when the provider manages the subnet.
```
Comment (JoelSpeed) [inline api/v1beta2/network_types.go:319]: How is the read only nature of this field enforced?

File: api/v1beta2/network_types.go (hunk 1 above)
Comment (JoelSpeed) [reply api/v1beta2/network_types.go:311]: I tested this out and understand now, the name that you enter here will become the name of the resource once it's created, but, the id field will then be repopulated by the subnet ID from AWS.

So above questions don't matter, but, how will this work with GitOps? I wouldn't expect the ID field to be overwritten as this might cause issues for someone trying to create their AWSCluster resource via some sort of GitOps flow

What's the motivation for overwriting the ID?

**Comment by JoelSpeed** [comment]
Manually tested this and it allowed me to specify subnets and have the AWSCluster create them as I had requested, it then repopulated the information into the spec as expected

File: api/v1beta2/network_types.go (hunk 1 above)
Comment (sbueringer) [reply api/v1beta2/network_types.go:311]: Just to add some context. When we made the initial change to lead to this whole feature regression our goal was to make it compatible with ClusterClass. But that basically only meant that CAPA should be compatible with SSA in a way that if an AWSCluster is continuously written by some tool (GitOps, ClusterClass controller or another controller) this tool and the CAPA controller should not continuously fight over field values because the AWSCluster CRD is not compatible with SSA in a way that allows to converge to a final state of the AWSCluster.

**Comment by sbueringer** [comment]
Just to add some context.

When we made the initial change that lead to this whole feature regression our goal was to make CAPA compatible with ClusterClass. But that basically only required that CAPA should be compatible with SSA in a way that if an AWSCluster is continuously written by some tool (GitOps, ClusterClass controller or another controller) this tool and the CAPA controller should not continuously fight over field values because the AWSCluster CRD is not compatible with SSA in a way that allows to converge to a final state of the AWSCluster.

Example:
* GitOps, ClusterClass, some other controller writes an AWSCluster
* CAPA controller writes fields back to the AWSCluster
* => this should converge and not be an infinite fight over field values

I hope this is still a goal for CAPA independent of that ClusterClass is an experimental feature. Of course if folks are just using kubectl apply to write AWSCluster once in a while this problem does not occur.

File: api/v1beta2/network_types.go (hunk 1 above)
Comment (sbueringer) [reply api/v1beta2/network_types.go:311]: I think the godoc is outdated a bit. To make this all work we cannot overwrite the ID

Comment (sbueringer) [reply api/v1beta2/network_types.go:311]: Some roughly related context: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4474#issuecomment-1702799841

File: pkg/cloud/services/network/subnets.go [hunk 3]
```diff
@@ -468,7 +472,10 @@ func (s *Service) createSubnet(sn *infrav1.SubnetSpec) (*infrav1.SubnetSpec, err
 	}
 
 	subnet := &infrav1.SubnetSpec{
-		ID:               *out.Subnet.SubnetId,
+		// Preserve the original identifier, this won't be a valid subnet ID, which
+		// is stored in the ResourceID field.
+		ID:               sn.ID,
+		ResourceID:       *out.Subnet.SubnetId,
```
Comment (sbueringer) [inline pkg/cloud/services/network/subnets.go:478]: Q: Here we are setting ResourceID to SubnetId and in l.340 to SubnetArn, is this the same thing?

(just to be sure)

**Comment by sbueringer** [comment]
PR looks good to me overall. I'm not that familiar with CAPA though.

Would be good if we can verify (in case it is not covered by e2e tests) that when we deploy a CAPA cluster in the supported use cases we won't end up in infinite reconciles if the AWSCluster is continuously re-applied (we should be able to test this with either ClusterClass, GitOps or just re-running kubectl apply, probably ideally with SSA enabled though)

**Comment by richardcase** [comment]
> this tool and the CAPA controller should not continuously fight over field values.
> ..
> I hope this is still a goal for CAPA independent of that ClusterClass is an experimental feature.

Its good to raise this @sbueringer 👍 Currently the way around this to tell your GitOps tool of choice to ignore certain fields (assuming the tool used supports this). Its far from ideal. We will make sure this use case is covered in our "re-thinking networking in CAPA".

> Would be good if we can verify (in case it is not covered by e2e tests) that when we deploy a CAPA cluster in the supported use cases 

Agreed. Looking at the PR, @vincepri  has restored the test that covers this functionality. However, the original test doesn't use ClusterClass....so we can add one. 

I can help and add this additional test or did you want to do it @vincepri  as part of this PR? I'm good either way...just wanted to offer some help.

**Comment by vincepri** [comment]
> I can help and add this additional test or did you want to do it @vincepri as part of this PR? I'm good either way...just wanted to offer some help.

If you have time to add a new test and maybe incorporate the commit from @AndiDog https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf as well, that would be great!

Going to fixup the tests today, let's run the e2e suite and merge this?

**Comment by richardcase** [comment]
> If you have time to add a new test and maybe incorporate the commit from @AndiDog [giantswarm@407bd98](https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf) as well, that would be great!

Will do 👍  I'll also keep an eye on the e2e tests runs if you kick them off on this PR.

File: pkg/cloud/services/network/subnets.go [hunk 4]
```diff
@@ -398,6 +402,10 @@ func (s *Service) describeSubnets() (*ec2.DescribeSubnetsOutput, error) {
 }
 
 func (s *Service) createSubnet(sn *infrav1.SubnetSpec) (*infrav1.SubnetSpec, error) {
+	// When managing subnets, the ID specified in the spec is the name of the subnet.
+	sn.Tags["Name"] = sn.ID
```
Comment (JoelSpeed) [inline pkg/cloud/services/network/subnets.go:406]: Need to cater for an empty map here, panics otherwise
```suggestion
	if sn.Tags == nil {
		sn.Tags = make(infrav1.Tags)
	}
	sn.Tags["Name"] = sn.ID
```

File: pkg/cloud/services/network/subnets.go [hunk 5]
```diff
@@ -158,12 +160,20 @@ func (s *Service) reconcileSubnets() error {
 			existingSubnet.DeepCopyInto(sub)
```
Comment (JoelSpeed) [inline pkg/cloud/services/network/subnets.go:160]: This line currently breaks the name preservation, `existing` never populates `resourceID` so `resourceID` gets wiped and the `id` gets set to the subnet-id.

Propose to update the fetching of existing to only populate `resourceID` (effect for existing is that `id` and `subnetID` will become the same value), and then copy the `id` from `sub` before we do the deepcopy.

This way the `id` is preserved if it exists today, but no longer has the effect of being required to match the subnet name.

**Comment by fabriziopandini** [comment]
Sorry for getting late to this.
I think that @sbueringer captures well what happened; I would also add that based on what I observed, everyone acted in the best interest of all the project and the sigs and at the best of their capabilities, and the regression of behavior is not intentional. 

Unfortunately, it is now evident that we lacked expertise, and even if we did all our best to involve all the relevant folks and broadcast the discussion, even if we signaled the change with a new API version, we should've been more diligent when this was discussed/when we made the final call on the implementation. 

But said that, I think that we should stick to SSA for cluster class, because this is the native approach provided by the API server to solve the same problem - controllers/tools co-authoring the same item on a list -. 
Note: We explored alternatives as well (the CAPI PR history should have some of them), but  discovered that the complexity is high and ultimately, our custom version of SSA will never be as good as the upstream one

**Comment by AndiDog** [comment]
> PR needs rebase.

If you incorporate my test from https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf, you'll also need to merge the `main` branch and put commit https://github.com/giantswarm/cluster-api-provider-aws/commit/6d4d4983c1d35fcd230a412ba5d588091269b384 on top. We resolved that merge conflict in our fork. Let me know if I can help here – in the form of pushing to this PR's branch.

**Comment by vincepri** [comment]
> > PR needs rebase.
> 
> If you incorporate my test from [giantswarm@407bd98](https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf), you'll also need to merge the `main` branch and put commit [giantswarm@6d4d498](https://github.com/giantswarm/cluster-api-provider-aws/commit/6d4d4983c1d35fcd230a412ba5d588091269b384) on top. We resolved that merge conflict in our fork. Let me know if I can help here – in the form of pushing to this PR's branch.

Are you able to open a PR after this one is merged?

File: pkg/cloud/services/network/subnets.go (hunk 5 above)
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:165]: `existing` should now populate the `resourceID ` properly

**Comment by AndiDog** [comment]
> > > PR needs rebase.
> > 
> > 
> > If you incorporate my test from [giantswarm@407bd98](https://github.com/giantswarm/cluster-api-provider-aws/commit/407bd9806fd50e1c970aa75ae79acfa7728070cf), you'll also need to merge the `main` branch and put commit [giantswarm@6d4d498](https://github.com/giantswarm/cluster-api-provider-aws/commit/6d4d4983c1d35fcd230a412ba5d588091269b384) on top. We resolved that merge conflict in our fork. Let me know if I can help here – in the form of pushing to this PR's branch.
> 
> Are you able to open a PR after this one is merged?

I'm fine to add the test as separate PR, yes.

**Comment by AndiDog** [comment]
I'll try to review this change soon. My first idea is to use `key` (or `listKey` 🤷) instead of `name` so we don't get confused – `name` could imply that the cloud resource gets assigned a name (e.g. `Name` tag), but here the field is only used within the YAML spec, not in cloud resources.

**Comment by Skarlso** [comment]
One suggestion we discussed during Office Hours is that the field name `name` is confusing because multiple AWS resource do have names and it could be expected that his field denotes that name.

Suggestion was to be more specific and call it what it is. Either `listKey`, `mapKey`, or `key` or something similar of nature.

Thanks! :)

**Comment by richardcase** [comment]
Lets get this in the next patch release

/milestone v2.2.3

**Comment by vincepri** [comment]
The PR description was outdated, the `name` field isn't there any longer. Instead, we keep the current `id` field as the listMap's unique key identifier and add `resourceId` field for the actual AWS resource id.

File: api/v1beta2/network_types.go (hunk 2 above)
Comment (JoelSpeed) [reply api/v1beta2/network_types.go:361]: Should we add CEL then to make it immutable?
```suggestion
	// ResourceID is the subnet identifier from AWS, READ ONLY.
	// This field is populated when the provider manages the subnet.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="resourceID is immutable"
```

File: pkg/cloud/services/network/subnets.go [hunk 6]
```diff
@@ -336,6 +343,7 @@ func (s *Service) describeVpcSubnets() (infrav1.Subnets, error) {
 	for _, ec2sn := range sns.Subnets {
 		spec := infrav1.SubnetSpec{
 			ID:               *ec2sn.SubnetId,
```
Comment (JoelSpeed) [inline pkg/cloud/services/network/subnets.go:345]: Do we still want this to be set to the subnetId?

Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:348]: We need to yeah, otherwise the ID is empty and it gets stored empty

File: pkg/cloud/services/network/subnets.go (hunk 3 above)
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:495]: Yes

File: api/v1beta2/network_types.go (hunk 2 above)
Comment (richardcase) [reply api/v1beta2/network_types.go:361]: Do we want to handle this on this PR or as a follow up?

**Review by richardcase — COMMENTED** [review]
This look good to me and the e2e are passing. It would be good to resolve any open comments.

File: api/v1beta1/awscluster_conversion.go [hunk 7]
```diff
@@ -73,6 +74,37 @@ func (src *AWSCluster) ConvertTo(dstRaw conversion.Hub) error {
...
+
+	if restored.Spec.NetworkSpec.VPC.IsIPv6Enabled() && restored.Spec.NetworkSpec.VPC.IPv6.IPAMPool != nil {
+		if dst.Spec.NetworkSpec.VPC.IPv6.IPAMPool == nil {
+			dst.Spec.NetworkSpec.VPC.IPv6.IPAMPool = &infrav2.IPAMPool{}
+		}
+
+		restoreIPAMPool(restored.Spec.NetworkSpec.VPC.IPv6.IPAMPool, dst.Spec.NetworkSpec.VPC.IPv6.IPAMPool)
+	}
+
+	dst.Spec.NetworkSpec.AdditionalControlPlaneIngressRules = restored.Spec.NetworkSpec.AdditionalControlPlaneIngressRules
```
Comment (AndiDog) [inline api/v1beta1/awscluster_conversion.go:93]: This lines are duplicated and from other changes that are already on the `main` branch. Looks like a rebase mistake.

File: api/v1beta1/awscluster_conversion.go [hunk 8]
```diff
@@ -73,6 +74,37 @@ func (src *AWSCluster) ConvertTo(dstRaw conversion.Hub) error {
...
+
+	// Restore SubnetSpec.ResourceID field, if any.
+	for _, subnet := range restored.Spec.NetworkSpec.Subnets {
+		if len(subnet.ResourceID) == 0 {
```
Comment (AndiDog) [inline api/v1beta1/awscluster_conversion.go:97]:
```suggestion
		if subnet.ResourceID == "" {
```

to avoid linter warnings

File: pkg/cloud/services/network/subnets.go [hunk 9]
```diff
@@ -399,6 +410,15 @@ func (s *Service) describeSubnets() (*ec2.DescribeSubnetsOutput, error) {
 }
 
 func (s *Service) createSubnet(sn *infrav1.SubnetSpec) (*infrav1.SubnetSpec, error) {
+	// When managing subnets, the ID specified in the spec is the name of the subnet.
+	if sn.Tags == nil {
+		sn.Tags = make(infrav1.Tags)
+	}
+	if len(sn.ID) > 0 {
+		sn.Tags["Name"] = sn.ID
+	}
```
Comment (AndiDog) [inline pkg/cloud/services/network/subnets.go:419]: Please deep-copy the `Tags` field into a local variable so we don't introduce strange bugs by changing the input parameter. Also, the `Name` tag may already be given and must be respected, so the `id` field should be the fallback value if _no_ `Name` tag is specified.

File: api/v1beta2/network_types.go [hunk 10]
```diff
@@ -348,8 +349,19 @@ func (v *VPCSpec) IsIPv6Enabled() bool {
 // SubnetSpec configures an AWS Subnet.
 type SubnetSpec struct {
 	// ID defines a unique identifier to reference this resource.
+	// If you're bringing your subnet, set the AWS subnet-id here, it must start with `subnet-`.
+	//
+	// When the VPC is managed by CAPA, and you'd like the provider to create a subnet for you,
+	// the id can be set to any placeholder value that does not start with `subnet-`;
+	// upon creation, the subnet AWS identifier will be populated in the `ResourceID` field and
+	// the `id` field is going to be used as the subnet name.
```
Comment (AndiDog) [inline api/v1beta2/network_types.go:357]:
```suggestion
	// the `id` field is going to be used as the subnet name. If you specify a tag
	// called `Name`, it takes precedence.
```

File: pkg/cloud/services/network/subnets.go [hunk 11]
```diff
@@ -52,6 +52,8 @@ func (s *Service) reconcileSubnets() error {
 	subnets := s.scope.Subnets()
 	defer func() {
 		s.scope.SetSubnets(subnets)
+		s.scope.Debug("Reconciled subnets", "subnets", subnets)
+		conditions.MarkTrue(s.scope.InfraCluster(), infrav1.SubnetsReadyCondition)
```
Comment (AndiDog) [inline pkg/cloud/services/network/subnets.go:56]: The deferred function also runs after errors and thus we don't know whether subnets are ready. The condition was previously set at the end of `reconcileSubnets` – why did this code get moved?

File: pkg/cloud/services/network/subnets.go [hunk 12]
```diff
@@ -174,18 +190,14 @@ func (s *Service) reconcileSubnets() error {
...
-	}
 
-	// Proceed to create the rest of the subnets that don't have an ID.
-	if !unmanagedVPC {
+		// Proceed to create the rest of the subnets that don't have an ID.
 		for i := range subnets {
 			subnet := &subnets[i]
-			if subnet.ID != "" {
+
+			// If we have a ResourceID (ARN), the resource was already created,
```
Comment (AndiDog) [inline pkg/cloud/services/network/subnets.go:198]: The field name and description makes me think it's an ID like `subnet-abc123`, but this comment says it's an ARN. Can you fix / clarify the description and/or comments?

And it's unclear what a "temporary one" is. Currently, the PR says that the `subnet.ID` field has two meanings: `subnet-xxx` for bring-your-own, or any other name for the managed VPC use case. Either way, the field value won't change and therefore can't be temporary, if I understand this right.

File: pkg/cloud/services/network/subnets.go [hunk 13]
```diff
@@ -469,10 +489,14 @@ func (s *Service) createSubnet(sn *infrav1.SubnetSpec) (*infrav1.SubnetSpec, err
 	}
 
 	subnet := &infrav1.SubnetSpec{
-		ID:               *out.Subnet.SubnetId,
+		// Preserve the original identifier, this won't be a valid subnet ID, which
+		// is stored in the ResourceID field.
```
Comment (AndiDog) [inline pkg/cloud/services/network/subnets.go:493]:
```suggestion
		// Preserve the original identifier, this won't be a valid subnet ID in case
		// of a managed subnet. The AWS identifier `subnet-xxx` is stored in the ResourceID field.
```

File: pkg/cloud/services/network/subnets.go (hunk 3 above)
Comment (AndiDog) [reply pkg/cloud/services/network/subnets.go:495]: I guess this got fixed and we're not using ARNs in `ResourceID` anymore? See my other review comment where that is confusing in a leftover code comment.

**Review by AndiDog — COMMENTED** [review]
/hold

(due to review comments)

**Comment by richardcase** [comment]
As discussed just now on slack, to allow more time for testing and review:

/milestone v2.3.0

File: api/v1beta2/network_types.go (hunk 2 above)
Comment (vincepri) [reply api/v1beta2/network_types.go:361]: I don't have a strong opinion to enforce this today, the reconciler will overwrite it anyways

File: pkg/cloud/services/network/subnets.go (hunk 11 above)
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:56]: A bit confused, I didn't add these lines

File: pkg/cloud/services/network/subnets.go [hunk 14]
```diff
@@ -136,35 +138,49 @@ func (s *Service) reconcileSubnets() error {
...
+					record.Warnf(s.scope.InfraCluster(), "FailedTagSubnet", "Failed tagging unmanaged Subnet %q: %v", existingSubnet.GetResourceID(), err)
 					break
 				}
 			}
 
-			// Update subnet spec with the existing subnet details
 			// TODO(vincepri): check if subnet needs to be updated.
+
+			if len(sub.ID) > 0 {
+				// NOTE: Describing existing subnets overrides the subnet.ID with the subnet's ARN,
```
[the remark this answers is not in the document]
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:162]: Clarified the comment a bit, the function assumes `ID` is the ARN

File: pkg/cloud/services/network/subnets.go [hunk 15]
```diff
@@ -136,35 +138,49 @@ func (s *Service) reconcileSubnets() error {
...
 		} else if unmanagedVPC {
 			// If there is no existing subnet and we have an umanaged vpc report an error
-			record.Warnf(s.scope.InfraCluster(), "FailedMatchSubnet", "Using unmanaged VPC and failed to find existing subnet for specified subnet id %d, cidr %q", sub.ID, sub.CidrBlock)
-			return errors.New(fmt.Errorf("usign unmanaged vpc and subnet %s (cidr %s) specified but it doesn't exist in vpc %s", sub.ID, sub.CidrBlock, s.scope.VPC().ID).Error())
+			record.Warnf(s.scope.InfraCluster(), "FailedMatchSubnet", "Using unmanaged VPC and failed to find existing subnet for specified subnet id %d, cidr %q", sub.GetResourceID(), sub.CidrBlock)
+			return errors.New(fmt.Errorf("usign unmanaged vpc and subnet %s (cidr %s) specified but it doesn't exist in vpc %s", sub.GetResourceID(), sub.CidrBlock, s.scope.VPC().ID).Error())
 		}
 	}
 
-	if !unmanagedVPC {
```
[the remark this answers is not in the document]
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:167]: The previous if conditions lacked readability, do you have strong opinions against the current structure?

File: pkg/cloud/services/network/subnets.go (hunk 12 above)
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:198]: Clarified, was a leftover

File: pkg/cloud/services/network/subnets.go (hunk 9 above)
Comment (vincepri) [reply pkg/cloud/services/network/subnets.go:419]: Agreed on the latter point about fallback, although not sure why we'd need to deepcopy the tags given that we want to change the input?

File: pkg/cloud/services/network/subnets.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (Skarlso) [reply pkg/cloud/services/network/subnets.go:167]: I'm not particularly found of single case switch statements, though the older format was a bit funny too.

Can't we have this instead?
```go
	if unmanagedVPC && len(subnets) < 1 {
		record.Warnf(s.scope.InfraCluster(), "FailedNoSubnet", "Expected at least 1 subnet but got 0")
		return errors.New("expected at least 1 subnet but got 0")
	}

	if !unmanagedVPC {
		// Check that we need at least 1 private and 1 public subnet after we have updated the metadata
		if len(subnets.FilterPrivate()) < 1 {
			record.Warnf(s.scope.InfraCluster(), "FailedNoPrivateSubnet", "Expected at least 1 private subnet but got 0")
			return errors.New("expected at least 1 private subnet but got 0")
		}
		if len(subnets.FilterPublic()) < 1 {
			record.Warnf(s.scope.InfraCluster(), "FailedNoPublicSubnet", "Expected at least 1 public subnet but got 0")
			return errors.New("expected at least 1 public subnet but got 0")
		}

		for i := range subnets {
			subnet := &subnets[i]
			if subnet.ID != "" {
				continue
			}

			nsn, err := s.createSubnet(subnet)
			if err != nil {
				return err
			}
			nsn.DeepCopyInto(subnet)
		}
	}

```

[the remark this answers is not in the document]
Comment (Skarlso) [reply pkg/cloud/services/network/subnets.go:167]: Note, that I merged the second `if !unmanagedVPC` into this one.

**Comment by AndiDog** [comment]
Looks good so far. Which cases did you test manually so far? Should we help testing this change before merging?

I think we should fix the single-case `switch` statement – see the remaining comment. Then all comments seem to be addressed.

**Comment by vincepri** [comment]
@AndiDog Only tested without ClusterClass, creating subnets managed by CAPA in different AZs

**Review by AndiDog — COMMENTED** [review]
/lgtm
/unhold
