### PR TITLE
:bug: Improve EC2 state handling, and set error for manually deleted EC2 instances

### LINKED ISSUE #1238: Log entry for every event
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Debugging a machine that hasn't reconciled correctly which has an InvalidUpdate 
entry in its Events, but didn't see a corresponding log entry.

**What did you expect to happen:**
A log entry published in addition to the Event.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.4.3
- Kubernetes version: (use `kubectl version`):  N/A
- OS (e.g. from `/etc/os-release`): N/A

### LINKED ISSUE #1239: Terminated instance not detected
/kind bug

**What steps did you take and what happened:**
If an EC2 instance is deleted from when the AWSMachine is in a Running state, warning InvalidUpdate events will be recorded, but the AWSMachine does not transition to Error.

**What did you expect to happen:**
AWSMachine transitions to Error for user deletion.

**Anything else you would like to add:**
Missing log entries related to the publishing of events as per #1238 

Test case:
1. Deploy as per quick start guide
2. Wait for worker nodes to reach running (verify with kubectl get machines)
3. Wait 10 minutes
4. Delete the EC2 instance backing one of the worker nodes

**Environment:**

- Cluster-api-provider-aws version: 0.4.3
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Tweaks EC2 instance state handling in the following ways:
* Emit log event as well as publish event to resource for better traceability
* Ignore instance attributes for validation when the instance is terminated, or about to transition to terminated from "shutting-down".
* Don't error when EC2 instance is stopping or is stopped, as machine could be rebooted.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1239 
Fixes #1238

### CODE REVIEW

**Comment by vincepri** [comment]
Reviewing

File: controllers/awsmachine_controller.go [hunk 1]
```diff
@@ -390,14 +400,21 @@ func (r *AWSMachineReconciler) reconcileLBAttachment(machineScope *scope.Machine
 // validateUpdate checks that no immutable fields have been updated and
 // returns a slice of errors representing attempts to change immutable state.
 func (r *AWSMachineReconciler) validateUpdate(spec *infrav1.AWSMachineSpec, i *infrav1.Instance) (errs []error) {
+
+	// EC2 instance attributes start disapearing during shutdown and termination, so do not
+	// perform more checks
+	if i.State == infrav1.InstanceStateTerminated || i.State == infrav1.InstanceStateShuttingDown {
+		return errs
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]:
```suggestion
		return nil
```

File: controllers/awsmachine_controller.go [hunk 2]
```diff
@@ -323,11 +327,16 @@ func (r *AWSMachineReconciler) reconcileNormal(ctx context.Context, machineScope
...
+		machineScope.Info("EC2 instance is running", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
 		machineScope.SetReady()
 	case infrav1.InstanceStatePending:
-		machineScope.Info("Machine instance is pending", "instance-id", *machineScope.GetInstanceID())
+		machineScope.Info("EC2 instance is pending", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		r.Recorder.Eventf(machineScope.AWSMachine, corev1.EventTypeWarning, "InstancePending", "EC2 instance is %q", instance.State)
+	case infrav1.InstanceStateStopping, infrav1.InstanceStateStopped:
+		machineScope.Info("EC2 instance is hibernating", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		r.Recorder.Eventf(machineScope.AWSMachine, corev1.EventTypeWarning, "InstanceHibernation", "EC2 instance is %q", instance.State)
 	default:
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: Can we add a comment here that states the unexpected states and that we're going to transition to failed state?

File: controllers/awsmachine_controller.go [hunk 3]
```diff
@@ -323,11 +327,16 @@ func (r *AWSMachineReconciler) reconcileNormal(ctx context.Context, machineScope
...
 	switch instance.State {
 	case infrav1.InstanceStateRunning:
-		machineScope.Info("Machine instance is running", "instance-id", *machineScope.GetInstanceID())
+		machineScope.Info("EC2 instance is running", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
 		machineScope.SetReady()
 	case infrav1.InstanceStatePending:
-		machineScope.Info("Machine instance is pending", "instance-id", *machineScope.GetInstanceID())
+		machineScope.Info("EC2 instance is pending", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		r.Recorder.Eventf(machineScope.AWSMachine, corev1.EventTypeWarning, "InstancePending", "EC2 instance is %q", instance.State)
+	case infrav1.InstanceStateStopping, infrav1.InstanceStateStopped:
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: This needs upstream support to make the Machine to flip back to `provisioned` state. Once https://github.com/kubernetes-sigs/cluster-api/issues/1622#issuecomment-545575154 is fixed

Comment (detiber) [reply controllers/awsmachine_controller.go]: If it is stopped, it's not guaranteed to have the same networkID when it returns up, so stopping/stopped should likely result in a permanent failure.

Comment (vincepri) [reply controllers/awsmachine_controller.go]: Got it, so it should possibly transition to a failure state, like it did before.

@randomvariable what's the reason behind this change?

Comment (randomvariable) [reply controllers/awsmachine_controller.go]: what do you mean network ID? The IP address remains the same (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html):
> The instance keeps its private IPv4 address. The instance gets a new public IPv4 address, unless it has an Elastic IP address, which doesn't change during a stop/start.

Comment (vincepri) [reply controllers/awsmachine_controller.go]: In that case, the node should be able to come back up. Would you mind testing this use case on an actual cluster?

Comment (detiber) [reply controllers/awsmachine_controller.go]: Ah, right...  I had forgotten we aren't assigning public IPs :joy:

Do we have to worry about Node deletion with this, though? Doesn't the AWS cloud provider delete Nodes for instances that are in a stopped state?

File: controllers/awsmachine_controller.go (hunk 2 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: Done. Explicitly stating the states, and making sure the entire lifecycle is covered. Added a link to the place in the documentation describing the states as well.

File: controllers/awsmachine_controller.go (hunk 3 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: checking now.

File: controllers/awsmachine_controller_test.go [hunk 4]
```diff
@@ -27,7 +27,10 @@ import (
 	. "github.com/onsi/gomega"
 	. "github.com/onsi/gomega/gstruct"
 	"github.com/pkg/errors"
+<<<<<<< HEAD
```
Comment (detiber) [inline controllers/awsmachine_controller_test.go]: looks like some rebase conflicts

**Comment by randomvariable** [comment]
Ready for review.
Have added descriptive unit tests based on the various transitions that can occur.

File: controllers/awsmachine_controller.go [hunk 5]
```diff
@@ -321,13 +325,29 @@ func (r *AWSMachineReconciler) reconcileNormal(ctx context.Context, machineScope
...
+
+		// We do not error yet so that the final terminated state is captured.
+	case infrav1.InstanceStateShuttingDown:
+		machineScope.V(1).Info("Unexpected EC2 instance termination", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		machineScope.SetUnready()
+		r.Recorder.Eventf(machineScope.AWSMachine, corev1.EventTypeWarning, "InstanceUnexpectedTermination", "Unexpected instance termination")
+	case infrav1.InstanceStateTerminated:
+		machineScope.V(1).Info("Unexpected EC2 instance termination", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		machineScope.SetUnready()
+		r.Recorder.Eventf(machineScope.AWSMachine, corev1.EventTypeWarning, "InstanceUnexpectedTermination", "Unexpected instance termination")
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: These two cases could be simplified to a single one capturing both

File: controllers/awsmachine_controller.go [hunk 6]
```diff
@@ -321,13 +325,29 @@ func (r *AWSMachineReconciler) reconcileNormal(ctx context.Context, machineScope
...
 		machineScope.SetReady()
-	case infrav1.InstanceStatePending:
-		machineScope.Info("Machine instance is pending", "instance-id", *machineScope.GetInstanceID())
-	default:
+	case infrav1.InstanceStateStopping:
+		machineScope.V(1).Info("EC2 instance is stopping", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		machineScope.SetUnready()
+	case infrav1.InstanceStateStopped:
+		machineScope.V(1).Info("EC2 instance is stopped", "state", instance.State, "instance-id", *machineScope.GetInstanceID())
+		machineScope.SetUnready()
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: Same as below, these can be simplified in a single case condition capturing both

File: pkg/cloud/scope/machine.go [hunk 7]
```diff
@@ -154,6 +154,11 @@ func (m *MachineScope) SetReady() {
 	m.AWSMachine.Status.Ready = true
 }
 
+// SetUnready sets the AWSMachine Ready Status to false
+func (m *MachineScope) SetUnready() {
```
Comment (vincepri) [inline pkg/cloud/scope/machine.go]:
```suggestion
func (m *MachineScope) SetNotReady() {
```

Nit for readability

File: controllers/awsmachine_controller.go (hunk 5 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: These ones can't. Not erroring in the case of InstanceStateShuttingDown, because our state machine can then no longer transition to Terminated, hence the comment.

**Comment by randomvariable** [comment]
Tweaked to be less noisy in the logs.

File: controllers/awsmachine_controller.go [hunk 8]
```diff
@@ -308,26 +311,36 @@ func (r *AWSMachineReconciler) reconcileNormal(ctx context.Context, machineScope
...
 	switch instance.State {
+	case infrav1.InstanceStatePending, infrav1.InstanceStateStopping, infrav1.InstanceStateStopped:
+		machineScope.SetNotReady()
 	case infrav1.InstanceStateRunning:
-		machineScope.Info("Machine instance is running", "instance-id", *machineScope.GetInstanceID())
 		machineScope.SetReady()
-	case infrav1.InstanceStatePending:
-		machineScope.Info("Machine instance is pending", "instance-id", *machineScope.GetInstanceID())
-	default:
+	case infrav1.InstanceStateShuttingDown, infrav1.InstanceStateTerminated:
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: Don't we need a default case at all here?

File: controllers/awsmachine_controller.go [hunk 9]
```diff
@@ -189,23 +189,23 @@ func (r *AWSMachineReconciler) reconcileDelete(machineScope *scope.MachineScope,
 		// and AWSMachine
 		// 3. Issue a delete
 		// 4. Scale controller deployment to 1
-		machineScope.V(2).Info("Unable to locate instance by ID or tags")
+		machineScope.V(2).Info("Unable to locate EC2 instance by ID or tags")
```
Comment (vincepri) [inline controllers/awsmachine_controller.go]: In the future, it'd be great if we can separate commits or PRs that aren't in the same scope

File: controllers/awsmachine_controller.go (hunk 8 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: Nope. There's literally no other options. Gone for explicitness so people know what the control flow is for each state.

Comment (vincepri) [reply controllers/awsmachine_controller.go]: Usually it's good practice adding default cases to catch unexpected values. For example, if a future SDK version add a new state which we don't look out for, we might incur in unexpected behavior. 

Having it would give us a safeguard, wdyt?

Comment (randomvariable) [reply controllers/awsmachine_controller.go]: It's not an SDK thing, it's the EC2 API, this has remained stable for years, and would be a major change. I'd rather we actually fail and add the appropriate handling.
I think soundness is better than completeness in this specific case.

File: controllers/awsmachine_controller.go (hunk 9 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: will do

File: controllers/awsmachine_controller.go (hunk 8 above)
Comment (randomvariable) [reply controllers/awsmachine_controller.go]: Blaming the brain worms. Yup, added with test.
