### PR TITLE
Fix cluster/machine status updates

### LINKED ISSUE #430: Cluster and machine status fails to update on first run
/kind bug

**What steps did you take and what happened:**
Create a cluster, on the first run, the status doesn't get updated properly.
```
E1130 17:44:52.063316       1 machine_scope.go:121] [machinescope] failed to store provider status for machine "aws-controlplane-s6qx9" in namespace "default": Operation cannot be fulfilled on machines.cluster.k8s.io "aws-controlplane-s6qx9": the object has been modified; please apply your changes to the latest version and try again
E1130 17:44:52.070631       1 scope.go:164] [scope] failed to store provider status for cluster "test1" in namespace "default": Operation cannot be fulfilled on clusters.cluster.k8s.io "test1": the object has been modified; please apply your changes to the latest version and try again
```

**What did you expect to happen:**
Status should get updated without an error.

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vince@vincepri.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #430 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/cloud/aws/actuators/machine_scope.go [hunk 1]
```diff
@@ -94,31 +95,33 @@ func (m *MachineScope) Region() string {
...
 }
 
 func (m *MachineScope) Close() {
 	if m.MachineClient == nil {
 		return
 	}
 
-	if _, err := m.MachineClient.Update(m.Machine); err != nil {
-		klog.Errorf("[machinescope] failed to update machine: %v", err)
+	latestMachine, err := m.MachineClient.Get(m.Name(), metav1.GetOptions{})
```
Comment (detiber) [inline pkg/cloud/aws/actuators/machine_scope.go]: Shouldn't this be done after the update? It looks like the Update below is actually a noop, and if it somehow did manage to Update the object it would cause the following UpdateStatus to fail.

File: pkg/cloud/aws/actuators/scope.go [hunk 2]
```diff
@@ -166,11 +150,18 @@ func (s *Scope) Close() {
 		return
 	}
 
-	if err := s.storeClusterConfig(); err != nil {
+	latestCluster, err := s.ClusterClient.Get(s.Name(), metav1.GetOptions{})
```
Comment (detiber) [inline pkg/cloud/aws/actuators/scope.go]: same comment here as with machine update

File: pkg/cloud/aws/actuators/machine_scope.go (hunk 1 above)
Comment (vincepri) [reply pkg/cloud/aws/actuators/machine_scope.go]: During my tests, it actually showed that the machine somehow gets updated before this method gets called. The `Update` below returns the latest version of the Machine (if successful) with the changes.

After trying and debugging in different stages, the conclusion I came up with is that these calls have to be chained. There is definitely something weird about the object being updated somewhere else during the first run, that's why we need to get the latest version. That said, doing the call even on subsequent calls seems to be fine.

**Comment by vincepri** [comment]
@detiber This is good to go I believe. It requires https://github.com/kubernetes-sigs/cluster-api/pull/627 to be merged and vendor updated to function on the first run.

File: pkg/apis/awsprovider/v1alpha1/register.go [hunk 3]
```diff
@@ -133,17 +152,17 @@ func EncodeClusterStatus(status *AWSClusterProviderStatus) (*runtime.RawExtensio
 	}, nil
 }
 
-// EncodeClusterConfig marshals the cluster config.
-func EncodeClusterConfig(status *AWSClusterProviderSpec) (*runtime.RawExtension, error) {
```
Comment (ashish-amarnath) [inline pkg/apis/awsprovider/v1alpha1/register.go]: Thank you for fixing my code :)
