### PR TITLE
:warning: :bug:Add flag option for uncompressed userdata.

### LINKED ISSUE #1639: userdata should not be compressed
/kind bug

**What steps did you take and what happened:**
I wrote a bootstrap provider for coreos ignition. But I failed to create ec2 instance because user data is gzip compressed and ignition failed to read it.

**What did you expect to happen:**

It's bootstraper's responsibility to decide whether it should compress userdata or not 
**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v0.4.10
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): container linux

### PR DESCRIPTION
**Pull request by MartinForReal**
**What this PR does / why we need it**:
Add flag option for uncompressed userdata.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1639

### CODE REVIEW

**Comment by MartinForReal** [comment]
flag option is not added to alphav2 because it will introduce a schema change in alphav2.

File: api/v1alpha2/zz_generated.conversion.go [hunk 1]
```diff
@@ -603,6 +603,7 @@ func autoConvert_v1alpha3_AWSMachineSpec_To_v1alpha2_AWSMachineSpec(in *v1alpha3
 	}
 	// WARNING: in.RootVolume requires manual conversion: does not exist in peer-type
 	out.NetworkInterfaces = *(*[]string)(unsafe.Pointer(&in.NetworkInterfaces))
+	// WARNING: in.UncompressedUserData requires manual conversion: does not exist in peer-type
```
Comment (detiber) [inline api/v1alpha2/zz_generated.conversion.go]: This will require a modification to `api/v1alpha2/awscluster_conversion.go` to attempt to restore the value from annotation if it is set, similar to how `Status.Bastion` is handled here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7240d095ea189681c6f92c79e14dd37853af2512/api/v1alpha2/awscluster_conversion.go#L65-L67

File: api/v1alpha3/awsmachine_types.go [hunk 2]
```diff
@@ -94,6 +94,13 @@ type AWSMachineSpec struct {
 	// +kubebuilder:validation:MaxItems=2
 	NetworkInterfaces []string `json:"networkInterfaces,omitempty"`
 
+	// UncompressedUserData specify whether the user data is gzip-compressed before it is sent to ec2 instance.
+	// cloud-init has built-in support for gzip-compressed user data
+	// user data stored in aws secret manager is always gzip-compressed.
+	//
+	// +optional
+	UncompressedUserData *bool `json:"uncompressedUserData,omitempty"`
```
Comment (detiber) [inline api/v1alpha3/awsmachine_types.go]: What are your thoughts on the long term solution for the naming of this variable? Do you think we should revert the logic when we are ready to make the next set of breaking API changes?

File: api/v1alpha2/zz_generated.conversion.go (hunk 1 above)
Comment (MartinForReal) [reply api/v1alpha2/zz_generated.conversion.go]: I added a unit test in awsmachine_conversion_test.go. 

https://github.com/minsheng-fintech-corp-ltd/cluster-api-provider-aws/blob/35ec7d2a453c10ab1ce5ddca85ccaa7744f4eb2e/api/v1alpha2/awsmachine_conversion_test.go#L154-L166

and added manual conversion in restoreAWSMachineSpec
 
https://github.com/minsheng-fintech-corp-ltd/cluster-api-provider-aws/blob/master/api/v1alpha2/awsmachine_conversion.go

Thanks for the info!

File: api/v1alpha3/awsmachine_types.go (hunk 2 above)
Comment (MartinForReal) [reply api/v1alpha3/awsmachine_types.go]: I think this works well for cloud-init based images.  Since most of the Linux distribution has support for cloud-init, I think there is no need to rever the logic.

**Comment by MartinForReal** [comment]
@detiber I've changed the code accordingly. Any advice is appreciated. Thanks!
