### PR TITLE
Fix to avoid updating tags when there is no change in them and add unit tests

### LINKED ISSUE #1499: Tags on resources are being updated during reconciliation even if those tags are not changed.
/kind bug

In our environment, we are noticing that tags on some AWS resources are being updated even if there is no change in them. It happens when there are external tags on those AWS resources created by some external entities dynamically. 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Created external tags on some AWS resources like security groups for example. There was no change in cluster created/managed tags but during reconciliation, we are seeing that those tags are still being updated even if there is no change.

**What did you expect to happen:**
Tags should not be updated if there is no change.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The code where it is happening is here:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/tags/tags.go#L58-#L60

And here is the patch we are using to handle this:
https://github.com/aveshagarwal/cluster-api-provider-aws/commit/358028f9688a94939876bfe862cef4bc2e3fefc0

**Environment:**
AWS

- Cluster-api-provider-aws version: 
latest

- Kubernetes version: (use `kubectl version`): 

1.15, 1.16

- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by aveshagarwal**
**What this PR does / why we need it**:

This PR fixes an issue where tags were being updated even there was no change in them. It happens when there are external tags on resources in addition to cluster managed tags.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1499 

@ncdc @detiber @vincepri @randomvariable @rudoi

### CODE REVIEW

**Comment by detiber** [comment]
lgtm
/assign @rudoi 
/assign @ncdc

File: pkg/cloud/tags/tags_test.go [hunk 1]
```diff
@@ -0,0 +1,85 @@
+/*
+Copyright 2019 The Kubernetes Authors.
```
Comment (ncdc) [inline pkg/cloud/tags/tags_test.go]:
```suggestion
Copyright 2020 The Kubernetes Authors.
```

File: pkg/cloud/tags/tags.go [hunk 2]
```diff
@@ -54,9 +54,21 @@ func Apply(params *ApplyParams) error {
...
+	want := infrav1.Build(buildParams)
+
+	// Some tags could be external set by some external entities
+	// and that means even if there is no change in cluster
+	// managed tags, tags would be updated as "current" and
+	// "want" would be different due to external tags.
+	// This fix makes sure that tags are updated only if
+	// there is a change in cluster managed tags.
+	return want.Difference(current)
+}
```
Comment (vincepri) [inline pkg/cloud/tags/tags.go]: Can we just move these 2 lines in the `Ensure` call instead?

Comment (ncdc) [reply pkg/cloud/tags/tags.go]: I'm guessing the reason he did it this way is to be able to unit test computeDiff. If you want to unit test the other func, you have to either mock out the ec2 CreateTags call, or we need to use something like a function pointer with test/default configurations to avoid ec2.

Comment (vincepri) [reply pkg/cloud/tags/tags.go]: Yeah makes sense, it's probably fine to keep it this way, although it's definitely harder to read/follow than before

File: pkg/cloud/tags/tags_test.go (hunk 1 above)
Comment (aveshagarwal) [reply pkg/cloud/tags/tags_test.go]: done.

**Comment by randomvariable** [comment]
lgtm for me
