### PR TITLE
🐛 fix: backwards compatibility for AWS service endpoint resolution

### LINKED ISSUE #5670: [Bug] Custom Service Endpoints are not selected after AWS SDK v2 migration
/kind bug

CAPA recently migrated to use AWS SDK v2 (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2225). As a side effect, in the use case of custom service endpoints, the service IDs for supported AWS APIs (e.g. S3, EC2, ELB, etc) has changed in v2.

In AWS SDK v2, the service ID is defined separately in each service package and do not have a strict convention. For example, EC2 service defines service ID as `EC2`, but ELB defines as `Elastic Load Balancing`.

**What steps did you take and what happened:**

Define custom service endpoints for all AWS API in use to CAPA via command argument: `--service-endpoints=region:service-id=url,...`. I detailed my finding with some "silly" hacks: https://gist.github.com/tthvo/df8dd8407cad12bde6d0c7440946a0d6

Despite providing the v2 service ID (or v1 service ID), CAPA failed to find the endpoint for certain services. Those are:

-  **Elastic Load Balancing**
- **Elastic Load Balancing v2**
- **Resource Groups Tagging API**
- **EventBridge**
- **Secrets Manager**

Basically, services that define its `serviceID` with more than 1 word.

**What did you expect to happen:**

CAPA should be able to correctly select the custom service endpoints for AWS APIs in use.

**Anything else you would like to add:**

As per the below code block ([endpoints.go#L90-L94](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/88cb4b92b1a76591623e9d5ef347bfdc22010622/pkg/cloud/endpoints/endpoints.go#L90-L94)):

```go
// convert service ID to UpperCase as service IDs in AWS SDK GO V2 are UpperCase & Go map is Case Sensitve
// This is for backward compabitibility
// Ref: SDK V2 https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#pkg-constants
// Ref: SDK V1 https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/endpoints#pkg-constants
serviceID = strings.ToUpper(serviceID)
```

> service IDs in AWS SDK GO V2 are UpperCase & Go map is Case Sensitve

This statement is only partially correct.

**Environment:**

- Cluster-api-provider-aws version: `2.9.0` and latest `main`.
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): `Fedora Linux 42 (Workstation Edition)`

### PR DESCRIPTION
**Pull request by tthvo**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

In AWS SDKv1, each service exports a constant `EndpointsID` to look up the custom service endpoint, for example, see ref [[0]](https://github.com/aws/aws-sdk-go/blob/070853e88d22854d2355c2543d0958a5f76ad407/service/resourcegroupstaggingapi/service.go#L33-L34). In AWS SDKv2, these contants are no longer available. Thus, for backwards compatibility, we copy those constants from the SDKv1 and map them to the corresponding `ServiceID` in SDK v2.

Additionally, in AWS SDKv1, `elb` and `elbv2` uses the same identifier (i.e. same EndpointsID), thus the same custom endpoint [[1]](https://github.com/aws/aws-sdk-go/blob/070853e88d22854d2355c2543d0958a5f76ad407/service/elbv2/service.go#L32-L33) [[2]](https://github.com/aws/aws-sdk-go/blob/070853e88d22854d2355c2543d0958a5f76ad407/service/elb/service.go#L32-L33). For backwards compatibility, if `elbv2` endpoint is undefined, `elbv2` endpoint resolver should fall back to `elb` endpoint if any.

This also fixes the bug where CAPA does not recognize services that define its `serviceID` with more than 1 word due to the incorrect assumption [endpoints.go#L90-L94](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/88cb4b92b1a76591623e9d5ef347bfdc22010622/pkg/cloud/endpoints/endpoints.go#L90-L94)). The services are:

- Elastic Load Balancing
- Elastic Load Balancing v2
- Resource Groups Tagging API
- EventBridge
- Secrets Manager

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5670 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] includes emoji in title 
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
ensure custom service endpoints for supported AWS services are properly selected by
both AWS SDKv2 and SDKv1 service ID (for backwards compatibility) 
```

### CODE REVIEW

**Comment by damdo** [comment]
Cc. @punkwalker

File: pkg/cloud/endpoints/endpoints.go [hunk 1]
```diff
@@ -46,6 +46,18 @@ var (
...
+		"elasticloadbalancing": elb.ServiceID,
+		"ec2":                  ec2.ServiceID,
+		"tagging":              rgapi.ServiceID,
+		"sqs":                  sqs.ServiceID,
+		"events":               eventbridge.ServiceID,
+		"eks":                  eks.ServiceID,
+		"ssm":                  ssm.ServiceID,
+		"sts":                  sts.ServiceID,
+		"secretsmanager":       secretsmanager.ServiceID,
+	}
```
Comment (damdo) [inline pkg/cloud/endpoints/endpoints.go:60]: I am assuming this is exhaustive for the services we use in CAPA right?

**Comment by nrb** [comment]
/approve
/hold
until the question about endpoint coverage is answered.

File: pkg/cloud/endpoints/endpoints.go (hunk 1 above)
Comment (tthvo) [reply pkg/cloud/endpoints/endpoints.go:60]: @damdo @nrb Right, this is the exhaustive list for all the services in CAPA.

In `pkg/cloud/endpoints/endpoints.go`, we define an endpoint resolver for each service that CAPA use. So, I add an entry for each resolver defined.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/97cc94cf6b6207425c202e24feedef88d63b4fa0/pkg/cloud/endpoints/endpoints.go#L135-L137

Except `elbv2`, which has the same identifier with `elb` in SDK v1 - that is `"elasticloadbalancing"`.
