### PR TITLE
fix: Process extra statements for Cluster API Controllers

### LINKED ISSUE #2387: extraStatements in the clusterAPIControllers config for clusterawsadm is being ignored
/kind bug

**What steps did you take and what happened:**
When using `clusterawsadm` to create IAM roles, we cannot add inline statements for the controllers. The field from the configuration is accepted but ignored.

Here is the configuration used to reproduce:

```
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1alpha1
kind: AWSIAMConfiguration
spec:
  eks:
    enable: true
    allowIAMRoleCreation: true 
    defaultControlPlaneRole:
      disable: true
    managedMachinePool:
      disable: false
  clusterAPIControllers:
    disabled: false
    extraStatements:
      - Action:
          - "iam:GetPolicy"
        Effect: "Allow"
        Resource:
          - "*"
```

The `clusterawsadm` command is working and does not fail, but the inline policy is not created.

**What did you expect to happen:**
I expected an inline policy to be added to the controllers role. But nothing happened.

**Environment:**

- Cluster-api-provider-aws version: 0.6.5
- Kubernetes version: (use `kubectl version`): v1.16.15-eks-ad4801
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Szymongib**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR fixes the bug causing `extraStatements` section to be ignored for `clusterAPIControllers` when creating IAM role.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2387

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] adds unit tests

**Release note**:

```release-note
Process extra statements for Cluster API Controllers
```

### CODE REVIEW

File: cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go [hunk 1]
```diff
@@ -387,6 +387,10 @@ func (t Template) ControllersPolicy() *iamv1.PolicyDocument {
 		})
 	}
 
+	if t.Spec.ClusterAPIControllers.ExtraStatements != nil {
```
Comment (sedefsavas) [inline cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go:390]: We should not change the `controllers.cluster-api-provider-aws.sigs.k8s.io` here, instead similar to controlplane and node, we want to attach extra statemements as `inline policy`: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2a183f580873ed46aebdbba77da212a3476682aa/cmd/clusterawsadm/cloudformation/bootstrap/control_plane.go#L24

And add this as inline policy in the `Policies` section of the controller role.

Comment (Szymongib) [reply cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go]: Oh yea, that totally makes sense! Sorry about that, fixed.

**Comment by richardcase** [comment]
For final approval: 

/assign sedefsavas
