### PR TITLE
Skip deleting 'control-plane.cluster-api-provider-aws.sigs.k8s.io' if it does not exist in the e2e setup

### LINKED ISSUE #3794: e2e tests fail if run once before but IAM role "control-plane.cluster-api-provider-aws.sigs.k8s.io" does not exist
/kind bug

**What steps did you take and what happened:**
When running the end to end tests, if they fail, they can leave an AWS account partially configured. If re-run, then the end to end tests attempt to clean up the CloudFormation. However this cleanup logic explicitly errors if it fails to find and delete the CloudFormation role "control-plane.cluster-api-provider-aws.sigs.k8s.io".

**What did you expect to happen:**
If the role is missing, skip deletion and swallow the error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Slack Thread: https://kubernetes.slack.com/archives/CD6U2V71N/p1666639763600259?thread_ts=1666639754.548709&cid=CD6U2V71N

**Environment:**

- Cluster-api-provider-aws version: main branch
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by cnmcavoy**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Does not explicitly error when a IAM role deletion fails in `deleteResourcesInCloudFormation` e2e logic. All of the other error handling in `deleteResourcesInCloudFormation` is suppressed, it's unclear why this error was checked and no others.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3794

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

File: test/e2e/shared/aws.go [hunk 1]
```diff
@@ -454,8 +454,7 @@ func deleteResourcesInCloudFormation(prov client.ConfigProvider, t *cfn_bootstra
 		tayp := val.AWSCloudFormationType()
 		if tayp == configservice.ResourceTypeAwsIamRole {
 			role := val.(*cfn_iam.Role)
-			_, err := iamSvc.DeleteRole(&iam.DeleteRoleInput{RoleName: aws.String(role.RoleName)})
-			Expect(err).NotTo(HaveOccurred())
+			_, _ = iamSvc.DeleteRole(&iam.DeleteRoleInput{RoleName: aws.String(role.RoleName)})
```
Comment (Ankitasw) [inline test/e2e/shared/aws.go:457]: I see few places(like detaching role policies) that the errors are checked.
Is there a specific scenario you came up where the tests are failing?

Comment (Ankitasw) [reply test/e2e/shared/aws.go:457]: Ok i missed the slack thread. Read it now.
