### PR TITLE
🐛 Filter out AWS internal tags when reconciling

### LINKED ISSUE #5120: Feature Flag TagUnmanagedNetworkResources does not work if network resources have internal aws tags
/kind bug

**What steps did you take and what happened:**
We want to use already existing subnets. But we want to enable the `TagUnmanagedNetworkResources` feature flag, so that we can manage the subnet tags. But the subnets were created using CloudFormation, so they contain some tags of the form `aws::cloudformation::*`. When trying to add or delete tags of that form, the AWS API returns an error, because those are reserved/internal AWS tags.
```
InvalidParameterValue: Value ( aws:cloudformation:stack-name ) for parameter key is invalid. Tag keys starting with 'aws:' are reserved for internal use
```

**What did you expect to happen:**
When enabling the TagUnmanagedNetworkResources feature flag, VPC and subnets are reconciled without errors, and tags are applied normally.

**Anything else you would like to add:**
Would it be possible to change CAPA code so that it ignores tags that start with `aws:`?

**Environment:**

- Cluster-api-provider-aws version: 2.5.2
- Kubernetes version: (use `kubectl version`): 1.28
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by fiunchinho**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Tags that start with `aws:` are considered internal AWS tags and can't be add or removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5120

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Filter out AWS internal tags when reconciling AWS infra
```

### CODE REVIEW

File: pkg/cloud/tags/tags_test.go [hunk 1]
```diff
@@ -34,14 +34,7 @@ import (
 )
 
 var (
-	bp = infrav1.BuildParams{
```
Comment (fiunchinho) [inline pkg/cloud/tags/tags_test.go:37]: I inlined the `BuildParams` object on each test case to make it easier to see what's being tested.

File: pkg/cloud/tags/tags.go [hunk 2]
```diff
@@ -127,10 +131,12 @@ func WithEKS(eksclient eksiface.EKSAPI) BuilderOption {
 	return func(b *Builder) {
 		b.applyFunc = func(params *infrav1.BuildParams) error {
 			tags := infrav1.Build(*params)
-
 			eksTags := make(map[string]*string, len(tags))
 			for k, v := range tags {
-				eksTags[k] = aws.String(v)
+				// We want to filter out the tag keys that start with `aws:` as they are reserved for internal AWS use.
+				if !strings.HasPrefix(k, "aws:") {
```
Comment (s3rj1k) [inline pkg/cloud/tags/tags.go:137]: Maybe make `aws:` as const ? (Will help readability)

Comment (fiunchinho) [reply pkg/cloud/tags/tags.go]: Nice suggestion! I've introduced a constant, please take another look.

Comment (s3rj1k) [reply pkg/cloud/tags/tags.go]: Yep LGTM, thanks for taking care of this.
