### PR TITLE
Fixes for gc related tests

### LINKED ISSUE #3998: GC_WORKLOAD variable is missing in e2e conf to support gc test cases
/kind bug

**What steps did you take and what happened:**
gc testcases will apply some workloads for the testing. It will read the yaml from GC_WORKLOAD variable. We should provide the variables in e2e conf, otherwise the testcases would fail with exception.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by wyike**
(cherry picked from commit 331fe732b18f3aef1bedcea6b85612799ed45af7)

**What type of PR is this?**

**What this PR does / why we need it**:
Backport  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3999 to release-1.5 as suggested in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3998#issuecomment-1408329673.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3998

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fixes bugs in garbage collection e2e tests
```

### CODE REVIEW

File: test/e2e/suites/gc_managed/gc_managed_test.go [hunk 1]
```diff
@@ -87,7 +87,7 @@ var _ = ginkgo.Describe("[managed] [gc] EKS Cluster external resource GC tests",
 		cp := ms.GetControlPlaneByName(ctx, ms.GetControlPlaneByNameInput{
 			Getter:    e2eCtx.Environment.BootstrapClusterProxy.GetClient(),
 			Namespace: cluster.Spec.InfrastructureRef.Namespace,
-			Name:      cluster.Spec.InfrastructureRef.Name,
+			Name:      cluster.Spec.ControlPlaneRef.Name,
```
Comment (Skarlso) [inline test/e2e/suites/gc_managed/gc_managed_test.go:90]: Heh, nice.

**Comment by Ankitasw** [comment]
@wyike please update release notes.

**Comment by wyike** [comment]
> /milestone v1.5.3

done

**Comment by Ankitasw** [comment]
To enable this we would need to add prow jobs for release 1.5, I guess.
cc @richardcase
