### PR TITLE
🏃 e2e: don't fail test if log streaming fails

### LINKED ISSUE #1491: e2e: log streaming errors should not cause overall test failures
/kind failing-test

**What steps did you take and what happened:**
See e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-master/1219706915278295042 - the functional tests passed but the pod log streaming failed and cause the entire test to fail.

**What did you expect to happen:**
Log streaming failures should not cause the entire test to fail.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: master

/assign
/lifecycle active
/milestone v0.5.0
/priority important-soon

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Don't fail e2e test if log streaming fails.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1491

### CODE REVIEW

File: test/e2e/e2e_suite_test.go [hunk 1]
```diff
@@ -169,17 +169,11 @@ var _ = BeforeSuite(func() {
 
 	// Verify capi components are deployed
 	common.WaitDeployment(kindClient, capiNamespace, capiDeploymentName)
-	go func() {
-		defer GinkgoRecover()
-		watchLogs(capiNamespace, capiDeploymentName, logPath)
-	}()
+	watchLogs(capiNamespace, capiDeploymentName, logPath)
```
Comment (detiber) [inline test/e2e/e2e_suite_test.go]: I just realized that we aren't also doing a `WaitDeployment` or a `watchLogs` on the CABPK or KCP components, I'm thinking we probably should be.

Comment (detiber) [reply test/e2e/e2e_suite_test.go]: Created https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1493 to address
