### PR TITLE
🏃 Enabled scopelint and fixed reported errors with suggestions

### LINKED ISSUE #1542: cleanup: enable `scopelint` linter
After #1535, we updated the golangci-lint to the latest version and matched the upstream Cluster API format for the linter, it seems there were a bunch of linters missing.

- Head over to [.golanci-lint.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/.golangci.yml) in the root of this repository.
- Remove the linter from the `linters.disable` list.
- Run `make lint-full`.
- Fix the reported errors with the suggestions.
- Submit a PR with the changes.

Feel free to reach out at any time if you need guidance or help.

/kind cleanup
/help
/good-first-issue
/milestone Next
/priority backlog

### PR DESCRIPTION
**Pull request by teaguecole**
**What this PR does / why we need it**:
This enables scopelint.  We need it so we can follow best practices with go and write cleaner code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1542

I am not sure which of the following labels to add. Other and Minor seemed like the most reasonable for this.  I am also open to enabling more linters and cleaning up code, but I also understand the value of having good-first-issues to bring in new contributors.  I kind of enjoy doing this as it makes me better at writing Go but I don't want to hog all the good-first-issues.

### CODE REVIEW

File: pkg/cloud/services/ec2/eips.go [hunk 1]
```diff
@@ -119,6 +119,7 @@ func (s *Service) releaseAddresses() error {
 	}
 
 	for _, ip := range out.Addresses {
```
Comment (detiber) [inline pkg/cloud/services/ec2/eips.go]: nit: Instead of shadowing the variable here, what about:
```go
for i := range out.Addresses {
	ip := out.Addresses[i]
}
```

Comment (teaguecole) [reply pkg/cloud/services/ec2/eips.go]: Yeah, I agree. Will make that change.

Comment (detiber) [reply pkg/cloud/services/ec2/eips.go]: Thanks, do you mind updating the other instances as well?

Comment (teaguecole) [reply pkg/cloud/services/ec2/eips.go]: All done. I think I got everything.
