### PR TITLE
Fix lastAppliedTags annotations naming

### LINKED ISSUE #3863: Invalid annotation key for sigs.k8s.io/cluster-api-provider-aws/v2-last-applied-tags
/kind bug

**What steps did you take and what happened:**
Upgraded to v2.0.0 with clusterctl

Looked into cluster-api-provider-aws logs. There were issues like:
`Invalid value: \"sigs.k8s.io/cluster-api-provider-aws/v2-last-applied-tags\" a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')`

**Anything else you would like to add:**
The issue is probably caused by two slashes appearing in the new annotations instead of one.
This may be appearing when using `additionalTags`.

* controllers/awsmachine_tags.go - `TagsLastAppliedAnnotation = "sigs.k8s.io/cluster-api-provider-aws/v2-last-applied-tags"`
* pkg/cloud/services/ec2/launchtemplate.go - `TagsLastAppliedAnnotation = "sigs.k8s.io/cluster-api-provider-aws/v2-last-applied-tags"`
* controllers/awsmachine_security_groups.go  - `SecurityGroupsLastAppliedAnnotation = "sigs.k8s.io/cluster-api-provider-aws/v2-last-applied-security-groups"`

**Environment:**

- Cluster-api-provider-aws version: 2.00
- Kubernetes version: (use `kubectl version`):  1.23

### PR DESCRIPTION
**Pull request by dntosas**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Valid annotation keys have two segments: an optional prefix and name, separated by a slash (/). 
In this commit, we fix the ones that include two slashes that couldn't be parsed as valid structs.

**Which issue(s) this PR fixes**:
Fixes #3863

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: controllers/awsmachine_security_groups.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ const (
 	// the AdditionalSecurityGroups in the Machine Provider Config.
 	// See https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
 	// for annotation formatting rules.
-	SecurityGroupsLastAppliedAnnotation = "sigs.k8s.io/cluster-api-provider-aws/v2-last-applied-security-groups"
+	SecurityGroupsLastAppliedAnnotation = "sigs.k8s.io/cluster-api-provider-aws-v2-last-applied-security-groups"
```
Comment (sbueringer) [inline controllers/awsmachine_security_groups.go:34]: Ah damn. I think adding the `/v2` was just a mistake when search/replacing to adding v2.

I think we have to rollback to the annotation we had before my change

Comment (sbueringer) [reply controllers/awsmachine_security_groups.go:34]: Thx for catching that!

Comment (dntosas) [reply controllers/awsmachine_security_groups.go]: thnx for the clarification @sbueringer ! pushed changes to revert annotations

**Comment by sbueringer** [comment]
Thank you very much!

/lgtm

cc @richardcase I don't really have the context, but I would guess this broke a bunch of stuff with v2.0.0.

**Comment by richardcase** [comment]
Thanks @dntosas and @sbueringer.  Will run tests and then we can get a patch release out.

**Comment by dntosas** [comment]
> Thanks @dntosas and @sbueringer. Will run tests and then we can get a patch release out.

niice 🙏

**Comment by richardcase** [comment]
Until the e2e pass:

/hold

**Comment by richardcase** [comment]
Non-eks e2e have [passed](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3867/pull-cluster-api-provider-aws-e2e/1594662253192286208)

**Comment by dntosas** [comment]
@richardcase i think we need to re-run EKS tests

**Comment by richardcase** [comment]
> @richardcase i think we need to re-run EKS tests

They've been stuck in pending for a while. Let me look at testgrid.....

**Comment by sbueringer** [comment]
Failed now (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3867/pull-cluster-api-provider-aws-e2e-eks/1594777679654031360)

I'll trigger a retry to give you more data (also probably unrelated (?))

/test pull-cluster-api-provider-aws-e2e-eks

**Comment by Ankitasw** [comment]
I think the same test is failing again, not sure how this affects ipv6 test.

**Comment by richardcase** [comment]
We've been seeing failures in the e2e since the weekend 😤 it's on the list of things to look at today (I'm also adding some extra logging to the e2e)

**Comment by Ankitasw** [comment]
@richardcase is it safe to merge this? As Non EKS tests are passing.

**Comment by dntosas** [comment]
i think this better to be merged and patch released quickly as it breaks AWSMachines reconciliation. 

people upgraded to v2.0.0 will need this for sure ^^ wdyt?

**Comment by richardcase** [comment]
@dntosas - just to be 100% clear, this completely breaks the `AWSMachine` reconciliation?

**Comment by dntosas** [comment]
> @dntosas - just to be 100% clear, this completely breaks the `AWSMachine` reconciliation?

Yeap @richardcase

**Comment by richardcase** [comment]
After discussion on slack with various parties and among the CAPA maintainers, we have decided to merge and do a patch release even though the EKS e2e test are failing. This a risk but the reasons are:

- Without this change `AWSMachine` reconciliation is completely broken for v2.0.0
- EKS e2e have been flakey before the 2.0.0 release
- This is the only change in the release.
- Non-eks e2e tests are passing

We will then aim to get the EKS e2e stable again as a matter of priority.

/override pull-cluster-api-provider-aws-e2e-eks
/approve

**Comment by sbueringer** [comment]
@richardcase + others who might be interested

> Without this change AWSMachine reconciliation is completely broken for v2.0.0

Could be an interesting follow-up why this wasn't caught by CI.

**Comment by richardcase** [comment]
@sbueringer - i entirely agree. We've started those discussions as to how this wasn't picked up. Strangely, all the e2e were passing. 

For me, i am going to solely focus on e2e testing for the next release.
