### PR TITLE
Fix EKS encryption config value comparisons

### LINKED ISSUE #2908: AWSManagedControlPlane EKS  encryption config incorrectly reconciles
/kind bug

AWSManagedControlPlane for EKS encryption config incorrectly reconciles and attempts to disable encryption config for a new cluster without any changes to the spec. This causes a new cluster to fail further reconcile steps and blocks building a new cluster with encryption config enabled.

**What steps did you take and what happened:**

- Create a new cluster with an encryption config

```yaml
encryptionConfig:
  provider: <kms key alias arn>
  resources:
    - "secrets"
```

- Verify in the EKS Console encryption is enabled
Screen Shot 2021-11-03 at 12 34 32 pm
 
`clusterctl` shows CAPA failed to reconcile control plane

```
❯ clusterctl describe cluster lab1-cluster                             
NAME                                                        READY  SEVERITY  REASON                               SINCE  MESSAGE         
/lab1-cluster                                               False  Error     EKSControlPlaneReconciliationFailed  97m    4 of 7 completed
└─ControlPlane - AWSManagedControlPlane/lab1-control-plane  False  Error     EKSControlPlaneReconciliationFailed  97m    4 of 7 completed
```

CAPA logs show it is trying to remove encryption config, although no config has changed and it has not been removed from the spec.

```
I1103 01:26:25.619043       1 cluster.go:496]  "msg"="reconciling encryption configuration"  
E1103 01:26:25.622744       1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane clusters/lab1-control-plane: failed reconciling eks encryption config: failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled" "name"="lab1-control-plane" "namespace"="clusters" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="AWSManagedControlPlane" 
```

Verify encropytiobn config is indeed on the spec
```json
❯ k get -o json awsmcp lab1-control-plane | jq '.spec.encryptionConfig'
{
  "provider": "<kms key alias arn>",
  "resources": [
    "secrets"
  ]
}
```

**What did you expect to happen:**

The control plane to reconcile correctly and be in an OK state. 

**Anything else you would like to add:**

I haven't been able to find the source of the bug, but it's clear that the encryption reconcile is not correctly comparing current and "desired state" as unchanged. https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4274a5ab5c9dc391045840d6e45e17fe0cbab3dc/pkg/cloud/services/eks/cluster.go#L505

I wouldn't be surprised if it's a pointer compare bug that https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2540 would address, however looks to be frozen. 

Additionally, the encryption config isn't tested yet https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2508

**Environment:**

- Cluster-api-provider-aws version: 1.0.0
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`):  N/A

### PR DESCRIPTION
**Pull request by jon-fearer**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR addresses a couple of issues that are preventing EKS-managed clusters from fully reconciling when encryption is enabled:
- Update EncryptionConfig.Provider comparison to dereference pointers and compare KeyARN
- Fix a couple of other equality comparisons that were flipped (checking true vs false)
- Add assertions to TestCompareSlices (`g.Expect(...)` vs `g.Expect(...).To(...)`)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2908 

**Special notes for your reviewer**:
This PR does not address the refactor work [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2540), but I am happy to add that if it's still wanted.

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [X] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix EKS encryption configuration comparison issues that blocked building a new cluster with encryption enabled
```

### CODE REVIEW

File: pkg/cloud/services/eks/cluster.go [hunk 1]
```diff
@@ -707,10 +707,10 @@ func compareEncryptionConfig(updatedEncryptionConfig, existingEncryptionConfig [
 		return false
 	}
 	for index, encryptionConfig := range updatedEncryptionConfig {
-		if encryptionConfig.Provider != existingEncryptionConfig[index].Provider {
+		if *encryptionConfig.Provider.KeyArn != *existingEncryptionConfig[index].Provider.KeyArn {
```
Comment (sedefsavas) [inline pkg/cloud/services/eks/cluster.go:710]: Do we need nil check here?

Comment (jon-fearer) [reply pkg/cloud/services/eks/cluster.go:710]: Yes, good catch

Comment (jon-fearer) [reply pkg/cloud/services/eks/cluster.go]: Updated

File: pkg/cloud/services/eks/cluster.go [hunk 2]
```diff
@@ -707,12 +707,19 @@ func compareEncryptionConfig(updatedEncryptionConfig, existingEncryptionConfig [
...
+		if !cmp.Equals(encryptionConfig.Resources, existingEncryptionConfig[index].Resources) {
 			return false
 		}
 	}
 	return true
 }
+
+func getKeyArn(encryptionConfig *eks.EncryptionConfig) string {
+	if encryptionConfig.Provider != nil && encryptionConfig.Provider.KeyArn != nil {
+		return *encryptionConfig.Provider.KeyArn
```
Comment (sedefsavas) [inline pkg/cloud/services/eks/cluster.go:722]: `aws.StringValue` deals with nil case as well. Since KeyArn sdk field, better to use SDK dereferencing.

Comment (jon-fearer) [reply pkg/cloud/services/eks/cluster.go:722]: Ah nice, I didn't know that handled nils. Will update

Comment (jon-fearer) [reply pkg/cloud/services/eks/cluster.go]: Updated. I left the nil check on `Provider` in there as I believe that could still be a nil pointer.
