### PR TITLE
fix: eks encryption logic fix

### LINKED ISSUE #3092: Specifying KMS encryption results in envelope encryption being set, but controller is trying to back it out
/kind bug

**What steps did you take and what happened:**
Built a new cluster with CAPA using KMS envelope encryption. Encryption was successfully enabled (checked via the aws console), but the controller is attempting to back that out per the console logs:
```
E0121 19:23:55.475711       1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane default/rterrill-test-1: failed reconciling eks encryption config: failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled" "name"="rterrill-test-1" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="AWSManagedControlPlane"
```

KMS config setting:
```
  encryptionConfig:
    provider: "arn:aws:kms:us-west-2:REDACTED:key/REDACTED"
    resources:
    - "secrets"
```
**What did you expect to happen:**
KMS encryption should be enabled and the controller should show success.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: cluster-api-aws-controller:v1.2.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The logic for when to update the EKS encryption had issues. This
refactors the logic to be more explicit.

Also updated the docs to say that the KMS key ARN needs to be used and
not the alias ARN.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3092 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Update to EKS encryption logic to stop it reporting a chnage when one hasn't occured.
```

### CODE REVIEW

File: pkg/cloud/services/eks/cluster.go [hunk 1]
```diff
@@ -523,22 +523,23 @@ func (s *Service) reconcileEKSEncryptionConfig(currentClusterConfig []*eks.Encry
...
-	default:
-		record.Warnf(s.scope.ControlPlane, "FailedUpdateEKSControlPlane", "failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled")
-		return errors.Errorf("failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled")
+
+		return nil
 	}
 
-	return nil
+	record.Warnf(s.scope.ControlPlane, "FailedUpdateEKSControlPlane", "failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled")
+	return errors.Errorf("failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled")
```
Comment (sedefsavas) [inline pkg/cloud/services/eks/cluster.go:542]: Once set, modifying or deleting the config is not allowed in the webhook, so not really needed.

Comment (sedefsavas) [reply pkg/cloud/services/eks/cluster.go:542]: @richardcase What was the fix here? I could not see.

**Comment by richardcase** [comment]
Changing to WIP as i will fix #3096 as part of this.

File: pkg/cloud/services/eks/cluster.go (hunk 1 above)
Comment (richardcase) [reply pkg/cloud/services/eks/cluster.go:542]: Agreed it should never get here....although it was with the issue that this PR relates to. I'd be tempted to keep it as it would be good to get an error .

**Comment by rayterrill** [comment]
More comments in Slack, but I built this and deployed it to my cluster - so far I'm able to build a cluster with no KMS error messages relating to trying to pull the encryption back off. Looking good @richardcase! Thank you!

**Comment by richardcase** [comment]
@rayterrill - thanks for confirming this fixes your issue. I'll do #3096 as a seperate PR after some thought so that we get this in.
