### PR TITLE
fixes vpc creation

### LINKED ISSUE #783: invalid vpc attributes
/kind bug

When creating a new vpc I'm getting:

`InvalidParameterCombination: Fields for multiple attribute types specified: enableDnsHostnames, enableDnsSupport`

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR fixes #783 

```release-note
NONE
```

### CODE REVIEW

File: pkg/cloud/aws/services/ec2/vpc_test.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func TestReconcileVPC(t *testing.T) {
 					}, nil)
 
 				m.ModifyVpcAttribute(gomock.AssignableToTypeOf(&ec2.ModifyVpcAttributeInput{})).Return(&ec2.ModifyVpcAttributeOutput{}, nil)
```
Comment (vincepri) [inline pkg/cloud/aws/services/ec2/vpc_test.go]: You should be able to use `.Times(2)` to avoid repetition

File: pkg/cloud/aws/services/ec2/vpc.go [hunk 2]
```diff
@@ -89,10 +89,19 @@ func (s *Service) createVPC() (*v1alpha1.VPCSpec, error) {
...
-		EnableDnsSupport:   &ec2.AttributeBooleanValue{Value: aws.Bool(true)},
+	}
+
+	if _, err = s.scope.EC2.ModifyVpcAttribute(attrInput); err != nil {
+		return nil, errors.Wrap(err, "failed to set vpc attributes")
+	}
+
+	attrInput = &ec2.ModifyVpcAttributeInput{
+		VpcId:            out.Vpc.VpcId,
+		EnableDnsSupport: &ec2.AttributeBooleanValue{Value: aws.Bool(true)},
```
Comment (vincepri) [inline pkg/cloud/aws/services/ec2/vpc.go]: Seems we can avoid this call during creation given that it defaults to `true` https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html

Comment (chuckha) [reply pkg/cloud/aws/services/ec2/vpc.go]: Yep, it defaults to true, but I wanted to keep the same behavior of the existing code

File: pkg/cloud/aws/services/ec2/vpc_test.go (hunk 1 above)
Comment (chuckha) [reply pkg/cloud/aws/services/ec2/vpc_test.go]: ah, ok

**Comment by vincepri** [comment]
Generally LGTM, I'd just add a little more details to the commit message and should be good to merge 🎉

**Comment by chuckha** [comment]
@vincepri fixed the commit message. that was fair feedback haha
