### PR TITLE
:bug: Delete cloud provider provisioned load balancers and security groups

### LINKED ISSUE #773: Cluster Delete fails when cloud-provider managed resources exist
/kind bug

**What steps did you take and what happened:**
- Create a cluster
- Deploy a Service of type LoadBalancer
- Delete the cluster

Deletion of Cluster fails with: 
```
Network vpc-0c8cb6be01c354cc6 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway
```

**What did you expect to happen:**
Cluster to be deleted

**Anything else you would like to add:**
Since the cloud-provider managed resources are created with known tagging (kubernetes.io/cluster/<name or id>=owned) and manage a limited set of resources, we can clean those up.

Some outstanding questions:
- Should we attempt to clean up all cloud-provider managed resources, or just ones that block cluster deletion?
  - Deletion of EBS volumes for example could result in unexpected data loss for users
  - Load balancers should be safe to delete without repurcussions
  - Any other resources to look out for?

**Environment:**
- Cluster-api-provider-aws version: v0.2.1
- Kubernetes version: (use `kubectl version`): v1.13.5
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

### PR DESCRIPTION
**Pull request by liztio**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #773

### CODE REVIEW

File: pkg/cloud/services/elb/loadbalancer_test.go [hunk 1]
```diff
@@ -1,101 +0,0 @@
...
-
-				m.DescribeLoadBalancerAttributes(gomock.Any()).Return(&elb.DescribeLoadBalancerAttributesOutput{
-					LoadBalancerAttributes: &elb.LoadBalancerAttributes{},
-				}, nil)
-
-				m.DeleteLoadBalancer(&elb.DeleteLoadBalancerInput{
-					LoadBalancerName: aws.String("test-cluster-apiserver"),
-				})
-
-				m.DescribeLoadBalancers(gomock.Any()).Return(&elb.DescribeLoadBalancersOutput{}, nil)
```
Comment (liztio) [inline pkg/cloud/services/elb/loadbalancer_test.go]: This was going to need to be completely reworked to handle the new logic, I decided the test was too brittle to bother with.

File: pkg/cloud/services/ec2/securitygroups.go [hunk 2]
```diff
@@ -160,22 +160,62 @@ func (s *Service) deleteSecurityGroups() error {
...
+		GroupId: aws.String(sg.ID),
+	}
+
+	if _, err := s.scope.EC2.DeleteSecurityGroup(input); awserrors.IsIgnorableSecurityGroupError(err) != nil {
+		record.Warnf(s.scope.AWSCluster, "FailedDeleteSecurityGroup", "Failed to delete %s SecurityGroup %q: %v", typ, sg.ID, err)
+		return errors.Wrapf(err, "failed to delete security group %q", sg.ID)
+	}
+
+	record.Eventf(s.scope.AWSCluster, "SuccessfulDeleteSecurityGroup", "Deleted %s SecurityGroup %q", typ, sg.ID)
+	s.scope.V(2).Info("Deleted security group security group", "security-group-id", sg.ID, "kind", typ)
```
Comment (ncdc) [inline pkg/cloud/services/ec2/securitygroups.go]:
```suggestion
	s.scope.V(2).Info("Deleted security group", "security-group-id", sg.ID, "kind", typ)
```

File: pkg/cloud/services/elb/loadbalancer.go [hunk 3]
```diff
@@ -321,6 +331,69 @@ func (s *Service) deleteClassicELBAndWait(name string) error {
...
+			}
+		}
+		return true
+	})
+
+	if err != nil {
+		if aerr, ok := err.(awserr.Error); ok {
+			switch aerr.Code() {
+			case elb.ErrCodeDependencyThrottleException:
+				return nil, errors.Wrap(err, "too many requests made to the resource tag group service")
```
Comment (ncdc) [inline pkg/cloud/services/elb/loadbalancer.go]: If we don't do this wrapping, what does the error look like in the log? Is it worth the logic to check for this code?

File: pkg/cloud/services/elb/loadbalancer.go [hunk 4]
```diff
@@ -321,6 +331,69 @@ func (s *Service) deleteClassicELBAndWait(name string) error {
...
+			default:
+				return nil, errors.Wrap(err, "unexpected aws error")
```
Comment (ncdc) [inline pkg/cloud/services/elb/loadbalancer.go]: Should we make this more informative, like what's on line 372?

File: pkg/cloud/services/elb/loadbalancer.go [hunk 5]
```diff
@@ -89,19 +93,25 @@ func (s *Service) GetAPIServerDNSName() (string, error) {
...
-	if _, err := s.describeClassicELB(elbName); err != nil {
-		if IsNotFound(err) {
-			return nil
-		}
+	elbs, err := s.listOwnedELBs()
+	if err != nil {
 		return err
 	}
 
-	if err := s.deleteClassicELBAndWait(elbName); err != nil {
```
Comment (ncdc) [inline pkg/cloud/services/elb/loadbalancer.go]: Can we remove the entire `deleteClassicELBAndWait` function - I don't think it's used anywhere else?

File: pkg/cloud/services/elb/loadbalancer.go (hunk 3 above)
Comment (liztio) [reply pkg/cloud/services/elb/loadbalancer.go]: Honestly I just did this because `describeClassicELB` did. I'm happy to yank it out.

File: pkg/cloud/services/ec2/securitygroups.go [hunk 6]
```diff
@@ -160,22 +160,62 @@ func (s *Service) deleteSecurityGroups() error {
...
-		}
+	clusterGroups, err := s.describeClusterOwnedSecurityGroups()
+	if err != nil {
+		return err
+	}
 
-		record.Eventf(s.scope.AWSCluster, "SuccessfulDeleteSecurityGroup", "Deleted managed SecurityGroup %q", sg.ID)
-		s.scope.V(2).Info("Deleted security group security group", "security-group-id", sg.ID)
+	for _, sg := range clusterGroups {
+		s.deleteSecurityGroup(&sg, "cluster managed")
```
Comment (vincepri) [inline pkg/cloud/services/ec2/securitygroups.go]: We should check and aggregate these errors

File: pkg/cloud/services/elb/loadbalancer.go [hunk 7]
```diff
@@ -19,18 +19,22 @@ package elb
...
 	"github.com/aws/aws-sdk-go/service/elb"
+	rgapi "github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi"
 	"github.com/pkg/errors"
 	infrav1 "sigs.k8s.io/cluster-api-provider-aws/api/v1alpha2"
 	"sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/awserrors"
 	"sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/converters"
 	"sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/wait"
 )
 
+const elbResourceType = "elasticloadbalancing:loadbalancer"
```
Comment (vincepri) [inline pkg/cloud/services/elb/loadbalancer.go]: Can we add a comment describing this constant?
