### PR TITLE
🐛 Fix deleting AWSCluster when VPC doesn't exist

### LINKED ISSUE #1375: Cluster deletion fails when VpcID is an empty string
/kind bug

This seems similar to the v1alpha1 issue here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/943.

If a cluster cannot be created due to hitting a VPC limit, the VPC ID field will remain blank and will then block deletion of the cluster. The workaround appears to be dropping the finalizer. 

```
E1125 13:52:24.440431       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster 10fac61f2591ca284ba10e0e4375c89534ae7a60/e2e-lcm-20191125-ilap: failed to create new vpc: failed to create vpc: VpcLimitExceeded: The maximum number of VPCs has been reached.\n\tstatus code: 400, request id: ff48270e-fa1d-4324-9e71-3c416d27ea31"  "controller"="awscluster" "request"={"Namespace":"10fac61f2591ca284ba10e0e4375c89534ae7a60","Name":"e2e-lcm-20191125-ilap"}
E1125 13:56:19.071775       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster 10fac61f2591ca284ba10e0e4375c89534ae7a60/e2e-lcm-20191125-ilap: failed to describe cluster-owned security groups in vpc \"\": InvalidParameterValue: vpc-id\n\tstatus code: 400, request id: 1c0a5745-bcf8-4fba-a35f-9e9398c12bf2"  "controller"="awscluster" "request"={"Namespace":"10fac61f2591ca284ba10e0e4375c89534ae7a60","Name":"e2e-lcm-20191125-ilap"}
```

Discussion here: https://kubernetes.slack.com/archives/CD6U2V71N/p1574704015458800

**Environment:**

- Cluster-api-provider-aws version: 0.4.4
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by aaroniscode**
**What this PR does / why we need it**:
If a VPC cannot be created for an AWSCluster object (like when a VPC limit is reached), the controller will fail to delete the AWSCluster as certain AWS calls fail without a VPC id.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1375

### CODE REVIEW

File: controllers/awscluster_controller.go [hunk 1]
```diff
@@ -104,26 +104,38 @@ func (r *AWSClusterReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reter
...
+	}
+
+	// Cluster is deleted so remove the finalizer.
+	clusterScope.AWSCluster.Finalizers = util.Filter(clusterScope.AWSCluster.Finalizers, infrav1.ClusterFinalizer)
+
+	return reconcile.Result{}, nil
+}
+
+func deleteClusterResources(clusterScope *scope.ClusterScope) error {
+	if clusterScope.VPC().ID == "" {
```
Comment (detiber) [inline controllers/awscluster_controller.go]: This should probably attempt to lookup the VPC (using name and labels) prior to short-circuiting here, otherwise we could potentially orphan a created VPC where persisting the ID back to the AWSCluster resource failed for some reason.

Comment (aaroniscode) [reply controllers/awscluster_controller.go]: @detiber thanks for the review and pointing that out!  I re-did the entire fix.

**Comment by aaroniscode** [comment]
Took a deeper look at the delete process and code and found that there is a VPC lookup process and 
 it currently takes place in `deleteVPC`. I took the code and moved it up earlier in the process, in `DeleteNetwork` as we can't delete the network components if the VPC doesn't exist. This is also where the error was occurring.

**Comment by ncdc** [comment]
LGTM. Asking @randomvariable to look too.
