### PR TITLE
Use Wrapf for errors only when err is not nil

### LINKED ISSUE #3179: Errors missed out due to wrong usage of error.Wrapf()
/kind bug

**What steps did you take and what happened:**
While writing the tests for `pkg/cloud/services/natgateway` package, I encountered [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/natgateways.go#L290) line of code. Here the expectation was to return an error if `len(out.NatGateways)` is zero but actually it will return error as nil. This is because `error.Wrapf(err, args…)` returns nil if err is nil. 
Due to this bug, the method `WaitForWithRetryable()` will keep retrying and then `deleteNatGateway()` will timeout. 

On further investigation, I found similar instances in other places too.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/fargate.go#L107
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/nodegroup.go#L487

**What did you expect to happen:**
We should use wrap errors with error.Wrapf() only if error is non-nil.

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:
This PR checks if a error is present already and then only makes use of the errors.Wrapf functionality else it returns a custom error. This should prevent unnecessary timeouts during implementation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3179 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by shivi28** [comment]
Thanks @DiptoChakrabarty for the PR 🎉 . Have added some suggestions, otherwise it's LGTM

File: pkg/cloud/services/network/natgateways.go [hunk 1]
```diff
@@ -287,7 +287,11 @@ func (s *Service) deleteNatGateway(id string) error {
 		}
 
 		if len(out.NatGateways) == 0 {
-			return false, errors.Wrapf(err, "no NAT gateway returned for id %q", id)
+			if err != nil {
+				return false, errors.Wrapf(err, "no NAT gateway returned for id %q", id)
+			}
+			errmsg := fmt.Sprintf("no NAT gateway returned for id %q", id)
+			return false, errors.New(errmsg)
```
Comment (Ankitasw) [inline pkg/cloud/services/network/natgateways.go:294]: nit: We can directly use `fmt.Sprintf("no NAT gateway returned for id %q", id)` as an argument to `errors.New()` without introducing new variable, wdyt?

File: pkg/cloud/tags/tags.go [hunk 2]
```diff
@@ -115,7 +115,11 @@ func WithEC2(ec2client ec2iface.EC2API) BuilderOption {
 			}
 
 			_, err := ec2client.CreateTags(createTagsInput)
-			return errors.Wrapf(err, "failed to tag resource %q in cluster %q", params.ResourceID, params.ClusterName)
+			if err != nil {
+				return errors.Wrapf(err, "failed to tag resource %q in cluster %q", params.ResourceID, params.ClusterName)
+			}
+			errmsg := fmt.Sprintf("failed to tag resource %q in cluster %q", params.ResourceID, params.ClusterName)
+			return errors.Errorf(errmsg)
```
Comment (Ankitasw) [inline pkg/cloud/tags/tags.go:122]: nit: Same comment as above

**Comment by Ankitasw** [comment]
Hi @DiptoChakrabarty , thanks for the PR.
I request you to run `make test` locally so that if your changes affect any existing test cases, you can modify them, or take a look if something went wrong with the implementation.

File: pkg/cloud/tags/tags.go (hunk 2 above)
Comment (pydctw) [inline pkg/cloud/tags/tags.go:122]: We should return nil when err == nil, meaning CreateTags are successful. This is why multiple tests are failing.

File: pkg/cloud/services/eks/fargate.go [hunk 3]
```diff
@@ -104,7 +104,10 @@ func (s *FargateService) reconcileFargateProfile() (requeue bool, err error) {
 		tagKey := infrav1.ClusterAWSCloudProviderTagKey(s.scope.ClusterName())
 		ownedTag := profile.Tags[tagKey]
 		if ownedTag == nil {
-			return false, errors.Wrapf(err, "owned tag not found for this cluster")
+			if err != nil {
```
[the remark this answers is not in the document]
Comment (DiptoChakrabarty) [reply pkg/cloud/services/eks/fargate.go]: yes done

File: pkg/cloud/services/eks/nodegroup.go [hunk 4]
```diff
@@ -484,7 +484,11 @@ func (s *NodegroupService) reconcileNodegroup() error {
 		tagKey := infrav1.ClusterAWSCloudProviderTagKey(s.scope.ClusterName())
 		ownedTag := ng.Tags[tagKey]
 		if ownedTag == nil {
-			return errors.Wrapf(err, "owner of %s mismatch: %s", eksNodegroupName, s.scope.ClusterName())
+			if err != nil {
+				return errors.Wrapf(err, "owner of %s mismatch: %s", eksNodegroupName, s.scope.ClusterName())
+			}
+			errmsg := fmt.Sprintf("owner of %s mismatch: %s", eksNodegroupName, s.scope.ClusterName())
```
[the remark this answers is not in the document]
Comment (DiptoChakrabarty) [reply pkg/cloud/services/eks/nodegroup.go]: modified

File: pkg/cloud/services/network/natgateways.go (hunk 1 above)
Comment (DiptoChakrabarty) [reply pkg/cloud/services/network/natgateways.go]: yes done them that way

File: pkg/cloud/tags/tags.go (hunk 2 above)
Comment (DiptoChakrabarty) [reply pkg/cloud/tags/tags.go]: I reverted this back to the way it is in upstream since no error will return nil by errors.Wrapf and it was causing tests to fail

Comment (DiptoChakrabarty) [reply pkg/cloud/tags/tags.go]: Thanks @pydctw I reverted it back to the original way(since wrapf will return nil if err is nil) , the failing tests failed once but passed after squash

File: pkg/cloud/services/network/natgateways.go [hunk 5]
```diff
@@ -287,7 +287,10 @@ func (s *Service) deleteNatGateway(id string) error {
 		}
 
 		if len(out.NatGateways) == 0 {
-			return false, errors.Wrapf(err, "no NAT gateway returned for id %q", id)
+			if err != nil {
```
Comment (shivi28) [inline pkg/cloud/services/network/natgateways.go:290]: nit: remove this err check, as we are already checking it at [Line285](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3186/files#diff-23c065949155c8a08cd81009d31c08a2d86909abe59c908a374d11c9a641281eL285)
```
if err != nil {
   return false, errors.Wrapf(err, "no NAT gateway returned for id %q", id)
}
```
/lgtm
