### PR TITLE
🐛 fix(nodegroup): add nil pointer check for nodegroup version

### LINKED ISSUE #5018: Issue: Panic Due to Invalid Memory Address or Nil Pointer Dereference in AWS Managed Machine Pool Reconciliation
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Description
We are experiencing a panic due to an invalid memory address or nil pointer dereference during the reconciliation of the AWS Managed Machine Pool. The panic occurs while the system attempts to reconcile the machine pool for AWSManagedMachinePool. This issue causes the reconciliation process to fail, impacting the cluster's ability to manage its resources effectively.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Logs:
---
I0613 02:33:54.500593       1 reconcile.go:90] "Reconciled aws-iam-authenticator configuration" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="[REDACTED]"
I0613 02:36:03.593823       1 awsmanagedcluster_controller.go:114] "Successfully reconciled AWSManagedCluster" controller="awsmanagedcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedCluster" AWSManagedCluster="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" cluster="[REDACTED]" controlPlane="[REDACTED]"
I0613 02:36:03.594253       1 awsmanagedcontrolplane_controller.go:304] "Reconciling AWSManagedControlPlane" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:03.666950       1 subnets.go:50] "Reconciling subnets" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:04.016766       1 roles.go:85] "using eks control plane role" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]" role-name="eks-controlplane.cluster-api-provider-aws.sigs.k8s.io"
I0613 02:36:04.990927       1 securitygroup.go:34] "Reconciling EKS security groups" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]" cluster-name="[REDACTED]"
I0613 02:36:05.225873       1 cluster.go:541] "reconciling encryption configuration" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:05.225961       1 addons.go:34] "Reconciling EKS addons" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:05.309970       1 addons.go:105] "no eks addons installed in cluster" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="[REDACTED]"
I0613 02:36:05.310046       1 addons.go:57] "no addons installed and no addons to install, no action needed" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:05.310096       1 identity_provider.go:33] "reconciling oidc identity provider" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:05.310146       1 identity_provider.go:35] "no oidc provider config, skipping reconcile" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:05.310207       1 cni.go:48] "Reconciling aws-node DaemonSet in cluster" controller="awsmanagedcontrolplane

---

controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:36:05.310732       1 cni.go:230] "Ensuring all resources for AWS VPC CNI in cluster are deleted" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 02:42:58.754230       1 controller.go:329] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool capi-managed-cluster/[REDACTED]: failed to wait for nodegroup to be active: failed to wait for EKS nodegroup \"capi-managed-cluster_[REDACTED]\": ResourceNotReady: failed waiting for successful resource state" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]"
E0613 02:42:59.808460       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 618 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2eeafc0?, 0x5ba4810})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:75 +0x85
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:108 +0xb2
panic({0x2eeafc0?, 0x5ba4810?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/eks.(*NodegroupService).reconcileNodegroupVersion(0xc00283b740, 0xc0013082d0)
	/workspace/pkg/cloud/services/eks/nodegroup.go:336 +0xbd
sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/eks.(*NodegroupService).reconcileNodegroup(0xc00283b740, {0x3ca2570, 0xc00283fc80})
	/workspace/pkg/cloud/services/eks/nodegroup.go:558 +0x711
sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/eks.(*NodegroupService).ReconcilePool(0xc00283b740, {0x3ca2570, 0xc00283fc80})
	/workspace/pkg/cloud/services/eks/eks.go:109 +0x11a
sigs.k8s.io/cluster-api-provider-aws/v2/exp/controllers.(*AWSManagedMachinePoolReconciler).reconcileNormal(0xc0010d0f00, {0x3ca2570, 0xc00283fc80}, 0xc0027af9a0, {0x3ccf070, 0xc002289200})
	/workspace/exp/controllers/awsmanagedmachinepool_controller.go:239 +0x4da
sigs.k8s.io/cluster-api-provider-aws/v2/exp/controllers.(*AWSManagedMachinePoolReconciler).Reconcile(0xc0010d0f00, {0x3ca2570, 0xc00283fc80}, {{{0xc00150dc50?, 0x0?}, {0xc00150dc98?, 0xc002833d08?}}})
	/workspace/exp/controllers/awsmanagedmachinepool_controller.go:192 +0x8b7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3ca6c40?, {0x3ca2570?, 0xc00283fc80?}, {{{0xc00150dc50?, 0xb?}, {0xc00150dc98?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0010fc1e0, {0x3ca25a8, 0xc000d72c30}, {0x309f620?, 0xc0022a0900?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:316 +0x3cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0010fc1e0, {0x3ca25a8, 0xc000d72c30})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266 +0x1af
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 273
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:223 +0x565
E0613 02:42:59.808540       1 controller.go:329] "Reconciler error" err="panic: runtime error: invalid memory address or nil pointer dereference [recovered]" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="[REDACTED]"
I0613 02:42:59.809436       1 awsmanagedmachinepool_controller.go:200] "Reconciling AWSManagedMachinePool"
I0613 02:42:59.809607       1 launchtemplate.go:73] "checking for existing launch template"
E0613 02:43:00.223847       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 618 [running]:

---

**Environment:**

- Cluster-api-provider-aws version: 2.5.0
- Kubernetes version: (use `kubectl version`): 1.25.5, local kubernetes   
- kubernetes version (tries to create the eks), 1.25.5, ami-0333068ec6744ace7
- OS (e.g. from `/etc/os-release`):   
- ami 
-

### PR DESCRIPTION
**Pull request by nueavv**
Added a check to ensure that the nodegroup version is not nil before dereferencing it. This prevents potential runtime panics due to nil pointer dereference.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR adds a nil pointer check for the nodegroup version in the `reconcileNodegroupVersion` function. This prevents potential runtime panics caused by dereferencing a nil pointer when the nodegroup version is not set.

**Which issue(s) this PR fixes**:
Fixes #5018

**Special notes for your reviewer**:

This change is essential to ensure the stability of the `reconcileNodegroupVersion` function by preventing nil pointer dereference issues.

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix nil pointer dereference in reconcileNodegroupVersion by adding a check for nodegroup version.
```

### CODE REVIEW

**Comment by nueavv** [comment]
I have built and tested the updated code, and it seems that the panic no longer occurs. Here are the updated logs.
It seems the panic issue has been resolved

```plaintext
I0613 04:01:44.064508       1 reconcile.go:39] "Reconciling kube-proxy DaemonSet in cluster" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="a4ce3943-5cdb-4467-aba9-18a759fd6cb2" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
I0613 04:01:44.065051       1 reconcile.go:39] "Reconciling aws-iam-authenticator configuration" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="a4ce3943-5cdb-4467-aba9-18a759fd6cb2" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="capi-managed-cluster/[REDACTED]"
E0613 04:01:44.386103       1 controller.go:329] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool capi-managed-cluster/[REDACTED]: failed to reconcile nodegroup version: nodegroup version is nil" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="3e0c724f-236b-4262-9c06-e22f83b0eacd"
I0613 04:01:44.386891       1 awsmanagedmachinepool_controller.go:200] "Reconciling AWSManagedMachinePool"
I0613 04:01:44.387068       1 launchtemplate.go:73] "checking for existing launch template"
I0613 04:01:44.439150       1 reconcile.go:90] "Reconciled aws-iam-authenticator configuration" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="a4ce3943-5cdb-4467-aba9-18a759fd6cb2" awsManagedControlPlane="capi-managed-cluster/[REDACTED]" cluster="[REDACTED]"
E0613 04:01:44.858183       1 controller.go:329] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool capi-managed-cluster/[REDACTED]: failed to reconcile nodegroup version: nodegroup version is nil" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="9bec8c74-79d0-4b39-bd40-607a5d899630"
I0613 04:01:44.859110       1 awsmanagedmachinepool_controller.go:200] "Reconciling AWSManagedMachinePool"
I0613 04:01:44.859320       1 launchtemplate.go:73] "checking for existing launch template"
E0613 04:01:45.297763       1 controller.go:329] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool capi-managed-cluster/[REDACTED]: failed to reconcile nodegroup version: nodegroup version is nil" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="91a7cb58-d6f8-4e8f-aa06-62acce826b74"
I0613 04:01:45.298635       1 awsmanagedmachinepool_controller.go:200] "Reconciling AWSManagedMachinePool"
I0613 04:01:45.298821       1 launchtemplate.go:73] "checking for existing launch template"
E0613 04:01:45.743834       1 controller.go:329] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool capi-managed-cluster/[REDACTED]: failed to reconcile nodegroup version: nodegroup version is nil" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="ef2c12c6-5c2b-4553-a62e-f69ce561d6d9"
I0613 04:01:45.744691       1 awsmanagedmachinepool_controller.go:200] "Reconciling AWSManagedMachinePool"
I0613 04:01:45.744882       1 launchtemplate.go:73] "checking for existing launch template"
E0613 04:01:46.178107       1 controller.go:329] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool capi-managed-cluster/[REDACTED]: failed to reconcile nodegroup version: nodegroup version is nil" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="capi-managed-cluster/[REDACTED]" namespace="capi-managed-cluster" name="[REDACTED]" reconcileID="a0c1977f-6e74-499e-805c-147fe74d8e39"
I0613 04:01:46.178945       1 awsmanagedmachinepool_controller.go:200] "Reconciling AWSManagedMachinePool"
I0613 04:01:46.179150       1 launchtemplate.go:73] "checking for existing launch template"

```

**Comment by nueavv** [comment]
Hi  @faiq  @vincepri Could you please review this PR when you have time?

**Review by damdo — COMMENTED** [review]
/lgtm

/assign @richardcase

**Comment by pavansokkenagaraj** [comment]
Should this check be handled here? 
If the status is `NodegroupStatusCreateFailed`, the `version` field is empty, causing a nil pointer error. 
For graceful handling, the reconciliation should stop and return an error when this condition is encountered.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50c23fbd7efde4bb5ec8069c621cca4ae54f12f7/pkg/cloud/services/eks/nodegroup.go#L538-L543

File: pkg/cloud/services/eks/nodegroup.go [hunk 1]
```diff
@@ -333,6 +333,11 @@ func (s *NodegroupService) reconcileNodegroupVersion(ng *eks.Nodegroup) error {
 			return fmt.Errorf("parsing EKS version from spec: %w", err)
 		}
 	}
+
+	// Check for nil pointers before dereferencing
+	if ng.Version == nil {
+		return fmt.Errorf("nodegroup version is nil")
+	}
```
Comment (pavansokkenagaraj) [inline pkg/cloud/services/eks/nodegroup.go:340]: Without the nodegroup status, just returning nil is not enough here
```
[capa-controller-manager-76cf9fbf-z76f8] 1 controller.go:316] "Reconciler error" err="failed to reconcile machine pool for AWSManagedMachinePool cluster-685bea824f4b2e09eb5c7654/gpu-worker--r5mh: failed to reconcile nodegroup version: nodegroup version is nil" controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="cluster-685bea824f4b2e09eb5c7654/gpu-worker--r5mh" namespace="cluster-685bea824f4b2e09eb5c7654" name="gpu-worker--r5mh" reconcileID="f863c423-57f7-4bac-838e-82ffabf9e73a"
```
